# The PNC pilot

Dr. Wheeler has previously conducted some pilot SNF analyses within the Philadelphia Neurodevelopmental Cohort (PNC) dataset.

Those previous analyses are outlined in this chapter.

## Script 1: Setting up the data

```{r eval = FALSE}
library(readr)

# rsFMRI
## import
rsfc_data_wb <- read.csv(paste0("data/pnc/pilot-snf/",
    "PNC_rsfc_QC_passed_present_in_all_imaging_modalities_whole_brain.csv"),
    check.names = FALSE)

# clinical data
## import
clinical <- read.csv("data/pnc/pilot-snf/tbi_pnc_clinical.csv",
                     check.names = FALSE)
clinical <- clinical[, -1]

## recode factors as numbers 1=yes, 0=no
names(clinical)
clinical$TBI_LOC <- ifelse(clinical$TBI_LOC == "yes", 1, 0)
clinical$TBI_AMN <- ifelse(clinical$TBI_AMN == "yes", 1, 0)
clinical$TBI_HEADACHE <- ifelse(clinical$TBI_HEADACHE == "yes", 1, 0)

clinical_t <- t(clinical)
colnames(clinical_t) <- as.character(unlist(clinical_t[1, ]))
clinical_t <- clinical_t[-1, ]
rownames(clinical_t) <- c()

# remove ppl with no data or NAs
clinical_t <- as.data.frame(clinical_t)
clinical_t <- clinical_t[colSums(!is.na(clinical_t)) > 0]
clinical_t <- clinical_t[sapply(clinical_t,
    function(clinical_t) !any(is.na(clinical_t)))]

### 6: Demographic Info for TBI participants
demographics <- read.csv("data/pnc/pilot-snf/tbi_pnc_dem.csv",
    check.names = FALSE)
demographics <- demographics[, -1]

demographics_datadic <- colnames(demographics)

# recode factors as numbers:
## Sex: 1=male, 2=female, 3=unknown
## Race 1=EA=1, 2=AA=2, 3=other
names(demographics)
demographics$Sex <-
    ifelse(demographics$Sex == "M", 1,
        ifelse(demographics$Sex == "F", 2, 3))

demographics_t <- t(demographics)
colnames(demographics_t) <- as.character(unlist(demographics_t[1, ]))
demographics_t <- demographics_t[-1, ]
rownames(demographics_t) <- c()

# remove ppl with no data or NAs
demographics_t <- as.data.frame(demographics_t)
demographics_t <- demographics_t[colSums(!is.na(demographics_t)) > 0]
demographics_t <- demographics_t[sapply(demographics_t,
    function(demographics_t) !any(is.na(demographics_t)))]


# Checking for same participants across datatypes

# Create vectors with the column names (which are always the subject IDs)
colnames_rsfc <- colnames(rsfc_data_wb)
colnames_clinical <- colnames(clinical_t)
colnames_demographics <- colnames(demographics_t)

# 'common_subs' contains only the IDs found in all datatypes)
common_subs <- Reduce(intersect,
    list(colnames_rsfc, colnames_clinical, colnames_demographics))

# Subset each dataframes to only have information from common_subs
rsfc <- rsfc_data_wb[, which(names(rsfc_data_wb) %in% c(common_subs))]
clinical <- clinical_t[, which(names(clinical_t) %in% c(common_subs))]
demographics <-
    demographics_t[, which(names(demographics_t) %in% c(common_subs))]

# Check for matchine number of participants across datatypes
dim(rsfc)
dim(clinical)
dim(demographics)

# Check the sample names to see if they are in the same order in all 3 datasets
# compare IDs for rsfc and clinical
sum(colnames(rsfc) == colnames(clinical)) == length(colnames(rsfc))
# compare IDs for tract clinical and demographic
sum(colnames(clinical) ==
    colnames(demographics)) ==
    length(colnames(clinical))
```

## Script 2: SNF

```{r}
### Run SNF using PNC data - TBI participants only

# PART 1: SNF SETUP

# load libraries
library(SNFtool)
library(dplyr)
library(ggplot2)

# source script that loads and checks data -
# source('ABCD-TBI_SNF_data_setup_script1.R')

# Perform the standard recommended normalisation
rsfc.norm <- standardNormalization(rsfc)
clinical.norm <- standardNormalization(clinical)
demographics.norm <- standardNormalization(demographics)

# For the subsequent analysis we need to transpose the data so the rows become columnns and the columns become rows
rsfc.norm.tr <- t(rsfc.norm)
clinical.norm.tr <- t(clinical.norm)
demographics.norm.tr <- t(demographics.norm)

#Now, the idea is to create similarity matrices (these can also be considered as graphs) for each of the data frames. For this it is necessary to set some parameters:
# 1) the number of neighbours, K (must be greater than 1; normally between 20 and 30)
# 2) the hyperparameter alpha, which is normally between 0.3 and 0.8
# 3) the number of iterations, usually between 10 and 50

#Before creating the affinity matrices, we need to first create distance matrices
rsfc.dist = dist2(as.matrix(rsfc.norm.tr),as.matrix(rsfc.norm.tr))
clinical.dist = dist2(as.matrix(clinical.norm.tr),as.matrix(clinical.norm.tr))
demographics.dist = dist2(as.matrix(demographics.norm.tr),as.matrix(demographics.norm.tr))

#Now create the similarity matrices (graphs) using the distance matrices and the K, alpha and T parameters
# First, set all the parameters:
K = 10 # number of neighbors, must be greater than 1. usually (10~30), I have used k = 10, as there are 85 subjects and it looks from Laura stefanik's article that k = number of subjets/10
alpha = 0.5 # hyperparameter, usually (0.3~0.8)
T = 50 # number of Iterations, usually (10~50)

# Construct similarity graphs (can be considered to be fully connected networks)
rsfc.sim = affinityMatrix(rsfc.dist, K, alpha)
clinical.sim = affinityMatrix(clinical.dist, K, alpha)
demographics.sim = affinityMatrix(demographics.dist, K, alpha)

# PART 2: SNF RUN
#SNF with rsFC + clinical + demographics 
# first create a list of the 3 similarity "networks"
sim.list <- list(rsfc.sim, clinical.sim, demographics.sim)

# Construct the fused network. This requires the previously defined K (no. neighbours) and T (no. iterations) parameters.
fused.sim = SNF(sim.list, K, T)

# set the row and column names of the fused network to the sample ids
dimnames(fused.sim) <- list(common_subs)

#estimate the number of clusters for fused network
#this command estimates number of clusters - note to add grid search for optimal number of clusters
clusters.est <- estimateNumberOfClustersGivenGraph(fused.sim)

# spectral clustering
# clusters.est as 2(first best) and 3(second best)
clustering.fused.2 <- spectralClustering(fused.sim,2)
clustering.fused.3 <- spectralClustering(fused.sim,3)

# add subject IDs to clustering.fused
common_subs<-as.data.frame(common_subs)
colnames(common_subs)[1] <- "SUBJID"

clustering.fused.2<-as.data.frame(clustering.fused.2)
clustering.fused.2<-cbind(common_subs,clustering.fused.2)
colnames(clustering.fused.2)[2]<- "cluster.2"

clustering.fused.3<-as.data.frame(clustering.fused.3)
clustering.fused.3<-cbind(common_subs,clustering.fused.3)
colnames(clustering.fused.3)[2]<- "cluster.3"

#output a csv with SUBJID and cluster number
write.csv(clustering.fused.2, file = "clusters_fused_2.csv")
write.csv(clustering.fused.3, file = "clusters_fused_3.csv")

#calculates NMI for rsfc conn and output csv
NMIScores.rsfc <-rankFeaturesByNMI(list(rsfc.norm.tr),fused.sim)
write.csv(NMIScores.rsfc, file = "nmi_rsfc.csv")

#calculates NMI for clinical
NMIScores.c <-rankFeaturesByNMI(list(clinical.norm.tr),fused.sim)
write.csv(NMIScores.c, file = "nmi_clin.csv")

#calculates NMI for demographic
NMIScores.d <-rankFeaturesByNMI(list(demographics.norm.tr),fused.sim)
write.csv(NMIScores.d, file = "nmi_dem.csv")

##### make variable names file
rownames.rsfc <- colnames(rsfc)
rownames.clinical <- colnames(clinical)
rownames.demographics <- colnames(demographics)

var<-cbind(rownames.rsfc, rownames.clinical, rownames.demographics)
write.csv(var, file = "variables.csv")
```

