project:
  type: book

book:
  title: "Profiling Biopsychosocial Subtypes of Pediatric Concussion"
  output-file: "abcd_concussion_snf"
  author: "Prashanth Velayudhan"
  search: true
  chapters:
    - index.qmd
    - abcd/01_baseline_extraction.qmd
  repo-url: https://github.com/pvelayudhan/abcd-concussion-snf
  repo-actions: [edit, issue]

execute:
  eval: false
  warning: false
  message: false


bibliography: references.bib

