project:
  type: book

book:
  title: "Profiling Biopsychosocial Subtypes of Pediatric Concussion"
  output-file: "abcd_cbcl_snf"
  author: "Prashanth Velayudhan"
  date: "06/12/2024"
  search: true
  chapters:
    - part: "Home"
      chapters:
        - index.qmd
    - part: "The ABCD dataset"
      chapters:
        - abcd/00_baseline_extraction.qmd
        - abcd/01_baseline_preprocessing.qmd
        - abcd/02_baseline_mtbi_snf.qmd
  repo-url: https://github.com/pvelayudhan/pv-phd-research
  repo-actions: [edit, issue]

execute:
  eval: false
  warning: false
  message: false
