project:
  type: book

book:
  title: "Clustering and classification for paediatric mTBI"
  number-sections: true
  output-file: "pv_phd"
  author: "Prashanth Velayudhan"
  date: "5/4/2022"
  chapters:
    - index.qmd
    - part: "Introduction"
      chapters:
        - introduction/mtbi.qmd
        - introduction/clustering.qmd
        - introduction/hyp_aim_obj_rat.qmd
    - part: "Subtyping in the ABCD Study"
      chapters:
        - abcd/abcd.qmd
        - abcd/neuroimaging.qmd
        - abcd/methods.qmd
        - abcd/pilot.qmd
        - abcd/subjects.qmd
        - abcd/inputs.qmd
        - abcd/snf.qmd
        - abcd/outcomes.qmd
        - abcd/bootstrapping.qmd
        - abcd/conclusion.qmd
    - references.qmd
  repo-url: https://github.com/psvelayudhan/pv-phd-research
  repo-actions: [edit, issue]

bibliography: prashanth_zotcite.bib
filters:
  - zotref.py
csl: nature.xml

format:
  html:
    theme: flatly
  pdf:
    documentclass: scrreprt


