# Extracting input variables

The proposed analyses for this project include the following categories of input variables:

* acute symptoms
* brain structure and function
* demographics
* psychosocial factors
* medical history

Over the next few subsections, I go collect key variables related to these categories from the NDA.


## Acute symptoms

Acute symptoms of interest include:

1. mechanism of injury
2. age at which injury occurred
3. presence and duration of LOC
4. presence of feeling dazed or having memory loss following the injury

```{r child="wheeler-lab/abcd/prashanth-proj/get-inputs/get_acute_symptoms.R"}

```


## Brain structure and function

Variables of interest related to brain structure and function include:

* Structural: T1-weighted multishell diffusion-weighted MRI data
* Functional: resting-state functional MRI data

The 2019 publication by Hagler et al. @hagler_image_2019 outlines the neuroimaging data present in the ABCD dataset in detail.


### Brain structure (!)

**!Known issues**

* Should I exclude automated segmentation ROIs (not a part of Anne's pilot ABCD SNF analyses)

DTI measures are provided for subcortical regions, cortical regions, and major white matter fiber tracts.
The analyses in this report are only concerned with the structure of specific white matter structures, which are present in the following ROIs:

1. Fiber tracts automatically labeled by AtlasTrack [Hagler].

E.g.:

* Element: dmdtifp1_1
* Name: Average fractional anisotropy within DTI atlas tract right fornix
* Aliases: dmri_dti.full.fa_fiber.at_fx.rh, dmri_dtifullfa_fiberat_fxrh

2. Subcortical regions labeled by automated segmentation [Fischl]

E.g.:

* Element: dmdtifp1_211
* Name: Average fractional anisotropy within ASEG ROI left-cerebral-white-matter
* Aliases: dmri_dti.full.md_subcort.aseg_cerebellum.white.matter.lh, dmri_dtifullmd_subcortaseg_cerebellumwhitematterlh

3. Regions of white matter sub-adjacent to cortical regions defined by anatomical parcellation [Desikan]

E.g.:

* Element: dmdtifp1_343
* Name: Average fractional anisotropy within parcellation of sub-adjacent white matter associated with cortical ROI left-medial orbito frontal
* Aliases: dmri_dti.full.fa.wm_cort.desikan_medialorbitofrontal.lh, dmri_dtifullfawm_cortdesikan_medialorbitofrontallh

Detailed lists of the ROIs are present in Supplementary File 2 of @hagler_image_2019.

* Average fractional anisotropy (FA)
* Mean diffusivity (MD)
* Average longitudinal diffusion coefficient
* Average transverse diffusion coefficient
* Fiber tract volume

For my current analyses, I include:

* non-compound regions
* FA and MD

(include rationale for why only look at these 2 and why not include GM)

The dTI data are located in the files *abcd_dmdtifp101.txt* and *abcd_dmdtifp201* (titled ABCD dMRI DTI Full Part 1 and 2 respectively).
All variables follow the naming scheme 'dmdtifp1_x', where x ranges from 1 to 1185.

The dMRI variables I will include for my analyses are shown in the table below.

| Variable              | Segmentation method     | Region type               | Element name in the NDA      |
|-----------------------|-------------------------|---------------------------|------------------------------|
| Fractional anisotropy | AtlasTrack              | Major WM tracts           | dmdtifp1_1 to dmdtifp1_35    |
| Fractional anisotropy | Anatomical parcellation | Sub-adjacent white matter | dmdtifp_331 to dmdtifp1_401  |
| Fractional anisotropy | Automated segmentation  | WM of major brain region  | dmdtifp1_211, 214, 228, 231  |
| Mean diffusivity      | AtlasTrack              | Major WM tracts           | dmdtifp1_43 to dmdtifp1_79   |
| Mean diffusivity      | Anatomical parcellation | Sub-adjacent white matter | dmdtifp1_402 to dmdtifp1_472 |
| Mean diffusivity      | Automated segmentation  | WM of major brain region  | dmdtifp1_241, 244, 258, 261  |


## Demographics (!)

**!Known issues**

* I am unsure of how clustering over categorical (nominal) variables, such as race or sex, will influence outcomes
* The inclusion of these variables will simply incentivize the clustering algorithm to assign members from the same sex/race/ethnicity to the same cluster
* May be worth it to try clustering with and without these variables and check how outcomes differ

Demographic variables to be included in the analyses are:

* Age
* Sex
* Race
* Ethnicity
* Socioeconomic status
* Pubertal development status

Age and sex are commonly included in the ABCD study's data files.


## Psychosocial factors

Psychosocial factors of interest include:

* family function
* prosocial behaviour
* loneliness
* healthy behaviours
* parent psychopathology


## Medical history

Medical history variables of interest include:

* Number of previous head injuries
* History of headaches


## Handling data types of mixed input

The original similarity network fusion paper @wang_similarity_2014 suggests using a scaled Euclidean distance for continuous variables, chi-squared distance for discrete variables, and agreement-based measure for binary variables.
The paper also indicates that SNF may be used to incorporate arbitrary types of discrete (binary or categorical) data alongside continuous data, and that the compatibility of the selected data sources can be verified using normalized mutual information scores.
This topic is addressed further in the methods section.



## Post-concussion symptoms
