# Hypotheses, aims, objectives, and rationales

I hypothesize that:

1. Distinct subtypes of subjects in a chronic-stage following paediatric mTBI, defined by variables related to the patient, their environment, and their injury, exist.
2. Those subtypes will be associated with distinct profiles of persistent post-concussive symptoms.
3. The heterogeneity among children that have sustained an mTBI is largely driven by variables that influence or were influenced by the injury, suggesting that the identified subtypes would not match the subtypes identified in the general paediatric population
4. Identified subtypes (and subject membership among those subtypes) will be relatively invariant over time

If these hypotheses are supported, identifying such subtypes may significantly improve our understanding of risk factors, prognoses, and potential mechanistic targets for therapeutic intervention. As well, variables that define these subtypes may inform data-driven patient stratification for upcoming clinical trials.

Though the proposed work for this project is primarily exploratory in nature, I intend on testing these hypotheses over the course of completing the project aims listed below. Predictions that follow the above hypotheses are described under the relevant objective descriptions.

