# Pre-imputation Data Exploration

## Sex and Gender

```{r}
library(ggplot2)
library(readr)
library(dplyr)
library(here)
library(UpSetR)
library(abcdutils)

core_path <- path_maker(here(paste0("data/abcd/core2")))
input_path <- path_maker(here(paste0("data/abcd/inputs")))
sub_path <- path_maker(here(paste0("data/abcd/subjects")))
fig_path <- path_maker(here(paste0("data/abcd/results/figures")))

import <- function(path) {
    return(abcd_load(core_path(path)))
}

mtbi_subjects <- read_subjects(sub_path("2024_04_17_mtbi_subjects.csv"))
uninjured_subjects <- read_subjects(sub_path("2024_04_17_uninjured_subjects.csv"))

gish_p_gi <- import("gender-identity-sexual-health/gish_p_gi.csv")
gish_y_gi <- import("gender-identity-sexual-health/gish_y_gi.csv")
```

```{r}
###############################################################################
# Gender check
###############################################################################
# Youth

mtbi_y_sex_t3 <- gish_y_gi |>
    filter_subjects(mtbi_subjects) |>
    filter_timepoint(t = 3) |>
    dplyr::select(
        subjectkey,
        kbi_sex_assigned_at_birth
    ) |>
    dplyr::rename(
        "y_sex" = "kbi_sex_assigned_at_birth"
    ) |>
    dplyr::mutate(group = "mtbi", t = 3) |>
    dplyr::mutate(
        y_sex = dplyr::case_when(
            y_sex == 1 ~ "M",
            y_sex == 2 ~ "F",
            TRUE ~ NA
        )
    )

uninj_y_sex_t3 <- gish_y_gi |>
    filter_subjects(uninjured_subjects) |>
    filter_timepoint(t = 3) |>
    dplyr::select(
        subjectkey,
        kbi_sex_assigned_at_birth
    ) |>
    dplyr::rename(
        "y_sex" = "kbi_sex_assigned_at_birth"
    ) |>
    dplyr::mutate(group = "uninj", t = 3) |>
    dplyr::mutate(
        y_sex = dplyr::case_when(
            y_sex == 1 ~ "M",
            y_sex == 2 ~ "F",
            TRUE ~ NA
        )
    )

mtbi_y_gender_t3 <- get_y_gender(
    gish_y_gi,
    mtbi_subjects,
    t = 3
) |>
    dplyr::mutate(group = "mtbi", t = 3)

search_dd("kbi_sex_assigned_at_birth")

search_dd("kbi_gender")$"notes"

mtbi_y_gender_t3$"y_gender"

uninj_y_gender_t3 <- get_y_gender(
    gish_y_gi,
    uninjured_subjects,
    t = 3
) |>
    dplyr::mutate(group = "uninj", t = 3)

search_dd("demo_gender_id_v2")

# Parent
d_gender_mtbi_p <- get_p_gender(
    gish_p_gi,
    mtbi_subjects,
    t = 0
) |>
    dplyr::mutate(group = "mtbi", t = 0)

d_gender_uninj_p <- get_p_gender(
    gish_p_gi,
    uninjured_subjects,
    t = 0
) |>
    dplyr::mutate(group = "uninj", t = 0)

d_sex_mtbi_p <- d_sex_mtbi |>
    dplyr::rename(
        "p_sex" = "sex"
    ) |>
    dplyr::mutate(group = "mtbi", t = 0)

d_sex_uninj_p <- d_sex_uninj |>
    dplyr::rename(
        "p_sex" = "sex"
    ) |>
    dplyr::mutate(group = "uninj", t = 0)

d_sex_mtbi_p <- get_sex(
    gish_p_gi,
    mtbi_subjects,
    t = 0,
    as_numeric = FALSE,
    only_m_f = FALSE
) |>
    dplyr::mutate(group = "mtbi", t = 0)

d_sex_uninj_p <- get_sex(
    gish_p_gi,
    uninjured_subjects,
    t = 0,
    as_numeric = FALSE,
    only_m_f = FALSE
) |>
    dplyr::mutate(group = "uninj", t = 0)

y_sex <- rbind(mtbi_y_sex_t3, uninj_y_sex_t3)
y_gender <- rbind(mtbi_y_gender_t3, uninj_y_gender_t3)
p_sex <- rbind(d_sex_mtbi_p, d_sex_uninj_p)
p_gender <- rbind(d_gender_mtbi_p, d_gender_uninj_p)

y_report <- dplyr::full_join(y_sex, y_gender) |>
    dplyr::select(-t)

p_report <- dplyr::full_join(p_sex, p_gender) |>
    dplyr::rename("p_sex" = "sex") |>
    dplyr::select(-t)

sag <- dplyr::full_join(
    y_report,
    p_report
)

sag$"id" <- 1:nrow(sag)

sag_uninj <- dplyr::filter(sag, group == "uninj")
sag_mtbi <- dplyr::filter(sag, group == "mtbi")

sag_mtbi$"y_sex" |> unique()
sag_uninj$"y_sex" |> unique()

sag_mtbi$"y_gender" |> unique()
sag_uninj$"y_gender" |> unique()

sag_mtbi$"p_gender" |> unique()
sag_uninj$"p_gender" |> unique()

sag_mtbi$"p_sex" |> unique()

sag_uninj$"p_sex" |> unique()

###############################################################################
# SEX
# youth-report sex F
sag_mtbi_ysf <- sag_mtbi |>
    dplyr::filter(y_sex == "F") |>
    dplyr::select(id) |>
    unlist() |>
    as.numeric()
sag_uninj_ysf <- sag_uninj |>
    dplyr::filter(y_sex == "F") |>
    dplyr::select(id) |>
    unlist() |>
    as.numeric()

# youth-report sex M
sag_mtbi_ysm <- sag_mtbi |>
    dplyr::filter(y_sex == "M") |>
    dplyr::select(id) |>
    unlist() |>
    as.numeric()
sag_uninj_ysm <- sag_uninj |>
    dplyr::filter(y_sex == "M") |>
    dplyr::select(id) |>
    unlist() |>
    as.numeric()

# youth-report sex NA
sag_mtbi_ysn <- sag_mtbi |>
    dplyr::filter(is.na(y_sex)) |>
    dplyr::select(id) |>
    unlist() |>
    as.numeric()
sag_uninj_ysn <- sag_uninj |>
    dplyr::filter(is.na(y_sex)) |>
    dplyr::select(id) |>
    unlist() |>
    as.numeric()

# parent-report sex F
sag_mtbi_psf <- sag_mtbi |>
    dplyr::filter(p_sex == "F") |>
    dplyr::select(id) |>
    unlist() |>
    as.numeric()
sag_uninj_psf <- sag_uninj |>
    dplyr::filter(p_sex == "F") |>
    dplyr::select(id) |>
    unlist() |>
    as.numeric()

# parent-report sex M
sag_mtbi_psm <- sag_mtbi |>
    dplyr::filter(p_sex == "M") |>
    dplyr::select(id) |>
    unlist() |>
    as.numeric()
sag_uninj_psm <- sag_uninj |>
    dplyr::filter(p_sex == "M") |>
    dplyr::select(id) |>
    unlist() |>
    as.numeric()

# parent-report sex NA
sag_mtbi_psn <- sag_mtbi |>
    dplyr::filter(is.na(p_sex)) |>
    dplyr::select(id) |>
    unlist() |>
    as.numeric()
sag_uninj_psn <- sag_uninj |>
    dplyr::filter(is.na(p_sex)) |>
    dplyr::select(id) |>
    unlist() |>
    as.numeric()

###############################################################################
# GENDER
# youth-report gender F
sag_mtbi_ygf <- sag_mtbi |>
    dplyr::filter(y_gender == "F") |>
    dplyr::select(id) |>
    unlist() |>
    as.numeric()
sag_uninj_ygf <- sag_uninj |>
    dplyr::filter(y_gender == "F") |>
    dplyr::select(id) |>
    unlist() |>
    as.numeric()

# youth-report gender M
sag_mtbi_ygm <- sag_mtbi |>
    dplyr::filter(y_gender == "M") |>
    dplyr::select(id) |>
    unlist() |>
    as.numeric()
sag_uninj_ygm <- sag_uninj |>
    dplyr::filter(y_gender == "M") |>
    dplyr::select(id) |>
    unlist() |>
    as.numeric()

# youth-report gender NB
sag_mtbi_ygnb <- sag_mtbi |>
    dplyr::filter(y_gender == "NB") |>
    dplyr::select(id) |>
    unlist() |>
    as.numeric()
sag_uninj_ygnb <- sag_uninj |>
    dplyr::filter(y_gender == "NB") |>
    dplyr::select(id) |>
    unlist() |>
    as.numeric()

# youth-report gender NA
sag_mtbi_ygn <- sag_mtbi |>
    dplyr::filter(is.na(y_gender)) |>
    dplyr::select(id) |>
    unlist() |>
    as.numeric()
sag_uninj_ygn <- sag_uninj |>
    dplyr::filter(is.na(y_gender)) |>
    dplyr::select(id) |>
    unlist() |>
    as.numeric()

# parent-report gender F
sag_mtbi_pgf <- sag_mtbi |>
    dplyr::filter(p_gender == "F") |>
    dplyr::select(id) |>
    unlist() |>
    as.numeric()
sag_uninj_pgf <- sag_uninj |>
    dplyr::filter(p_gender == "F") |>
    dplyr::select(id) |>
    unlist() |>
    as.numeric()

# parent-report gender M
sag_mtbi_pgm <- sag_mtbi |>
    dplyr::filter(p_gender == "M") |>
    dplyr::select(id) |>
    unlist() |>
    as.numeric()
sag_uninj_pgm <- sag_uninj |>
    dplyr::filter(p_gender == "M") |>
    dplyr::select(id) |>
    unlist() |>
    as.numeric()

# parent-report gender NB
sag_mtbi_pgnb <- sag_mtbi |>
    dplyr::filter(p_gender == "NB") |>
    dplyr::select(id) |>
    unlist() |>
    as.numeric()
sag_uninj_pgnb <- sag_uninj |>
    dplyr::filter(p_gender == "NB") |>
    dplyr::select(id) |>
    unlist() |>
    as.numeric()

# parent-report gender missing
sag_mtbi_pgn <- sag_mtbi |>
    dplyr::filter(is.na(p_gender)) |>
    dplyr::select(id) |>
    unlist() |>
    as.numeric()
sag_uninj_pgn <- sag_uninj |>
    dplyr::filter(is.na(p_gender)) |>
    dplyr::select(id) |>
    unlist() |>
    as.numeric()
```

```{r}

mtbi_gender_plot <- UpSetR::upset(
    fromList(
        list(
            "YouthF" = sag_mtbi_ygf,
            "YouthM" = sag_mtbi_ygm,
            "YouthNB" = sag_mtbi_ygnb,
            "YouthMissing" = sag_mtbi_ygn,
            "ParentF" = sag_mtbi_pgf,
            "ParentNB" = sag_mtbi_pgnb,
            "ParentM" = sag_mtbi_pgm,
            "ParentMissing" = sag_mtbi_pgn
        )
    ),
    intersections = list(
        list("ParentF", "YouthF"),
        list("ParentMissing", "YouthMissing"),
        list("ParentMissing", "YouthF"),
        list("ParentMissing", "YouthNB"),
        list("ParentNB", "YouthMissing"),
        list("ParentF", "YouthMissing"),
        list("ParentM", "YouthMissing"),
        list("ParentF", "YouthNB"),
        list("ParentNB", "YouthF"),
        list("ParentM", "YouthF"),
        list("ParentM", "YouthNB"),
        list("ParentMissing", "YouthM"),
        list("ParentF", "YouthM"),
        list("ParentM", "YouthM")
    ),
    text.scale = 2.5,
    keep.order = FALSE,
    empty.intersections = "on"
)
mtbi_gender_plot

uninj_gender_plot <- UpSetR::upset(
    fromList(
        list(
            "YouthF" = sag_uninj_ygf,
            "YouthM" = sag_uninj_ygm,
            "YouthNB" = sag_uninj_ygnb,
            "YouthMissing" = sag_uninj_ygn,
            "ParentF" = sag_uninj_pgf,
            "ParentM" = sag_uninj_pgm,
            "ParentNB" = sag_uninj_pgnb,
            "ParentMissing" = sag_uninj_pgn
        )
    ),
    sets = c(
            "YouthMissing",
            "ParentMissing",
            "YouthNB",
            "ParentNB",
            "YouthF",
            "ParentF",
            "YouthM",
            "ParentM"
    ),
    intersections = list(
        list("ParentF", "YouthF"),
        list("ParentMissing", "YouthMissing"),
        list("ParentMissing", "YouthF"),
        list("ParentMissing", "YouthNB"),
        list("ParentNB", "YouthMissing"),
        list("ParentF", "YouthMissing"),
        list("ParentM", "YouthMissing"),
        list("ParentF", "YouthNB"),
        list("ParentNB", "YouthF"),
        list("ParentM", "YouthF"),
        list("ParentM", "YouthNB"),
        list("ParentMissing", "YouthM"),
        list("ParentF", "YouthM"),
        list("ParentM", "YouthM")
    ),
    text.scale = 2.5,
    keep.order = TRUE,
    empty.intersections = "on"
)
uninj_gender_plot

mtbi_sex_plot <- UpSetR::upset(
    fromList(
        list(
            "YouthF" = sag_uninj_ysf,
            "YouthM" = sag_uninj_ysm,
            "YouthMissing" = sag_uninj_ysn,
            "ParentF" = sag_uninj_psf,
            "ParentM" = sag_uninj_psm,
            "ParentMissing" = sag_uninj_psn
        )
    ),
    sets = c(
            "YouthMissing",
            "ParentMissing",
            "YouthF",
            "ParentF",
            "YouthM",
            "ParentM"
    ),
    intersections = list(
        list("ParentF", "YouthF"),
        list("ParentMissing", "YouthMissing"),
        list("ParentMissing", "YouthF"),
        list("ParentF", "YouthMissing"),
        list("ParentM", "YouthMissing"),
        list("ParentM", "YouthF"),
        list("ParentMissing", "YouthM"),
        list("ParentF", "YouthM"),
        list("ParentM", "YouthM")
    ),
    text.scale = 2,
    keep.order = TRUE,
    empty.intersections = "on"
)
mtbi_sex_plot

uninj_sex_plot <- UpSetR::upset(
    fromList(
        list(
            "YouthF" = sag_uninj_ysf,
            "YouthM" = sag_uninj_ysm,
            "YouthMissing" = sag_uninj_ysn,
            "ParentF" = sag_uninj_psf,
            "ParentM" = sag_uninj_psm,
            "ParentMissing" = sag_uninj_psn
        )
    ),
    sets = c(
            "YouthMissing",
            "ParentMissing",
            "YouthF",
            "ParentF",
            "YouthM",
            "ParentM"
    ),
    intersections = list(
        list("ParentM", "YouthM"),
        list("ParentF", "YouthM"),
        list("ParentF", "YouthF"),
        list("ParentMissing", "YouthMissing"),
        list("ParentMissing", "YouthF"),
        list("ParentF", "YouthMissing"),
        list("ParentM", "YouthMissing"),
        list("ParentM", "YouthF"),
        list("ParentMissing", "YouthM")
    ),
    text.scale = 2,
    keep.order = FALSE,
    empty.intersections = "on"
)
uninj_sex_plot

ggsave()


library(ComplexUpset)

movies = as.data.frame(ggplot2movies::movies)
head(movies, 3)
genres = colnames(movies)[18:24]
genres

```

```{r}
library(ggplot2)
library(ComplexUpset)
library(fastDummies)

movies = ggplot2movies::movies
genres = c("Action", "Animation", "Comedy", "Drama", "Documentary", "Romance")

upset(
    movies,
    genres,
    queries = list(
        upset_query(
            intersect=c("Drama", "Comedy"),
            color="red",
            fill="red",
            only_components=c("intersections_matrix", "Intersection size")
        ),
        upset_query(
            set = "Drama",
            fill = "blue"
        )
    ),
    min_size = 10,
    width_ratio = 0.1
)

movies

sex_and_gender[is.na(sex_and_gender)] <- "NA"
sex_and_gender <- sex_and_gender |>
    dummy_cols(
        select_columns = c("y_sex", "y_gender", "p_sex", "p_gender"),
        remove_selected_columns = TRUE
    ) |>
    tibble()

sex_and_gender_mtbi <- sex_and_gender |>
    dplyr::filter(group == "mtbi")  |>
    dplyr::select(-group, -id)

sex_and_gender_uninj <- sex_and_gender |>
    dplyr::filter(group == "uninj")  |>
    dplyr::select(-group, -id)

sex_col_ids <- grep("sex", colnames(sex_and_gender))
gender_col_ids <- grep("gender", colnames(sex_and_gender))
sex_cols <- colnames(sex_and_gender)[sex_col_ids]
gender_cols <- colnames(sex_and_gender)[gender_col_ids]

upset(
    sex_and_gender_uninj,
    sex_cols
)

library(patchwork)

upset(
    sex_and_gender_uninj,
    gender_cols,
    intersections = list(
        c("p_gender_M", "y_gender_M"),
        c("p_gender_F", "y_gender_F"),
        c("p_gender_M", "y_gender_NA"),
        c("p_gender_F", "y_gender_NA"),
        c("p_gender_F", "y_gender_NB"),
        c("p_gender_M", "y_gender_NB"),
        c("p_gender_NB", "y_gender_NB"),
        c("p_gender_NA", "y_gender_NA"),
        c("p_gender_F", "y_gender_M"),
        c("p_gender_M", "y_gender_F"),
        c("p_gender_NA", "y_gender_F"),
        c("p_gender_NA", "y_gender_M"),
        c("p_gender_NA", "y_gender_NB"),
        c("p_gender_NB", "y_gender_F"),
        c("p_gender_NB", "y_gender_NA")
    )
)

upset(
    sex_and_gender_mtbi,
    gender_cols,
    intersections = list(
        c("p_gender_M", "y_gender_M"),
        c("p_gender_F", "y_gender_F"),
        c("p_gender_F", "y_gender_NA"),
        c("p_gender_M", "y_gender_NA"),
        c("p_gender_F", "y_gender_NB"),
        c("p_gender_M", "y_gender_NB"),
        c("p_gender_NB", "y_gender_NB"),
        c("p_gender_NA", "y_gender_NA"),
        c("p_gender_F", "y_gender_M"),
        c("p_gender_M", "y_gender_F"),
        c("p_gender_NA", "y_gender_F"),
        c("p_gender_NA", "y_gender_M"),
        c("p_gender_NA", "y_gender_NB"),
        c("p_gender_NB", "y_gender_F"),
        c("p_gender_NB", "y_gender_NA")
    )
)

pf ynb, pf ym, pm ynb, pm yf, yf pna, ym pna, ynb pna,

```
