# Meta-clustering characterization

## Meta-clustering

```{r eval = FALSE}
library(here)
library(readr)
library(dplyr)
library(scabcd)
library(abcdutils)
library(ggplot2)


proc_path <- path_maker(here(paste0("data/abcd/results/processed")))
fig_path <- path_maker(here(paste0("data/abcd/results/figures")))

#output_matrix_full <- read_csv(proc_path("2023_02_22_om.csv"))
om_0_0_train <- read_csv(proc_path("2023_04_05_om_0_0_train.csv"))

min(om_0_0_train$min_p_val) #4.6e-08
min(om_0_0_train$mean_p_val) #0.0016

mc_results_0_0_train <- meta_cluster(om_0_0_train)

write_csv(data.frame(mc_results_0_0_train),
          proc_path("mc_results_0_0_train.csv", date = TRUE))

mc_results_0_0_train <-
    as.matrix(read_csv(proc_path("2023_04_05_mc_results_0_0_train.csv")))

colnames(mc_results) <- as.character(seq_len(nrow(mc_results)))
rownames(mc_results) <- as.character(seq_len(nrow(mc_results)))

# Visualizing the meta-clustering results
mc_heatmap(mc_results_0_0_train,
           save = fig_path("mc_results_0_0_train.png", date = TRUE))

# Trying to plot the input design matrix as a heatmap
mc_order_0_0_train <- get_pheatmap_order(mc_results_0_0_train)

design_matrix <- data.frame(read_csv(proc_path("full_design_matrix.csv")))

dm_heatmap(design_matrix[mc_order_0_0_train, ],
           fig_path("dm_reordered_0_0_train.png", date = TRUE))

mc_pvals_0_0_train <- p_val_select(om_0_0_train)

mc_pvals_reordered_0_0_train <- mc_pvals_0_0_train[mc_order_0_0_train, ]

# This is the actual important graph
pvals_pheatmap(mc_pvals_reordered_0_0_train,
               save = fig_path("mc_pvals_0_0_train.png", date = TRUE))
```


## Picking new top rows based on each cluster size

```{r}
#output_matrix_full <- read_csv(proc_path("2023_02_22_om.csv"))
om_0_0_train <- read_csv(proc_path("2023_04_05_om_0_0_train.csv"))

unique(om_0_0_train$nclust)

top_oms <- top_om_per_cluster(om_0_0_train)

top_oms$"significance"

top_oms

top_oms |>
    dplyr::select(c("significance", "row_id"))

write_csv(top_oms, proc_path("top_oms_0_0_train.csv", date = TRUE))

om_scatter(top_oms,
           save = fig_path("top_oms_0_0_train_scatter.png", date = TRUE))
```
