# Matching

## Importing packages and establishing file paths

```{r}
library(readr)
library(abcdutils)
library(here)
library(metasnf)
library(progressr)
library(rlist)
library(MatchIt)

input_path <- path_maker(here(paste0("data/abcd/inputs")))
proc_path <- path_maker(here(paste0("data/abcd/results/processed")))
fig_path <- path_maker(here(paste0("data/abcd/results/figures")))
sub_path <- path_maker(here(paste0("data/abcd/subjects")))

mtbi_subjects <- read_csv(sub_path("2024_08_17_mtbi_subjects.csv"))
uninjured_subjects <- read_csv(sub_path("2024_08_17_uninjured_subjects.csv"))
```

## Importing data

```{r}
all_dls <- list.load(input_path("2024_08_17_all_dls.rds"))

mtbi_full_data_list_1 <- list.load(input_path("2024_08_22_mtbi_full_data_list_1.rds"))
mtbi_full_oom_list_1 <- list.load(input_path("2024_08_22_mtbi_full_oom_list_1.rds"))

uninj_dl_imp_1 <- all_dls$"uninj_data_lists"$"imp_1"
uninj_dl_imp_2 <- all_dls$"uninj_data_lists"$"imp_2"
uninj_dl_imp_3 <- all_dls$"uninj_data_lists"$"imp_3"
uninj_dl_imp_4 <- all_dls$"uninj_data_lists"$"imp_4"
uninj_dl_imp_5 <- all_dls$"uninj_data_lists"$"imp_5"

uninj_ol_imp_1 <- all_dls$"uninj_oom_lists"$"imp_1"
uninj_ol_imp_2 <- all_dls$"uninj_oom_lists"$"imp_2"
uninj_ol_imp_3 <- all_dls$"uninj_oom_lists"$"imp_3"
uninj_ol_imp_4 <- all_dls$"uninj_oom_lists"$"imp_4"
uninj_ol_imp_5 <- all_dls$"uninj_oom_lists"$"imp_5"
```

## Matching

Finding matched uninjured controls for each mtbi subject based on a variety of variables.
Matching will be done based on the first imputed dataset of the baseline data.

```{r}
names(mtbi_full_data_list_1)
names(mtbi_full_oom_list_1)

matching_vars_1 <- c(
    "d_income",
    "p_parent_psych",
    "d_race"
)

matching_vars_2 <- c(
    "d_income",
    "d_race",
    "d_sex",
    "d_pubertal"
)
matching_vars_3 <- c(
    "p_parent_psych"
)

matching_vars_4 <- c(
    "cbcl",
    "sds_total_probs"
)
```

```{r}
names(mtbi_full_data_list_1)

# 5 different combinations for the dl matching

c(mtbi_full_data_list_1, mtbi_full_oom_list_1)

mtbi_dl_match <- mtbi_full_data_list_1[matching_vars_1]
mtbi_dl_match_2 <- mtbi_full_data_list_1[matching_vars_2]
mtbi_dl_match_3 <- mtbi_full_data_list_1[matching_vars_3]
mtbi_ol_match_4 <- mtbi_full_oom_list_1[matching_vars_4]

# 4 different combinations * 5 imputations for the uninjured
uninj_dl_match_imp_1_1 <- uninj_dl_imp_1[matching_vars_1]
uninj_dl_match_imp_1_2 <- uninj_dl_imp_1[matching_vars_2]
uninj_dl_match_imp_1_3 <- uninj_dl_imp_1[matching_vars_3]
uninj_ol_match_imp_1_4 <- uninj_ol_imp_1[matching_vars_4]

uninj_dl_match_imp_2_1 <- uninj_dl_imp_2[matching_vars_1]
uninj_dl_match_imp_2_2 <- uninj_dl_imp_2[matching_vars_2]
uninj_dl_match_imp_2_3 <- uninj_dl_imp_2[matching_vars_3]
uninj_ol_match_imp_2_4 <- uninj_ol_imp_2[matching_vars_4]

uninj_dl_match_imp_3_1 <- uninj_dl_imp_3[matching_vars_1]
uninj_dl_match_imp_3_2 <- uninj_dl_imp_3[matching_vars_2]
uninj_dl_match_imp_3_3 <- uninj_dl_imp_3[matching_vars_3]
uninj_ol_match_imp_3_4 <- uninj_ol_imp_3[matching_vars_4]

uninj_dl_match_imp_4_1 <- uninj_dl_imp_4[matching_vars_1]
uninj_dl_match_imp_4_2 <- uninj_dl_imp_4[matching_vars_2]
uninj_dl_match_imp_4_3 <- uninj_dl_imp_4[matching_vars_3]
uninj_ol_match_imp_4_4 <- uninj_ol_imp_4[matching_vars_4]

uninj_dl_match_imp_5_1 <- uninj_dl_imp_5[matching_vars_1]
uninj_dl_match_imp_5_2 <- uninj_dl_imp_5[matching_vars_2]
uninj_dl_match_imp_5_3 <- uninj_dl_imp_5[matching_vars_3]
uninj_ol_match_imp_5_4 <- uninj_ol_imp_5[matching_vars_4]


###############################################################################
# Conversion to dataframes
###############################################################################
mtbi_df_match_1 <- mtbi_dl_match_1 |> collapse_dl()
mtbi_df_match_2 <- mtbi_dl_match_2 |> collapse_dl()
mtbi_df_match_3 <- mtbi_dl_match_3 |> collapse_dl()
mtbi_df_match_4 <- mtbi_ol_match_4 |> collapse_dl()

```

```{r}



mtbi_matching_df$"mtbi" <- 1
uninj_matching_df$"mtbi" <- 0

matching_df <- rbind(mtbi_matching_df, uninj_matching_df)

# Nearest neighbour matching
matching_results <- matchit(
    formula(mtbi ~ household_income + race + age + sex),
    data = matching_df,
    method = "nearest"
)

# The uninjured matching has 0 mean diff on all matching variables
matching_summary <- capture.output(print(summary(matching_results)))

writeLines(matching_summary, proc_path("demo_matching_summary.txt", TRUE))

grDevices::png(
    filename = fig_path("demo_matching_summary.png", TRUE),
    width = 1000,
    height = 500,
    res = 120
)
plot(summary(matching_results), position = "right")
grDevices::dev.off()

# Obtain the matched data
matched_data <- match.data(matching_results)

# Extract the control group from the matched data
matched_uninj <- matched_data |>
    dplyr::filter(mtbi == 0) |>
    dplyr::select(subjectkey)

write_csv(matched_uninj, sub_path("demo_matched_uninj.csv", TRUE))
```

## Loading data and out of model lists

```{r}

matched_uninj <- read_csv(sub_path("2024_06_13_demo_matched_uninj.csv"))

all_dls |> names()

uninj_dls <- all_dls[
    c(
        "uninj_data_lists",
        "uninj_pooled_data_lists",
        "uninj_oom_lists",
        "uninj_pooled_oom_lists"
    )
]

subject_filter_dl <- function(data_list, subject_vector) {
    data_list <- data_list |>
        lapply(
            function(x) {
                keep_subs <- x$"data"$"subjectkey" %in% subject_vector
                x$"data" <- x$"data"[keep_subs, ]
                return(x)
            }
        )
    return(data_list)
}

demo_matched_uninj_dls <- lapply(
    uninj_dls,
    function(x) {
        lapply(
            x,
            function(y) {
                subject_filter_dl(y, matched_uninj$"subjectkey")
            }
        )
    }
)

list.save(
    demo_matched_uninj_dls,
    input_path("demo_matched_uninj_dls.rds", TRUE)
)
```
