# SNF in Uninjured Controls

## Importing packages and establishing file paths

```{r}
library(readr)
library(abcdutils)
library(here)
library(metasnf)
library(progressr)
library(rlist)
library(MatchIt)

input_path <- path_maker(here(paste0("data/abcd/inputs")))
proc_path <- path_maker(here(paste0("data/abcd/results/processed")))
fig_path <- path_maker(here(paste0("data/abcd/results/figures")))
sub_path <- path_maker(here(paste0("data/abcd/subjects")))

mtbi_subjects <- read_csv(sub_path("2024_02_13_mtbi_subjects.csv"))
uninjured_subjects <- read_csv(sub_path("2024_02_13_uninjured_subjects.csv"))
mtbi_subjects_train <- read_csv(sub_path("2024_02_13_mtbi_train_subjects.csv"))

source("abcd/functions.R")

```

## Loading data and out of model lists

```{r}
data_list_mu1 <- list.load(input_path("2024_03_17_data_list_mu1.rds"))
data_list_mu2 <- list.load(input_path("2024_03_17_data_list_mu2.rds"))
data_list_mu3 <- list.load(input_path("2024_03_17_data_list_mu3.rds"))
data_list_mu4 <- list.load(input_path("2024_03_17_data_list_mu4.rds"))
data_list_mu5 <- list.load(input_path("2024_03_17_data_list_mu5.rds"))
data_list_mpu1 <- list.load(input_path("2024_03_17_data_list_mpu1.rds"))
data_list_mpu2 <- list.load(input_path("2024_03_17_data_list_mpu2.rds"))
data_list_mpu3 <- list.load(input_path("2024_03_17_data_list_mpu3.rds"))
data_list_mpu4 <- list.load(input_path("2024_03_17_data_list_mpu4.rds"))
data_list_mpu5 <- list.load(input_path("2024_03_17_data_list_mpu5.rds"))
oom_list_mu1 <- list.load(input_path("2024_03_17_oom_list_mu1.rds"))
oom_list_mu2 <- list.load(input_path("2024_03_17_oom_list_mu2.rds"))
oom_list_mu3 <- list.load(input_path("2024_03_17_oom_list_mu3.rds"))
oom_list_mu4 <- list.load(input_path("2024_03_17_oom_list_mu4.rds"))
oom_list_mu5 <- list.load(input_path("2024_03_17_oom_list_mu5.rds"))
oom_list_mpu1 <- list.load(input_path("2024_03_17_oom_list_mpu1.rds"))
oom_list_mpu2 <- list.load(input_path("2024_03_17_oom_list_mpu2.rds"))
oom_list_mpu3 <- list.load(input_path("2024_03_17_oom_list_mpu3.rds"))
oom_list_mpu4 <- list.load(input_path("2024_03_17_oom_list_mpu4.rds"))
oom_list_mpu5 <- list.load(input_path("2024_03_17_oom_list_mpu5.rds"))
```

## Generating custom distance measures

```{r}
my_distance_metrics <- generate_distance_metrics_list(
    continuous_distances = list(
        "standard_norm_euclidean" = sn_euclidean_distance
    ),
    discrete_distances = list(
        "standard_norm_euclidean" = sn_euclidean_distance
    ),
    ordinal_distances = list(
        "standard_norm_euclidean" = sn_euclidean_distance
    ),
)

clust_algs_list <- generate_clust_algs_list(
    "three_cluster_spectral" = spectral_three,
    disable_base = TRUE
)

settings_matrix_mu <- generate_settings_matrix(
    data_list_mu1,
    nrow = 200,
    seed = 42,
    clustering_algorithms = clust_algs_list,
    distance_metrics_list = my_distance_metrics
)

write_csv(settings_matrix_mu, proc_path("settings_matrix_mu.csv", TRUE))

settings_matrix_mu <- read_csv(proc_path("2024_03_18_settings_matrix_mu.csv"))

```

## SNF for each of the imputations

```{r}

# Uninjured only imputed
# Imputation 1
start <- proc.time()
progressr::with_progress({
    solutions_matrix_mu1 <- batch_snf(
        data_list = data_list_mu1,
        settings_matrix = settings_matrix_mu,
        distance_metrics_list = my_distance_metrics,
        clust_algs_list = clust_algs_list,
        processes = "max"
    )
})
proc.time() - start
write_csv(solutions_matrix_mu1, proc_path("solutions_matrix_mu1.csv", TRUE))
# Imputation 2
start <- proc.time()
progressr::with_progress({
    solutions_matrix_mu2 <- batch_snf(
        data_list = data_list_mu2,
        settings_matrix = settings_matrix_mu,
        distance_metrics_list = my_distance_metrics,
        clust_algs_list = clust_algs_list,
        processes = "max"
    )
})
proc.time() - start
write_csv(solutions_matrix_mu2, proc_path("solutions_matrix_mu2.csv", TRUE))
# Imputation 3
start <- proc.time()
progressr::with_progress({
    solutions_matrix_mu3 <- batch_snf(
        data_list = data_list_mu3,
        settings_matrix = settings_matrix_mu,
        distance_metrics_list = my_distance_metrics,
        clust_algs_list = clust_algs_list,
        processes = "max"
    )
})
proc.time() - start
write_csv(solutions_matrix_mu3, proc_path("solutions_matrix_mu3.csv", TRUE))
# Imputation 4
start <- proc.time()
progressr::with_progress({
    solutions_matrix_mu4 <- batch_snf(
        data_list = data_list_mu4,
        settings_matrix = settings_matrix_mu,
        distance_metrics_list = my_distance_metrics,
        clust_algs_list = clust_algs_list,
        processes = "max"
    )
})
proc.time() - start
write_csv(solutions_matrix_mu4, proc_path("solutions_matrix_mu4.csv", TRUE))
# Imputation 5
start <- proc.time()
progressr::with_progress({
    solutions_matrix_mu5 <- batch_snf(
        data_list = data_list_mu5,
        settings_matrix = settings_matrix_mu,
        distance_metrics_list = my_distance_metrics,
        clust_algs_list = clust_algs_list,
        processes = "max"
    )
})
proc.time() - start
write_csv(solutions_matrix_mu5, proc_path("solutions_matrix_mu5.csv", TRUE))
#
# Uninjured pooled imputed
# Imputation 1
start <- proc.time()
progressr::with_progress({
    solutions_matrix_mpu1 <- batch_snf(
        data_list = data_list_mpu1,
        settings_matrix = settings_matrix_mu,
        distance_metrics_list = my_distance_metrics,
        clust_algs_list = clust_algs_list,
        processes = "max"
    )
})
proc.time() - start
write_csv(solutions_matrix_mpu1, proc_path("solutions_matrix_mpu1.csv", TRUE))
# Imputation 2
start <- proc.time()
progressr::with_progress({
    solutions_matrix_mpu2 <- batch_snf(
        data_list = data_list_mpu2,
        settings_matrix = settings_matrix_mu,
        distance_metrics_list = my_distance_metrics,
        clust_algs_list = clust_algs_list,
        processes = "max"
    )
})
proc.time() - start
write_csv(solutions_matrix_mpu2, proc_path("solutions_matrix_mpu2.csv", TRUE))
# Imputation 3
start <- proc.time()
progressr::with_progress({
    solutions_matrix_mpu3 <- batch_snf(
        data_list = data_list_mpu3,
        settings_matrix = settings_matrix_mu,
        distance_metrics_list = my_distance_metrics,
        clust_algs_list = clust_algs_list,
        processes = "max"
    )
})
proc.time() - start
write_csv(solutions_matrix_mpu3, proc_path("solutions_matrix_mpu3.csv", TRUE))
# Imputation 4
start <- proc.time()
progressr::with_progress({
    solutions_matrix_mpu4 <- batch_snf(
        data_list = data_list_mpu4,
        settings_matrix = settings_matrix_mu,
        distance_metrics_list = my_distance_metrics,
        clust_algs_list = clust_algs_list,
        processes = "max"
    )
})
proc.time() - start
write_csv(solutions_matrix_mpu4, proc_path("solutions_matrix_mpu4.csv", TRUE))
# Imputation 5
start <- proc.time()
progressr::with_progress({
    solutions_matrix_mpu5 <- batch_snf(
        data_list = data_list_mpu5,
        settings_matrix = settings_matrix_mu,
        distance_metrics_list = my_distance_metrics,
        clust_algs_list = clust_algs_list,
        processes = "max"
    )
})
proc.time() - start
write_csv(solutions_matrix_mpu5, proc_path("solutions_matrix_mpu5.csv", TRUE))
```

## Re-importing the generated solutions

```{r}
solutions_matrix_mu1 <- read_csv(proc_path("2024_03_18_solutions_matrix_mu1.csv"))
solutions_matrix_mu2 <- read_csv(proc_path("2024_03_18_solutions_matrix_mu2.csv"))
solutions_matrix_mu3 <- read_csv(proc_path("2024_03_18_solutions_matrix_mu3.csv"))
solutions_matrix_mu4 <- read_csv(proc_path("2024_03_18_solutions_matrix_mu4.csv"))
solutions_matrix_mu5 <- read_csv(proc_path("2024_03_18_solutions_matrix_mu5.csv"))
solutions_matrix_mpu1 <- read_csv(proc_path("2024_03_18_solutions_matrix_mpu1.csv"))
solutions_matrix_mpu2 <- read_csv(proc_path("2024_03_18_solutions_matrix_mpu2.csv"))
solutions_matrix_mpu3 <- read_csv(proc_path("2024_03_18_solutions_matrix_mpu3.csv"))
solutions_matrix_mpu4 <- read_csv(proc_path("2024_03_18_solutions_matrix_mpu4.csv"))
solutions_matrix_mpu5 <- read_csv(proc_path("2024_03_18_solutions_matrix_mpu5.csv"))

mu_sm <- do.call(
    "rbind",
    list(
        solutions_matrix_mu1,
        solutions_matrix_mu2,
        solutions_matrix_mu3,
        solutions_matrix_mu4,
        solutions_matrix_mu5,
        solutions_matrix_mpu1,
        solutions_matrix_mpu2,
        solutions_matrix_mpu3,
        solutions_matrix_mpu4,
        solutions_matrix_mpu5
    )
)

write_csv(data.frame(mu_sm), proc_path("mu_sm.csv", TRUE))

mu_ari <- calc_om_aris(mu_sm, processes = "max")
write_csv(data.frame(mu_ari), proc_path("mu_ari.csv", TRUE))

mu_ari_order <- ari_order(mu_ari)
write_csv(data.frame(mu_ari_order), proc_path("mu_ari_order.csv", TRUE))

```

```{r}
mu_sm <- read_csv(proc_path("2024_03_18_mu_sm.csv"))

mu_ari <- read_csv(proc_path("2024_03_18_mu_ari.csv")) |> as.matrix()

mu_ari_order <- unlist(read_csv(proc_path("2024_03_18_mu_ari_order.csv")))
names(mu_ari_order) <- NULL
```

## Full imputation meta clustering plot with impairment levels

```{r}

imputation_labels <- data.frame(
    "imputation" = c(
        rep("u1", 200),
        rep("u2", 200),
        rep("u3", 200),
        rep("u4", 200),
        rep("u5", 200),
        rep("pu1", 200),
        rep("pu2", 200),
        rep("pu3", 200),
        rep("pu4", 200),
        rep("pu5", 200)
    ),
    "pooled" = c(
        rep("yes", 1000),
        rep("no", 1000)
    )
)

imputed_data <- list(
    "u1" = c(data_list_mu1, oom_list_mu1),
    "u2" = c(data_list_mu2, oom_list_mu2),
    "u3" = c(data_list_mu3, oom_list_mu3),
    "u4" = c(data_list_mu4, oom_list_mu4),
    "u5" = c(data_list_mu5, oom_list_mu5),
    "pu5" = c(data_list_mpu5, oom_list_mpu5),
    "pu1" = c(data_list_mpu1, oom_list_mpu1),
    "pu2" = c(data_list_mpu2, oom_list_mpu2),
    "pu3" = c(data_list_mpu3, oom_list_mpu3),
    "pu4" = c(data_list_mpu4, oom_list_mpu4),
    "pu5" = c(data_list_mpu5, oom_list_mpu5)
)

mu_sm_l <- cbind(mu_sm, imputation_labels)

mu_esm <- extend_solutions_imp(
    mu_sm_l,
    imputed_targets = imputed_data,
    min_p = 1e-10,
    calculate_summaries = FALSE,
    processes = "max"
)
write_csv(mu_esm, proc_path("mu_esm.csv", TRUE))

```

```{r}
mu_esm <- read_csv(proc_path("2024_03_18_mu_esm.csv"))
```

```{r}

mu_mc_heatmap <- my_similarity_matrix_heatmap(
    aris = mu_ari,
    aris_order = mu_ari_order,
    extended_solutions = mu_esm,
    show_clusters = FALSE
)

mc_heatmap_save(mu_mc_heatmap, fig_path("mu_mc_heatmap.png", TRUE))

```
