# Validation of Clustering Results

## Label propagation

Here, I check to see if the key inferences observed in the top mTBI cluster still persist when propagated to a held out subset of patients.

## Importing packages and establishing file paths

```{r}
library(readr)
library(abcdutils)
library(here)
library(metasnf)
library(progressr)
library(rlist)
library(ggplot2)
#library(patchwork)
#library(ggsignif)

source(here("abcd/functions.R"))

input_path <- path_maker(here(paste0("data/abcd/inputs")))
proc_path <- path_maker(here(paste0("data/abcd/results/processed")))
fig_path <- path_maker(here(paste0("data/abcd/results/figures")))
sub_path <- path_maker(here(paste0("data/abcd/subjects")))

mtbi_subjects <- read_csv(sub_path("2024_01_28_mtbi_subjects.csv"))
mtbi_train <- read_csv(sub_path("2024_01_28_mtbi_subjects_train.csv"))
mtbi_test <- read_csv(sub_path("2024_01_28_mtbi_subjects_test.csv"))

```

# Importing the top mTBI solution and held out subjects

```{r}

top_mc_b_solution <- read_csv(proc_path("2024_01_30_top_mc_b_solution.csv"))

```

```{r}
data_list_m1 <- list.load(input_path("2024_01_28_data_list_m1.rds"))
data_list_m2 <- list.load(input_path("2024_01_28_data_list_m2.rds"))
data_list_m3 <- list.load(input_path("2024_01_28_data_list_m3.rds"))
data_list_m4 <- list.load(input_path("2024_01_28_data_list_m4.rds"))
data_list_m5 <- list.load(input_path("2024_01_28_data_list_m5.rds"))
oom_list_m1 <- list.load(input_path("2024_01_28_oom_list_m1.rds"))
oom_list_m2 <- list.load(input_path("2024_01_28_oom_list_m2.rds"))
oom_list_m3 <- list.load(input_path("2024_01_28_oom_list_m3.rds"))
oom_list_m4 <- list.load(input_path("2024_01_28_oom_list_m4.rds"))
oom_list_m5 <- list.load(input_path("2024_01_28_oom_list_m5.rds"))

full_data_list_m1 <- list.load(input_path("2024_01_31_full_data_list_m1.rds"))
full_data_list_m2 <- list.load(input_path("2024_01_31_full_data_list_m2.rds"))
full_data_list_m3 <- list.load(input_path("2024_01_31_full_data_list_m3.rds"))
full_data_list_m4 <- list.load(input_path("2024_01_31_full_data_list_m4.rds"))
full_data_list_m5 <- list.load(input_path("2024_01_31_full_data_list_m5.rds"))
full_oom_list_m1 <- list.load(input_path("2024_01_31_full_oom_list_m1.rds"))
full_oom_list_m2 <- list.load(input_path("2024_01_31_full_oom_list_m2.rds"))
full_oom_list_m3 <- list.load(input_path("2024_01_31_full_oom_list_m3.rds"))
full_oom_list_m4 <- list.load(input_path("2024_01_31_full_oom_list_m4.rds"))
full_oom_list_m5 <- list.load(input_path("2024_01_31_full_oom_list_m5.rds"))

```

```{r}

propagated_labels <- lp_row(top_row, full_data_list)

```
