setwd("/hpf/projects/awheeler/Users/pvelayudhan/subtyping/research")

library(readr)
library(abcdutils)
library(here)
library(metasnf)
library(progressr)
library(rlist)
library(MatchIt)
library(tibble)
library(ggplot2)
library(fastDummies)
library(dplyr)
library(tidyr)
library(xtable)
library(patchwork)

input_path   <- path_maker(here(paste0("data/abcd/inputs")))
proc_path    <- path_maker(here(paste0("data/abcd/results/processed")))
fig_path     <- path_maker(here(paste0("data/abcd/results/figures")))
sub_path     <- path_maker(here(paste0("data/abcd/subjects")))
model_path   <- path_maker(here(paste0("data/abcd/results/models")))
unij_ns_subs <- readRDS(sub_path("2025_06_11_unij_no_sibs_subs.rds"))

matched_config <- readRDS(proc_path("2025_06_15_matched_config.rds"))

matched_unij_dl_d_u <- readRDS(proc_path("2025_06_15_matched_unij_dl_d_u.rds"))
matched_unij_dl_p_u <- readRDS(proc_path("2025_06_15_matched_unij_dl_p_u.rds"))
matched_unij_dl_o_u <- readRDS(proc_path("2025_06_15_matched_unij_dl_o_u.rds"))
matched_unij_dl_d_p <- readRDS(proc_path("2025_06_15_matched_unij_dl_d_p.rds"))
matched_unij_dl_p_p <- readRDS(proc_path("2025_06_15_matched_unij_dl_p_p.rds"))
matched_unij_dl_o_p <- readRDS(proc_path("2025_06_15_matched_unij_dl_o_p.rds"))
matched_unij_dl_dp_u <- readRDS(proc_path("2025_06_15_matched_unij_dl_dp_u.rds"))
matched_unij_dl_do_u <- readRDS(proc_path("2025_06_15_matched_unij_dl_do_u.rds"))
matched_unij_dl_op_u <- readRDS(proc_path("2025_06_15_matched_unij_dl_op_u.rds"))
matched_unij_dl_dp_p <- readRDS(proc_path("2025_06_15_matched_unij_dl_dp_p.rds"))
matched_unij_dl_do_p <- readRDS(proc_path("2025_06_15_matched_unij_dl_do_p.rds"))
matched_unij_dl_op_p <- readRDS(proc_path("2025_06_15_matched_unij_dl_op_p.rds"))
matched_unij_dl_dpo_p <- readRDS(proc_path("2025_06_15_matched_unij_dl_dpo_p.rds"))
matched_unij_dl_dpo_u <- readRDS(proc_path("2025_06_15_matched_unij_dl_dpo_u.rds"))
random_unij_dl_u1 <- readRDS(proc_path("2025_06_15_random_unij_dl_u1.rds"))
random_unij_dl_p1 <- readRDS(proc_path("2025_06_15_random_unij_dl_p1.rds"))

## SNF
#matched_unij_sol_df_d_u <- progressr::with_progress(batch_snf(matched_unij_dl_d_u, matched_config, processes = "max"))
#saveRDS(matched_unij_sol_df_d_u, proc_path("matched_unij_sol_df_d_u.rds", TRUE))
#cat("snf 1 done\n")
#matched_unij_sol_df_p_u <- progressr::with_progress(batch_snf(matched_unij_dl_p_u, matched_config, processes = "max"))
#saveRDS(matched_unij_sol_df_p_u, proc_path("matched_unij_sol_df_p_u.rds", TRUE))
#cat("snf 2 done\n")
#matched_unij_sol_df_o_u <- progressr::with_progress(batch_snf(matched_unij_dl_o_u, matched_config, processes = "max"))
#saveRDS(matched_unij_sol_df_o_u, proc_path("matched_unij_sol_df_o_u.rds", TRUE))
#cat("snf 3 done\n")
#matched_unij_sol_df_d_p <- progressr::with_progress(batch_snf(matched_unij_dl_d_p, matched_config, processes = "max"))
#saveRDS(matched_unij_sol_df_d_p, proc_path("matched_unij_sol_df_d_p.rds", TRUE))
#cat("snf 4 done\n")
#matched_unij_sol_df_p_p <- progressr::with_progress(batch_snf(matched_unij_dl_p_p, matched_config, processes = "max"))
#saveRDS(matched_unij_sol_df_p_p, proc_path("matched_unij_sol_df_p_p.rds", TRUE))
#cat("snf 5 done\n")

matched_unij_sol_df_o_p <- progressr::with_progress(batch_snf(matched_unij_dl_o_p, matched_config, processes = "max"))
saveRDS(matched_unij_sol_df_o_p, proc_path("matched_unij_sol_df_o_p.rds", TRUE))
cat("snf 6 done\n")
matched_unij_sol_df_dp_u <- progressr::with_progress(batch_snf(matched_unij_dl_dp_u, matched_config, processes = "max"))
saveRDS(matched_unij_sol_df_dp_u, proc_path("matched_unij_sol_df_dp_u.rds", TRUE))
cat("snf 7 done\n")
matched_unij_sol_df_do_u <- progressr::with_progress(batch_snf(matched_unij_dl_do_u, matched_config, processes = "max"))
saveRDS(matched_unij_sol_df_do_u, proc_path("matched_unij_sol_df_do_u.rds", TRUE))
cat("snf 8 done\n")
matched_unij_sol_df_op_u <- progressr::with_progress(batch_snf(matched_unij_dl_op_u, matched_config, processes = "max"))
saveRDS(matched_unij_sol_df_op_u, proc_path("matched_unij_sol_df_op_u.rds", TRUE))
cat("snf 9 done\n")
matched_unij_sol_df_dp_p <- progressr::with_progress(batch_snf(matched_unij_dl_dp_p, matched_config, processes = "max"))
saveRDS(matched_unij_sol_df_dp_p, proc_path("matched_unij_sol_df_dp_p.rds", TRUE))
cat("snf 10 done\n")
#
#matched_unij_sol_df_do_p <- progressr::with_progress(batch_snf(matched_unij_dl_do_p, matched_config, processes = "max"))
#saveRDS(matched_unij_sol_df_do_p, proc_path("matched_unij_sol_df_do_p.rds", TRUE))
#cat("snf 11 done\n")
#matched_unij_sol_df_op_p <- progressr::with_progress(batch_snf(matched_unij_dl_op_p, matched_config, processes = "max"))
#saveRDS(matched_unij_sol_df_op_p, proc_path("matched_unij_sol_df_op_p.rds", TRUE))
#cat("snf 12 done\n")
#matched_unij_sol_df_dpo_p <- progressr::with_progress(batch_snf(matched_unij_dl_dpo_p, matched_config, processes = "max"))
#saveRDS(matched_unij_sol_df_dpo_p, proc_path("matched_unij_sol_df_dpo_p.rds", TRUE))
#cat("snf 13 done\n")
#matched_unij_sol_df_dpo_u <- progressr::with_progress(batch_snf(matched_unij_dl_dpo_u, matched_config, processes = "max"))
#saveRDS(matched_unij_sol_df_dpo_u, proc_path("matched_unij_sol_df_dpo_u.rds", TRUE))
#cat("snf 14 done\n")
#random_unij_sol_df_s1 <- progressr::with_progress(batch_snf(random_unij_dl_s1, matched_config, processes = "max"))
#saveRDS(random_unij_sol_df_s1, proc_path("random_unij_sol_df_s1.rds", TRUE))
#cat("snf 15 done\n")
#random_unij_sol_df_p1 <- progressr::with_progress(batch_snf(random_unij_dl_p1, matched_config, processes = "max"))
#saveRDS(random_unij_sol_df_p1, proc_path("random_unij_sol_df_p1.rds", TRUE))
