# Clustering with hierarchical / k-means algorithms

```{r}
library(readr)
library(abcdutils)
library(metasnf)
library(here)
library(fastDummies)
library(mclust)

input_path      <- path_maker(here(paste0("data/abcd/inputs")))
proc_path       <- path_maker(here(paste0("data/abcd/results/processed")))
fig_path        <- path_maker(here(paste0("data/abcd/results/figures")))
sub_path        <- path_maker(here(paste0("data/abcd/subjects")))
```

```{r}
mtbi_dl_1 <- readRDS(input_path("2025_09_15_mtbi_dl_1.rds"))
mtbi_ful_df <- readRDS(proc_path("2025_09_16_mtbi_ful_df.rds"))

mtbi_dl_2 <- readRDS(input_path("2025_09_15_mtbi_dl_2.rds"))
mtbi_dl_3 <- readRDS(input_path("2025_09_15_mtbi_dl_3.rds"))
mtbi_dl_4 <- readRDS(input_path("2025_09_15_mtbi_dl_4.rds"))
mtbi_dl_5 <- readRDS(input_path("2025_09_15_mtbi_dl_5.rds"))

mtbi_dls <- list(
    "imp_1" = mtbi_dl_1,
    "imp_2" = mtbi_dl_2,
    "imp_3" = mtbi_dl_3,
    "imp_4" = mtbi_dl_4,
    "imp_5" = mtbi_dl_5
)
```

```{r}
mtbi_dfs <- lapply(
    mtbi_dls,
    function(x) {
        data.frame(x) |>
            dummy_cols(
                select_columns = c("race", "mtbi_mechanism"),
                remove_selected_columns = TRUE,
                remove_most_frequent_dummy = TRUE
            ) |>
            dplyr::select(-uid)
    }
)
```

## No scaling hclust

```{r}
mtbi_dist_mats <- lapply(
    mtbi_dfs,
    function(x) {
        dist(x, method = 'euclidean')
    }
)

mtbi_hclusters <- lapply(
    mtbi_dist_mats,
    function(x) {
        cutree(hclust(x, method = 'average'), k = 3)
    }
)

# Not very similar through hierarchical clustering
adjustedRandIndex(mtbi_hclusters[[1]], mtbi_ful_df$"cluster") # 0.08
adjustedRandIndex(mtbi_hclusters[[2]], mtbi_ful_df$"cluster") # 0.07
adjustedRandIndex(mtbi_hclusters[[3]], mtbi_ful_df$"cluster") # 0.08
adjustedRandIndex(mtbi_hclusters[[4]], mtbi_ful_df$"cluster") # 0.07
adjustedRandIndex(mtbi_hclusters[[5]], mtbi_ful_df$"cluster") # 0.34
```

## Scaling hclust

```{r}
mtbi_sdist_mats <- lapply(
    mtbi_dfs,
    function(x) {
        dist(scale(x), method = 'euclidean')
    }
)

mtbi_shclusters <- lapply(
    mtbi_sdist_mats,
    function(x) {
        cutree(hclust(x, method = 'average'), k = 3)
    }
)

adjustedRandIndex(mtbi_shclusters[[1]], mtbi_ful_df$"cluster") # 0.019
adjustedRandIndex(mtbi_shclusters[[2]], mtbi_ful_df$"cluster") # 0.019
adjustedRandIndex(mtbi_shclusters[[3]], mtbi_ful_df$"cluster") # 0.019
adjustedRandIndex(mtbi_shclusters[[4]], mtbi_ful_df$"cluster") # 0.019
adjustedRandIndex(mtbi_shclusters[[5]], mtbi_ful_df$"cluster") # 0.019
```

## k-means

```{r}
mtbi_kclusters <- lapply(
    mtbi_dfs,
    function(x) {
        kmeans(x, centers = 3, nstart = 20)$"cluster"
    }
)

# Not very similar through hierarchical clustering
adjustedRandIndex(mtbi_kclusters[[1]], mtbi_ful_df$"cluster") # 0.16
adjustedRandIndex(mtbi_kclusters[[2]], mtbi_ful_df$"cluster") # 0.18
adjustedRandIndex(mtbi_kclusters[[3]], mtbi_ful_df$"cluster") # 0.18
adjustedRandIndex(mtbi_kclusters[[4]], mtbi_ful_df$"cluster") # 0.16
adjustedRandIndex(mtbi_kclusters[[5]], mtbi_ful_df$"cluster") # 0.17
```

K-means and hierarchical clustering do not seem to easily reproduce the baseline concussion subtypes.
