# Imputation

Missing value imputation.

1. Load all the data and join into a single dataframe.

```{r}
library(dplyr)
library(abcdutils)
library(readr)
library(purrr)
library(here)

# Inputs
as_mtbi_loc <-
    read_csv(here("data/abcd/inputs/pre-imputation/as_mtbi_loc.csv"))
as_mtbi_mechanism <-
    read_csv(here("data/abcd/inputs/pre-imputation/as_mtbi_mechanism.csv"))
as_mtbi_mem_daze <-
    read_csv(here("data/abcd/inputs/pre-imputation/as_mtbi_mem_daze.csv"))
d_income <-
    read_csv(here("data/abcd/inputs/pre-imputation/d_income.csv"))
d_interview_age <-
    read_csv(here("data/abcd/inputs/pre-imputation/d_interview_age.csv"))
d_mtbi_age <-
    read_csv(here("data/abcd/inputs/pre-imputation/d_mtbi_age.csv"))
d_pubertal_status <-
    read_csv(here("data/abcd/inputs/pre-imputation/d_pubertal_status.csv"))
d_race <-
    read_csv(here("data/abcd/inputs/pre-imputation/d_race_cu.csv"))
d_sex <-
    read_csv(here("data/abcd/inputs/pre-imputation/d_sex.csv"))
mh_headaches <-
    read_csv(here("data/abcd/inputs/pre-imputation/mh_headaches.csv"))
mh_mtbi_count <-
    read_csv(here("data/abcd/inputs/pre-imputation/mh_mtbi_count.csv"))
dm_wmndf <-
    read_csv(here("data/abcd/inputs/pre-imputation/dm_wmndf.csv"))
rm_gord_cor <-
    read_csv(here("data/abcd/inputs/pre-imputation/rm_gord_cor.csv"))
rm_gord_var <-
    read_csv(here("data/abcd/inputs/pre-imputation/rm_gord_var.csv"))
rm_subc_cor <-
    read_csv(here("data/abcd/inputs/pre-imputation/rm_subc_cor.csv"))
rm_subc_var <-
    read_csv(here("data/abcd/inputs/pre-imputation/rm_subc_var.csv"))
sm_cort_sa <-
    read_csv(here("data/abcd/inputs/pre-imputation/sm_cort_sa.csv"))
sm_cort_t <-
    read_csv(here("data/abcd/inputs/pre-imputation/sm_cort_t.csv"))
sm_subc_v <-
    read_csv(here("data/abcd/inputs/pre-imputation/sm_subc_v.csv"))
p_loneliness <-
    read_csv(here("data/abcd/inputs/pre-imputation/p_loneliness.csv"))
p_screen_time <-
    read_csv(here("data/abcd/inputs/pre-imputation/p_screen_time.csv"))
p_family_function <-
    read_csv(here("data/abcd/inputs/pre-imputation/p_family_function.csv"))
p_sports <-
    read_csv(here("data/abcd/inputs/pre-imputation/p_sports.csv"))
p_prosocial <-
    read_csv(here("data/abcd/inputs/pre-imputation/p_prosocial.csv"))
p_parent_psych <-
    read_csv(here("data/abcd/inputs/pre-imputation/p_parent_psych.csv"))
p_exercise <-
    read_csv(here("data/abcd/inputs/pre-imputation/p_exercise.csv"))

# Outcomes
cbcl_headaches <-
    read_csv(here("data/abcd/outputs/pre-imputation/cbcl_headaches.csv"))
cbcl_nausea <-
    read_csv(here("data/abcd/outputs/pre-imputation/cbcl_nausea.csv"))
cbcl_vomiting <-
    read_csv(here("data/abcd/outputs/pre-imputation/cbcl_vomiting.csv"))
cbcl_dizzy <-
    read_csv(here("data/abcd/outputs/pre-imputation/cbcl_dizzy.csv"))
cbcl_overtired <-
    read_csv(here("data/abcd/outputs/pre-imputation/cbcl_overtired.csv"))
cbcl_sleeping_more <-
    read_csv(here("data/abcd/outputs/pre-imputation/cbcl_sleeping_more.csv"))
cbcl_sleeping_less <-
    read_csv(here("data/abcd/outputs/pre-imputation/cbcl_sleeping_less.csv"))
cbcl_depress_r <-
    read_csv(here("data/abcd/outputs/pre-imputation/cbcl_depress_r.csv"))
cbcl_anxiety_r <-
    read_csv(here("data/abcd/outputs/pre-imputation/cbcl_anxiety_r.csv"))
cbcl_attention_r <-
    read_csv(here("data/abcd/outputs/pre-imputation/cbcl_attention_r.csv"))
cbcl_aggressive_r <-
    read_csv(here("data/abcd/outputs/pre-imputation/cbcl_aggressive_r.csv"))
sds_sleep <-
    read_csv(here("data/abcd/outputs/pre-imputation/sds_sleep_df.csv"))
nihtbx_list_fc <-
    read_csv(here("data/abcd/outputs/pre-imputation/nihtbx_list_fc.csv"))
nihtbx_pattern_fc <-
    read_csv(here("data/abcd/outputs/pre-imputation/nihtbx_pattern_fc.csv"))
nihtbx_cardsort_fc <-
    read_csv(here("data/abcd/outputs/pre-imputation/nihtbx_cardsort_fc.csv"))


# put all data frames into a named list

df_list <- list(
    "loss of consciousness" = as_mtbi_loc,
    "mechanism of injury" = as_mtbi_mechanism,
    "memory loss / dazed" = as_mtbi_mem_daze,
    "income" = d_income,
    "interview_age" = d_interview_age,
    "mtbi_age" = d_mtbi_age,
    "pubertal_status" = d_pubertal_status,
    "race" = d_race,
    "sex" = d_sex,
    "headaches" = mh_headaches,
    "mtbi_count" = mh_mtbi_count,
    "wmndf" = dm_wmndf,
    "gord correlations" = rm_gord_cor,
    "gord variances" = rm_gord_var,
    "subc corrrelations" = rm_subc_cor,
    "subc variances" = rm_subc_var,
    "cortical surface area" = sm_cort_sa,
    "cortical thickness" = sm_cort_t,
    "subcortical volume" = sm_subc_v,
    "loneliness" = p_loneliness,
    "screen time" = p_screen_time,
    "family function" = p_family_function,
    "sports" = p_sports,
    "prosocial" = p_prosocial,
    "parent psych" = p_parent_psych,
    "exercise" = p_exercise,
    "cbcl headaches" = cbcl_headaches,
    "cbcl nausea" = cbcl_nausea,
    "cbcl vomiting" = cbcl_vomiting,
    "cbcl dizzy" = cbcl_dizzy,
    "cbcl overtired" = cbcl_overtired,
    "cbcl sleeping more" = cbcl_sleeping_more,
    "cbcl sleeping less" = cbcl_sleeping_less,
    "cbcl depress r" = cbcl_depress_r,
    "cbcl anxiety r" = cbcl_anxiety_r,
    "cbcl attention r" = cbcl_attention_r,
    "cbcl aggressive r" = cbcl_aggressive_r,
    "sds sleep" = sds_sleep,
    "nihtbx list fc" = nihtbx_list_fc,
    "nihtbx pattern fc" = nihtbx_pattern_fc,
    "nihtbx cardsort fc" = nihtbx_cardsort_fc)

```


Missing data visualizations:

```{r eval = FALSE}
vis_missing_by_df(df_list)
```
