# Neuroimaging in ABCD

Over the ABCD study's ten-year period of data collection, participants are scheduled to undergo neuroimaging every 2 years. The details of this neuroimaging are described in detail in a guide by Hagler et al. (@UD6THTQZ#Hagler_Etal_2019). This chapter provides an easier-to-digest summary of that information.

## Types of imaging data collected

Three major types of imaging data are provided by the NDA:

- structural MRI (sMRI)
- diffusion MRI (dMRI)
- functional MRI (fMRI)
    - task-related analysis of functional MRI (task-fMRI)
    - functional connectivity analysis of resting-state fMRI (rsfMRI)

## Parcellations of the brain

Detailed lists of the ROIs are present in Supplementary File 2 of @UD6THTQZ#Hagler_Etal_2019. Below is a list of the different parcellation schemes that have been used for the neuroimaging data in ABCD. Table numbers are referencing tables in Supplementary File 2 of @UD6THTQZ#Hagler_Etal_2019. 


### Parcellations containing white matter parcels

1. **ASEG**: **Subcortical regions** labeled by automated segmentation (Fischl et al., 2002 @QYYLVDUI#Fischl_Etal_2002; supp. table 1)
    - The paper itself refers to whole brain segmentation

2. **APARC-DESIKAN**: **Cortical regions** (including regions of white matter sub-adjacent to cortical regions) defined by anatomical parcellation (Desikan; supp. table 2)

3. **ATLASTRACK**: **Fiber tracts** automatically labeled by AtlasTrack (Hagler; supp. table 6)


### Parcellations not containing white matter parcels

4. **APARC-DESTRIEUX**: **Cortical regions** (Destrieux; supp. table 3)

5. **FUZZY**: Fuzzy-cluster parcellations based on genetic correlation of surface area (Chen; supp. table 4)

6. **GORDON**: Cortical parcels and network membership defined by resting-state functional connectivity (Gordon; supp. table 5)


## Functional MRI


### Resting-state fMRI


#### Summary of all rsfMRI files containing data:

1. ABCD rsfmri Gordon Network Correlations (abcd_betnet02.txt)
    - based on putative cortical area parcellations defined by Gordon et al. in 2016 @2XF56HJP#Gordon_Etal_2016
    - contains the following variables:
        a. a few variables on frame information (e.g., rotation, displacement)
        b. average correlation between various networks and other networks
2. ABCD rsfMRI Destrieux (abcd_mrirsfd01.txt)
    - contains the following variables:
        a. temporal variance in Destrieux ROIs
3. ABCD rsfMRI Temporal Variance (abcd_mrirstv02.txt)
    - contains the following variables:
        a. a few variables on frame information (e.g., rotation, displacement)
        b. temporal variance in APARC (APARC-DESIKAN) ROIs (rsmfri_var_cdk_*)
        c. temporal variance in Gordon cortical parcellations (rsfmri_var_cortgordon_*)
        d. temporal variance in ASEG ROIs (rsfmri_var_scs_*)
4. ABCD rsfMRI Network to Subcortical ROI Correlations (mrirscor02.txt)
    - contains the following variables:
        a. a few variables on frame information (e.g., rotation, displacement)
        b. average correlation between various networks and ASEG ROIs (rsfmri_cor_ngd_*)
5. Resting-State fMRI Survey (restsurv01.txt)
    - A survey following the fMRI asking about the experience

#### rsfMRI measures included in SNF

We examine the following rsfMRI measures in this project:
    - Gordon network correlations (**1b**)
        - This parcellation covers the entire cortical surface and has been reported to have improved intra-parcel BOLD homogeneity over the alternatives [@2XF56HJP#Gordon_Etal_2016; @DDLTCB2D#MirandaDominguez_Etal_2018; @B9QTL6PZ#Marek_Etal_2019]
    - Subcortical correlations (**4b**)
        - This is the only parcellation containing subcortical information
    - Gordon and subcortical temporal variances (**3c** and **3d**)
        - Temporal variances have been found to associate with outcomes in mTBI and other neurological disorders [@VHIR44YA#Dretsch_Etal_2019; @FZL5BIG9#Hu_Etal_2018]


## Structural MRI

This project is interested in three aspects of structural MRI:
    - cortical surface areas
    - cortical thickness(es)
    - subcortical volumes


### Summary of all sMRI files containing data:

- ABCD sMRI Destrieux Parcellation
    - Part 1 (abcd_mrisdp10201.txt)
        - Cortical thickness
        - Sulcal depth
        - Cortical area
        - Cortical volume
    - Part 2 (abcd_mrisdp20201.txt)
    - Part 3 (abcd_mrisdp30201.txt)

# bookmark

### Cortical volumes

- The relevant file is abcd_mrisdp10201, which contains the cortical volumes of ~150 regions
    - variables `mrisdp_*` where * ranges from 454 to 604


### Cortical surface area

- The relevant file is abcd_mrisdp10201, which contains the cortical thickness of ~150 regions
    - variables `mrisdp_*` where * ranges from 303 to 453


### Cortical thickness

- The relevant file is abcd_mrisdp10201, which contains the cortical thickness of ~150 regions
    - variables `mrisdp_*` where * ranges from 1 to 151


## Diffusion MRI

RSI and DTI measures are both calculated for white matter fiber tract ROIs


### RSI measures

The RSI measures used in this project come from the NDA file `mri_rsi_p102.txt`. The variables are all those in the form of `dmri_rsindwm_cdk_*` where `*` represents the shorthand form of any white matter region. These variables are associated with the Desikan parcellation.


### DTI measures

DTI measures are provided for subcortical regions, cortical regions, and major white matter fiber tracts.
