# Normalized mutual information


## Load libraries and data
```{r}
library(scabcd)
library(abcdutils)
library(here)
library(readr)


proc_path <- path_maker(here(paste0("data/abcd/results/processed")))


# Load training data
as_mtbi_loc_train <- read_csv(proc_path("as_mtbi_loc_train.csv"))
as_mtbi_mechanism_train <- read_csv(proc_path("as_mtbi_mechanism_train.csv"))
as_mtbi_mem_daze_train <- read_csv(proc_path("as_mtbi_mem_daze_train.csv"))
d_income_train <- read_csv(proc_path("d_income_train.csv"))
d_interview_age_train <- read_csv(proc_path("d_interview_age_train.csv"))
d_mtbi_age_train <- read_csv(proc_path("d_mtbi_age_train.csv"))
d_pubertal_status_train <- read_csv(proc_path("d_pubertal_status_train.csv"))
d_race_train <- read_csv(proc_path("d_race_train.csv"))
d_sex_train <- read_csv(proc_path("d_sex_train.csv"))
mh_headaches_train <- read_csv(proc_path("mh_headaches_train.csv"))
mh_mtbi_count_train <- read_csv(proc_path("mh_mtbi_count_train.csv"))
dm_wmndf_qc_train <- read_csv(proc_path("dm_wmndf_qc_train.csv"))
rm_gord_cor_qc_train <- read_csv(proc_path("rm_gord_cor_qc_train.csv"))
rm_gord_var_qc_train <- read_csv(proc_path("rm_gord_var_qc_train.csv"))
rm_subc_cor_qc_train <- read_csv(proc_path("rm_subc_cor_qc_train.csv"))
rm_subc_var_qc_train <- read_csv(proc_path("rm_subc_var_qc_train.csv"))
sm_cort_sa_qc_train <- read_csv(proc_path("sm_cort_sa_qc_train.csv"))
sm_cort_t_qc_train <- read_csv(proc_path("sm_cort_t_qc_train.csv"))
sm_subc_v_qc_train <- read_csv(proc_path("sm_subc_v_qc_train.csv"))
p_loneliness_train <- read_csv(proc_path("p_loneliness_train.csv"))
p_screen_time_train <- read_csv(proc_path("p_screen_time_train.csv"))
p_family_function_train <- read_csv(proc_path("p_family_function_train.csv"))
p_sports_train <- read_csv(proc_path("p_sports_train.csv"))
p_prosocial_train <- read_csv(proc_path("p_prosocial_train.csv"))
p_parent_psych_train <- read_csv(proc_path("p_parent_psych_train.csv"))
p_exercise_train <- read_csv(proc_path("p_exercise_train.csv"))
cbcl_headaches_train <- read_csv(proc_path("cbcl_headaches_train.csv"))
cbcl_nausea_train <- read_csv(proc_path("cbcl_nausea_train.csv"))
cbcl_vomiting_train <- read_csv(proc_path("cbcl_vomiting_train.csv"))
cbcl_dizzy_train <- read_csv(proc_path("cbcl_dizzy_train.csv"))
cbcl_overtired_train <- read_csv(proc_path("cbcl_overtired_train.csv"))
cbcl_sleeping_more_train <- read_csv(proc_path("cbcl_sleeping_more_train.csv"))
cbcl_sleeping_less_train <- read_csv(proc_path("cbcl_sleeping_less_train.csv"))
cbcl_depress_train <- read_csv(proc_path("cbcl_depress_train.csv"))
cbcl_anxiety_train <- read_csv(proc_path("cbcl_anxiety_train.csv"))
cbcl_attention_train <- read_csv(proc_path("cbcl_attention_train.csv"))
cbcl_aggressive_train <- read_csv(proc_path("cbcl_aggressive_train.csv"))


# Structure containing all input data
# These data should not contain any NAs, but need not have the same subjects
data_list <- generate_data_list(
    mtbi_loc = as_mtbi_loc_train,
    mtbi_mechanism = as_mtbi_mechanism_train,
    mtbi_mem_daze = as_mtbi_mem_daze_train,
    income = d_income_train,
    interview_age = d_interview_age_train,
    mtbi_age = d_mtbi_age_train,
    pubertal_status = d_pubertal_status_train,
    race = d_race_train,
    sex = d_sex_train,
    headaches = mh_headaches_train,
    mtbi_count = mh_mtbi_count_train,
    wmndf = dm_wmndf_qc_train,
    gord_cor = rm_gord_cor_qc_train,
    gord_var = rm_gord_var_qc_train,
    subc_cor = rm_subc_cor_qc_train,
    subc_var = rm_subc_var_qc_train,
    cort_sa = sm_cort_sa_qc_train,
    cort_t = sm_cort_t_qc_train,
    subc_v = sm_subc_v_qc_train,
    loneliness = p_loneliness_train,
    screen_time = p_screen_time_train,
    family_function = p_family_function_train,
    sports = p_sports_train,
    prosocial = p_prosocial_train,
    parent_psych = p_parent_psych_train,
    exercise = p_exercise_train)

# Structure containing all outcome data
outcome_list <- generate_outcome_list(
    cbcl_nausea = cbcl_nausea_train,
    cbcl_vomiting = cbcl_vomiting_train,
    cbcl_dizzy = cbcl_dizzy_train,
    cbcl_overtired = cbcl_overtired_train,
    cbcl_sleeping_more = cbcl_sleeping_more_train,
    cbcl_sleeping_less = cbcl_sleeping_less_train,
    cbcl_depress = cbcl_depress_train,
    cbcl_anxiety = cbcl_anxiety_train,
    cbcl_attention = cbcl_attention_train,
    cbcl_aggressive = cbcl_aggressive_train)
```

```{r}
top_om_rows <- read_csv(proc_path("2023_03_08_top_om_rows.csv"))

design_matrix <- data.frame(read_csv(proc_path("full_design_matrix.csv")))

top_om_rows

# Just focus on the 2 cluster solution characterized in the poster
top_om_row <- select_om(top_om_rows, 84)
top_dm_row <- select_om(design_matrix, 84)

top_om_row

top_dm_row


mini_data_list <- generate_data_list(
    mtbi_loc = as_mtbi_loc_train,
    mtbi_mechanism = as_mtbi_mechanism_train)

single_data_list <- generate_data_list(
    mtbi_loc = as_mtbi_loc_train)


# The NMI process doesn't require any SNFing, just affinity matrix step.
nmi_df <- calc_nmi(top_om_row, data_list)

nmi_df

nmi_df1 <- calc_nmi(top_om_rows[1, ], data_list)
nmi_df2 <- calc_nmi(top_om_rows[2, ], data_list)
nmi_df3 <- calc_nmi(top_om_rows[3, ], data_list)


library(ggplot2)


nmi_df1$input <- factor(nmi_df1$input, levels = nmi_df1$input)
nmi_df2$input <- factor(nmi_df2$input, levels = nmi_df2$input)
nmi_df3$input <- factor(nmi_df3$input, levels = nmi_df3$input)

nmi_df1$nmi <- as.numeric(nmi_df1$nmi)
nmi_df2$nmi <- as.numeric(nmi_df2$nmi)
nmi_df3$nmi <- as.numeric(nmi_df3$nmi)

str(nmi_df)

ggplot(nmi_df2, aes(x = input, y = nmi)) +
    geom_point() +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
    ggtitle("2-cluster solution used in poster") +
    ggplot2::theme(text = ggplot2::element_text(size = 20))
ggsave(fig_path("two_cluster_poster_nmis.png", date = TRUE))

ggplot(nmi_df3, aes(x = input, y = nmi)) +
    geom_point() +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
    ggtitle("5 cluster solution, all input vars (the identical mc)") +
    ggplot2::theme(text = ggplot2::element_text(size = 20))
ggsave(fig_path("five_cluster_all_inputs_nmis.png", date = TRUE))

ggplot(nmi_df1, aes(x = input, y = nmi)) +
    geom_point() +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
    ggtitle("5 cluster solution, lowest p-values from the second MC") +
    ggplot2::theme(text = ggplot2::element_text(size = 20))
ggsave(fig_path("five_cluster_second_mc_lowest_pvals_nmis.png", date = TRUE))

```
