# Overview

The Adolescent Brain Cognitive Development (ABCD) study is a long term study of pediatric development tracking patients from 21 research sites across the United States.

## Mild traumatic brain injuries

Four studies have previously investigated mTBI using the ABCD dataset. 

* Guberman et al., 2022 @YBZQILQ8#Guberman_Etal_2022
* Cook and Iversion, 2021 @LJNVCZAQ#Cook_Iverson_2021
* Cook, Karr, Iverson, 2022 @R8GH75M8#Cook_Karr_Iverson_2022
* Dufour et al., 2020 @HFXNXFZS#Dufour_Etal_2020

The TBI information of the ABCD dataset is split across a few files:

* `abcd_otbi01.txt`: the raw, modified Ohio State TBI screen given at baseline
* `abcd_tbi01.txt`: summary scores of abcd_otbi01.txt
* `abcd_lpohstbi01.txt`: all longitudinal follow-ups of the baseline screen
* `abcd_lsstbi01.txt`: summary scores of abcd_lpohstbi01.txt

## Neuroimaging {#sec-abcdneuroimaging}

Over the ABCD study's ten-year period of data collection, participants are scheduled to undergo neuroimaging every 2 years. The details of this neuroimaging are described in detail in a guide by Hagler et al. (@UD6THTQZ##Hagler_Etal_2019). This chapter provides an easier-to-digest summary of that information.

### Types of imaging data collected

Three major types of imaging data are provided by the NDA:

- structural MRI (sMRI)
- diffusion MRI (dMRI)
- functional MRI (fMRI)
    - task-related analysis of functional MRI (task-fMRI)
    - functional connectivity analysis of resting-state fMRI (rsfMRI)

### Parcellations of the brain

Detailed lists of the ROIs are present in Supplementary File 2 of @UD6THTQZ##Hagler_Etal_2019. Below is a list of the different parcellation schemes that have been used for the neuroimaging data in ABCD. Table numbers are referencing tables in Supplementary File 2 of @UD6THTQZ#Hagler_Etal_2019. 


#### Parcellations containing white matter parcels

1. **ASEG**: **Subcortical regions** labeled by automated segmentation (Fischl et al., 2002 @QYYLVDUI##Fischl_Etal_2002; supp. table 1)
    - The paper itself refers to whole brain segmentation

2. **APARC-DESIKAN**: **Cortical regions** (including regions of white matter sub-adjacent to cortical regions) defined by anatomical parcellation (Desikan; supp. table 2)

3. **ATLASTRACK**: **Fiber tracts** automatically labeled by AtlasTrack (Hagler; supp. table 6)


#### Parcellations not containing white matter parcels

4. **APARC-DESTRIEUX**: **Cortical regions** (Destrieux; supp. table 3)

5. **FUZZY**: Fuzzy-cluster parcellations based on genetic correlation of surface area (Chen; supp. table 4)

6. **GORDON**: Cortical parcels and network membership defined by resting-state functional connectivity (Gordon; supp. table 5)


### Functional MRI


#### Resting-state fMRI


##### Summary of all rsfMRI files containing data:

1. ABCD rsfmri Gordon Network Correlations (abcd_betnet02.txt)
    - based on putative cortical area parcellations defined by Gordon et al. in 2016 @2XF56HJP##Gordon_Etal_2016
    - contains the following variables:
        a. a few variables on frame information (e.g., rotation, displacement; rsfmri_c_ngd_tr:rsfmri_c_ngd_maxrot)
        b. average correlation between various networks and other networks (rsfmri_c_ngd_ad_ngd_ad:rsfmri_c_ngd_vs_ngd_vs)
2. ABCD rsfMRI Destrieux (abcd_mrirsfd01.txt)
    - contains the following variables:
        a. temporal variance in Destrieux ROIs (mrirsfd*)
3. ABCD rsfMRI Network to Subcortical ROI Correlations (mrirscor02.txt)
    - contains the following variables:
        a. a few variables on frame information (e.g., rotation, displacement; rsfmri_cor_ngd_scs_tr:rsfmri_cor_ngd_scs_maxrot)
        b. average correlation between various networks and ASEG ROIs (rsfmri_cor_ngd_*)
4. ABCD rsfMRI Temporal Variance (abcd_mrirstv02.txt)
    - contains the following variables:
        a. a few variables on frame information (e.g., rotation, displacement; rsfmri_var_tr:rsfmri_var_maxrot)
        b. temporal variance in APARC (APARC-DESIKAN) ROIs (rsmfri_var_cdk_*)
        c. temporal variance in Gordon cortical parcellations (rsfmri_var_cortgordon_*)
        d. temporal variance in ASEG ROIs (rsfmri_var_scs_*)
5. Resting-State fMRI Survey (restsurv01.txt)
    - A survey following the fMRI asking about the experience

##### rsfMRI measures included in SNF

We examine the following rsfMRI measures in this project:
    - Gordon network correlations (**1b**)
        - This parcellation covers the entire cortical surface and has been reported to have improved intra-parcel BOLD homogeneity over the alternatives [@2XF56HJP##Gordon_Etal_2016; @DDLTCB2D#MirandaDominguez_Etal_2018; @B9QTL6PZ#Marek_Etal_2019]
    - Subcortical correlations (**3b**)
        - This is the only parcellation containing subcortical information
    - Gordon and subcortical temporal variances (**4c** and **4d**)
        - Temporal variances have been found to associate with outcomes in mTBI and other neurological disorders [@VHIR44YA##Dretsch_Etal_2019; @FZL5BIG9#Hu_Etal_2018]


### Structural MRI

This project is interested in three aspects of structural MRI:
    - cortical surface areas
    - cortical thickness(es)
    - subcortical volumes


#### Summary of all sMRI files containing data:

- ABCD sMRI Destrieux Parcellation
    - Part 1 (`abcd_mrisdp10201.txt`)
        - Cortical thickness
        - Sulcal depth
        - Cortical area
        - Cortical volume
    - Part 2 (`abcd_mrisdp20201.txt`)
    - Part 3 (`abcd_mrisdp30201.txt`)
- ABCD sMRI 
    - Part 1 (`abcd_smrip10201.txt`)



#### Subcortical volumes

- The relevant file is `abcd_smrip10201.txt`, which contains the volumes of 46 subcortical regions partitioned by ASEG
    - variables `smri_vol_subcortaseg_*` where `*` ranges from `cerebralwhitematterlh` to `subcorticalgrayvolume`


#### Cortical surface area

- The relevant file is `abcd_mrisdp10201.txt`, which contains the cortical thickness of ~150 regions
    - variables `mrisdp_*`, where `*` ranges from 303 to 453


#### Cortical thickness

- The relevant file is `abcd_mrisdp10201.txt`, which contains the cortical thickness of ~150 regions
    - variables `mrisdp_*`, where `*` ranges from 1 to 151


#### Other sMRI measures

Measures that are not a part of the subtyping analyses, but are listed for reference. 

- Cortical volumes
    - The relevant file is abcd_mrisdp10201, which contains the cortical volumes of ~150 regions
        - variables `mrisdp_*` where * ranges from 454 to 604


### Diffusion MRI

RSI and DTI measures are both calculated for white matter fiber tract ROIs


#### RSI measures

The RSI measures used in this project come from the NDA file `mri_rsi_p102.txt`. The variables are all those in the form of `dmri_rsindwm_cdk_*` where `*` represents the shorthand form of any white matter region. These variables are associated with the Desikan parcellation.


#### DTI measures

DTI measures are provided for subcortical regions, cortical regions, and major white matter fiber tracts.

Across all parcellations, the options for examining white matter FA and MD are in the table below.

| Variable              | Segmentation method     | Region type               | Element name in the NDA      |
|-----------------------|-------------------------|---------------------------|------------------------------|
| Fractional anisotropy | AtlasTrack              | Major WM tracts           | dmdtifp1_1 to dmdtifp1_35    |
| Fractional anisotropy | Anatomical parcellation | Sub-adjacent white matter | dmdtifp1_331 to dmdtifp1_401  |
| Fractional anisotropy | Automated segmentation  | WM of major brain region  | dmdtifp1_211, 214, 228, 231  |
| Mean diffusivity      | AtlasTrack              | Major WM tracts           | dmdtifp1_43 to dmdtifp1_79   |
| Mean diffusivity      | Anatomical parcellation | Sub-adjacent white matter | dmdtifp1_402 to dmdtifp1_472 |
| Mean diffusivity      | Automated segmentation  | WM of major brain region  | dmdtifp1_241, 244, 258, 261  |

I had considered using these variables originally, but am using RSI measures instead.



## Psychosocial resilience {#sec-abcdpsych}

Information about psychosocial resilience is spread across several data files in the NDA. In this project, I use the following aspects of psychosocial resilience.


### Parent psychopathology

Information about parent psychopathology is collected from the "ABCD Parent Adult Self Report Scores Aseba (ASR)" file (`abcd_asrs01.txt`; category Questionnaire; release 4.0).

Psychometric scores in the ABCD study are often reported as raw scores and as T-scores (Z score transformed to have a mean of 50 and a standard deviation of 10). The NDA mentions that the T-scores are in relation to norms for each gender at ages 18-35 and 36-59 (for the adult self report). The age and gender of the parents can be obtained from the Parent Demographics Surveys (`abcd_lpds01.txt`; demographics category, `pdem02.txt`; demographics category). At the time of writing this, I am not completely sure about whether it is better to use the raw scores or the T-scores for subtyping.

Consider the situation that there are significant differences in the raw scores depending on the reporting parent's age group and gender. Using the T-scores will ensure that the signal provided by this information will be whether or not the parent's scores are abnormal for their group. However, using the T-scores will also lose the uncorrected information about parent gender and age that is present in the raw scores, which could matter even more.

One way to preserve as much information as possible may be to use the raw scores but also include demographic variables of the primary parent (age, gender, adoptive status) into the subtyping. I will proceed with raw scores for now and add in a subsequent section on primary parent demographics.


### Family function

Family function information is taken from the data files "ABCD Youth Family Environment Scale-Family Conflict Subscale Modified from PhenX (FES)" (`abcd_fes01.txt`; parenting category; release 4.0) and "ABCD Parent Family Environment Scale-Family Conflict Subscale Modified from PhenX (FES)" (`fes02.txt`; parenting category; release 4.0).


### Prosocial behaviour

Prosocial behaviour information was originally planned to be collected from the "Strengths and Difficulties Questionnaire", but the questionnaire only contained responses from around 3000 subjects. Instead, information is collected from the "Youth Prosocial Behavior Survey" (`abcd_psb01.txt`; behavior category; release 4.0) and the "Parent Prosocial Behavior Survey" (`psb01.txt`; behavior category; release 4.0), which ask three questions:

1. Is the child nice to other people and do they care about their feelings
2. Is the child helpful if someone is hurt, upset, or feeling sick
3. Does the child often offer to help others


### Loneliness

Loneliness will be tracked by factoring in the number of close friends (`resiliency5b_y` + `resiliency6b_y`) and how many friends (`resiliency5a_y` + `resiliency6a_y`) each subject has from the ABCD Other Resilience file (`abcd_ysr01.txt`; category Social Adjustments; release 4.0).


### Healthy behaviours

Three forms of healthy behaviour are tracked: 

1. Screen time
2. Involvement in sports and activities
3. Exercise habits

Screen time information is collected from the Youth Screen Time Survey (`abcd_stq01.txt`; category Questionnaire; release 4.0) and the Parent Screen Time Survey (`stq01.txt`; category Questionnaire; release 4.0). Within the youth survey, the following variables are collected for both weekdays and weekends separately:

- hours watching TV / movies
- hours watching videos
- hours playing video games
- hours spent texting
- hours on social media
- hours spent video chatting

These variables span `screen1_wkdy_y` to `screen12_wknd_y`.

Within the parent survey, the following variables are collected for weekdays and weekends separately, as well as for reporting in minutes and hours separately:

- time spent on a computer

These variables span `screentime1_p_hours` to `screentime2_p_minutes`.

