# Pilot results


## Incorporating pilot work:
- Keep the approach of bulk data grabbing scripts as done for the pilot
- Include a new section on data preprocessing for SNF (04-preprocessing for SNF)
- convert SNF script into a pilot script that explores 2 and 3 cluster options. this will become 05-pilot-snf and make room for 06-snf-approach-1 (inputs are inputs, outputs are not included - similar to what was done for the pilot)
- remove the old branch that was specifically for 3 cluster options
- new snf scripts can be used to explore the alternative styles of subtyping (e.g., including outputs in with the subtyping)
- package development can be the next major stage: a refactoring of the code present earlier in the process (abcdwheelR)
- systematic review on the horizon!


Before polishing the full analyses for applying SNF to the ABCD study, I conducted a pilot SNF analysis which examined a subset of our planned input variables and outcome measures.
The results of those pilot analyses are shown below.

The input variables used for this pilot include:

## Input variables

### Structural brain imaging

I looked at FA and MD DTI values for white matter structures.

The dTI data are located in the files *abcd_dmdtifp101.txt* and *abcd_dmdtifp201* (titled ABCD dMRI DTI Full Part 1 and 2 respectively).
All variables follow the naming scheme 'dmdtifp1_x', where x ranges from 1 to 1185.

Across all parcellations, the options for examining white matter FA and MD are in the table below.

| Variable              | Segmentation method     | Region type               | Element name in the NDA      |
|-----------------------|-------------------------|---------------------------|------------------------------|
| Fractional anisotropy | AtlasTrack              | Major WM tracts           | dmdtifp1_1 to dmdtifp1_35    |
| Fractional anisotropy | Anatomical parcellation | Sub-adjacent white matter | dmdtifp1_331 to dmdtifp1_401  |
| Fractional anisotropy | Automated segmentation  | WM of major brain region  | dmdtifp1_211, 214, 228, 231  |
| Mean diffusivity      | AtlasTrack              | Major WM tracts           | dmdtifp1_43 to dmdtifp1_79   |
| Mean diffusivity      | Anatomical parcellation | Sub-adjacent white matter | dmdtifp1_402 to dmdtifp1_472 |
| Mean diffusivity      | Automated segmentation  | WM of major brain region  | dmdtifp1_241, 244, 258, 261  |

I specifically examined the parcellation used by Desikan et al. for this pilot, which covers dmtifp_331 to 472.

* Average fractional anisotropy (FA)
* Mean diffusivity (MD)
* Average longitudinal diffusion coefficient
* Average transverse diffusion coefficient
* Fiber tract volume
