```{r}
library(SNFtool)

# The version of group predict from the library:
groupPredict <- function (train, test, groups, K = 20, alpha = 0.5, t = 20, method = 1) 
{
    Wi <- vector("list", length = length(train))
    for (i in 1:length(train)) {
        view <- standardNormalization(rbind(train[[i]], test[[i]]))
        Dist1 <- dist2(view, view)
        Wi[[i]] <- affinityMatrix(Dist1, K, alpha)
    }
    W <- SNF(Wi, K, t)
    Y0 <- matrix(0, nrow(view), max(groups))
    for (i in 1:length(groups)) {
        Y0[i, groups[i]] <- 1
    }
    Y <- .csPrediction(W, Y0, method)
    newgroups <- rep(0, nrow(view))
    for (i in 1:nrow(Y)) {
        newgroups[i] <- which(Y[i, ] == max(Y[i, ]))
    }
    return(newgroups)
}

# The version of group predict from the github cran mirror:
groupPredict <- function(train, test, groups, K=20, alpha=0.5, t=20, method=1){
    # Predicts subtype of new patients from labeled training set of patients 
    #   using label propigation or local and global consistency.
    #
    # Args:
    #   train: List affinity matrices for samples with known labels
    #   test: List affinity matrices for samples with unknown labels.
    #       Length of test must match length of train (and order?)
    #   groups: Labels specifying the groups in train
    #   K: SNF parameter for number of neighbours in KNN step
    #   alpha: SNF Hyperparameter 
    #   t: SNF varaible - number of iterations
    #   method: 0/1 specifies method used (1) Label propagation or
    #       (0) Local & global consistency.
    #
    # Returns: 
    #   Vector of new labels assigned to the test samples 
    Wi <- vector("list", length=length(train))
    
    for (i in 1:length(train)){
        view <- standardNormalization(rbind(train[[i]],test[[i]]))
        Dist1 <- dist2(view, view)
        Wi[[i]] <- affinityMatrix(Dist1, K, alpha)
    }
    W <- SNF(Wi,K,t)
    Y0 <- matrix(0,nrow(view), max(groups))
    for (i in 1:length(groups)){
        Y0[i,groups[i]] <- 1
    }
    Y <- .csPrediction(W, Y0, method)
    newgroups <- rep(0, nrow(view))
    for (i in 1:nrow(Y)) {
        newgroups[i] <- which(Y[i,] == max(Y[i,]))
    }
    return (newgroups)
}
```

The demonstration provided in the SNF documentation

```{r}

# These files are packaged with the SNFtool source code
load("~/mnt/wheeler-lab/lab-data/snf-demo/dataL-data/dataL.RData")
source_datal <- dataL
source_labels <- label

# These data are made available when loading the SNFtool library
data(dataL)
data(label)
lib_datal <- dataL
lib_labels <- label


# The dataL structure is a list of two dataframes
# Comparison of dimensions
dim(lib_datal[[1]]) # 300 x 76
dim(lib_datal[[2]]) # 300 x 240

dim(source_datal[[1]]) # 600 x 76
dim(source_datal[[2]]) # 600 x 240


# Both labels appear to be equal parts 1, 2, and 3
source_labels
lib_labels

# Create the training and test data
# P: This corresponds to 480 or 240 training cases depending on which data used
n = floor(0.8*length(label)) # number of training cases

# P: From documentation, this randomly picks 240 integers between 1 and 300
trainSample = sample.int(length(label), n)

# P: This comment says 150 samples, but really uses 240 samples
train = lapply(dataL, function(x) x[trainSample, ]) # Use the first 150 samples for training
test = lapply(dataL, function(x) x[-trainSample, ]) # Test the rest of the data set
groups = label[trainSample]

str(dataL[[1]])

dim(train[[1]])
dim(train[[2]])

dim(test[[1]])
dim(test[[2]])

# Set the other
K = 20
alpha = 0.5
t = 20
method = TRUE

# Apply the prediction function to the data
newLabel = groupPredict(train,test,groups,K,alpha,t,method)

# Compare the prediction accuracy
accuracy = sum(label[-trainSample] == newLabel[-c(1:n)])/(length(label) - n)

accuracy

```

