# Psychosocial resilience {#sec-abcdpsych}

Information about psychosocial resilience is spread across several data files in the NDA. In this project, I use the following aspects of psychosocial resilience.


## Parent psychopathology

Information about parent psychopathology is collected from the "ABCD Parent Adult Self Report Scores Aseba (ASR)" file (`abcd_asrs01.txt`; category Questionnaire; release 4.0).

Psychometric scores in the ABCD study are often reported as raw scores and as T-scores (Z score transformed to have a mean of 50 and a standard deviation of 10). The NDA mentions that the T-scores are in relation to norms for each gender at ages 18-35 and 36-59 (for the adult self report). The age and gender of the parents can be obtained from the Parent Demographics Surveys (`abcd_lpds01.txt`; demographics category, `pdem02.txt`; demographics category). At the time of writing this, I am not completely sure about whether it is better to use the raw scores or the T-scores for subtyping.

Consider the situation that there are significant differences in the raw scores depending on the reporting parent's age group and gender. Using the T-scores will ensure that the signal provided by this information will be whether or not the parent's scores are abnormal for their group. However, using the T-scores will also lose the uncorrected information about parent gender and age that is present in the raw scores, which could matter even more.

One way to preserve as much information as possible may be to use the raw scores but also include demographic variables of the primary parent (age, gender, adoptive status) into the subtyping. I will proceed with raw scores for now and add in a subsequent section on primary parent demographics.


## Family function

Family function information is taken from the data files "ABCD Youth Family Environment Scale-Family Conflict Subscale Modified from PhenX (FES)" (`abcd_fes01.txt`; parenting category; release 4.0) and "ABCD Parent Family Environment Scale-Family Conflict Subscale Modified from PhenX (FES)" (`fes02.txt`; parenting category; release 4.0).


## Prosocial behaviour

Prosocial behaviour information was originally planned to be collected from the "Strengths and Difficulties Questionnaire", but the questionnaire only contained responses from around 3000 subjects. Instead, information is collected from the "Youth Prosocial Behavior Survey" (`abcd_psb01.txt`; behavior category; release 4.0) and the "Parent Prosocial Behavior Survey" (`psb01.txt`; behavior category; release 4.0), which ask three questions:

1. Is the child nice to other people and do they care about their feelings
2. Is the child helpful if someone is hurt, upset, or feeling sick
3. Does the child often offer to help others


## Loneliness

Loneliness will be tracked by factoring in the number of close friends (`resiliency5b_y` + `resiliency6b_y`) and how many friends (`resiliency5a_y` + `resiliency6a_y`) each subject has from the ABCD Other Resilience file (`abcd_ysr01.txt`; category Social Adjustments; release 4.0).


## Healthy behaviours

Three forms of healthy behaviour are tracked: 

1. Screen time
2. Involvement in sports and activities
3. Exercise habits

Screen time information is collected from the Youth Screen Time Survey (`abcd_stq01.txt`; category Questionnaire; release 4.0) and the Parent Screen Time Survey (`stq01.txt`; category Questionnaire; release 4.0). Within the youth survey, the following variables are collected for both weekdays and weekends separately:

- hours watching TV / movies
- hours watching videos
- hours playing video games
- hours spent texting
- hours on social media
- hours spent video chatting

These variables span `screen1_wkdy_y` to `screen12_wknd_y`.

Within the parent survey, the following variables are collected for weekdays and weekends separately, as well as for reporting in minutes and hours separately:

- time spent on a computer

These variables span `screentime1_p_hours` to `screentime2_p_minutes`.
