# Similarity network fusion

```{r eval = FALSE}
ibrary(here)
library(readr)
library(dplyr)
library(scabcd)

# Import input variables
as_mtbi_loc <- read_csv(here("data/abcd/inputs/as_mtbi_loc.csv"))
as_mtbi_mechanism <- read_csv(here("data/abcd/inputs/as_mtbi_mechanism.csv"))
as_mtbi_mem_daze <- read_csv(here("data/abcd/inputs/as_mtbi_mem_daze.csv"))
d_income <- read_csv(here("data/abcd/inputs/d_income.csv"))
d_interview_age <- read_csv(here("data/abcd/inputs/d_interview_age.csv"))
d_mtbi_age <- read_csv(here("data/abcd/inputs/d_mtbi_age.csv"))
d_pubertal_status <- read_csv(here("data/abcd/inputs/d_pubertal_status.csv"))
d_race <- read_csv(here("data/abcd/inputs/d_race_cu.csv"))
d_sex <- read_csv(here("data/abcd/inputs/d_sex.csv"))
mh_headaches <- read_csv(here("data/abcd/inputs/mh_headaches.csv"))
mh_mtbi_count <- read_csv(here("data/abcd/inputs/mh_mtbi_count.csv"))
dm_wmndf <- read_csv(here("data/abcd/inputs/dm_wmndf.csv"))
rm_gord_cor <- read_csv(here("data/abcd/inputs/rm_gord_cor.csv"))
rm_gord_var <- read_csv(here("data/abcd/inputs/rm_gord_var.csv"))
rm_subc_cor <- read_csv(here("data/abcd/inputs/rm_subc_cor.csv"))
rm_subc_var <- read_csv(here("data/abcd/inputs/rm_subc_var.csv"))
sm_cort_sa <- read_csv(here("data/abcd/inputs/sm_cort_sa.csv"))
sm_cort_t <- read_csv(here("data/abcd/inputs/sm_cort_t.csv"))
sm_subc_v <- read_csv(here("data/abcd/inputs/sm_subc_v.csv"))
p_loneliness <- read_csv(here("data/abcd/inputs/p_loneliness.csv"))
p_screen_time <- read_csv(here("data/abcd/inputs/p_screen_time.csv"))
p_family_function <- read_csv(here("data/abcd/inputs/p_family_function.csv"))
p_sports <- read_csv(here("data/abcd/inputs/p_sports.csv"))
p_prosocial <- read_csv(here("data/abcd/inputs/p_prosocial.csv"))
p_parent_psych <- read_csv(here("data/abcd/inputs/p_parent_psych.csv"))
p_exercise <- read_csv(here("data/abcd/inputs/p_exercise.csv"))


# Import outcome measures
cbcl_headaches <- read_csv(here("data/abcd/outputs/cbcl_headaches.csv"))
cbcl_nausea <- read_csv(here("data/abcd/outputs/cbcl_nausea.csv"))
cbcl_vomiting <- read_csv(here("data/abcd/outputs/cbcl_vomiting.csv"))
cbcl_dizzy <- read_csv(here("data/abcd/outputs/cbcl_dizzy.csv"))
cbcl_overtired <- read_csv(here("data/abcd/outputs/cbcl_overtired.csv"))
cbcl_sleeping_more <- read_csv(here("data/abcd/outputs/cbcl_sleeping_more.csv"))
cbcl_sleeping_less <- read_csv(here("data/abcd/outputs/cbcl_sleeping_less.csv"))
cbcl_depress_r <- read_csv(here("data/abcd/outputs/cbcl_depress_r.csv"))
cbcl_anxiety_r <- read_csv(here("data/abcd/outputs/cbcl_anxiety_r.csv"))
cbcl_attention_r <- read_csv(here("data/abcd/outputs/cbcl_attention_r.csv"))
cbcl_aggressive_r <- read_csv(here("data/abcd/outputs/cbcl_aggressive_r.csv"))
sds_sleep <- read_csv(here("data/abcd/outputs/sds_sleep_df.csv"))

# Sample for testing
as_mtbi_loc <- as_mtbi_loc[1:100, ]
as_mtbi_mechanism <- as_mtbi_mechanism[1:100, ]
as_mtbi_mem_daze <- as_mtbi_mem_daze[1:100, ]
d_income <- d_income[1:100, ]
d_interview_age <- d_interview_age[1:100, ]
d_mtbi_age <- d_mtbi_age[1:100, ]
d_pubertal_status <- d_pubertal_status[1:100, ]
d_race <- d_race[1:100, ]
d_sex <- d_sex[1:100, ]
dm_wmndf <- dm_wmndf[1:100, ]
mh_headaches <- mh_headaches[1:100, ]
mh_mtbi_count <- mh_mtbi_count[1:100, ]
rm_gord_cor <- rm_gord_cor[1:100, ]
rm_gord_var <- rm_gord_var[1:100, ]
rm_subc_cor <- rm_subc_cor[1:100, ]
rm_subc_var <- rm_subc_var[1:100, ]
sm_cort_sa <- sm_cort_sa[1:100, ]
sm_cort_t <- sm_cort_t[1:100, ]
sm_subc_v <- sm_subc_v[1:100, ]
p_loneliness <-  p_loneliness[1:100, ]
p_screen_time <-  p_screen_time[1:100, ]
p_family_function <-  p_family_function[1:100, ]
p_sports <-  p_sports[1:100, ]
p_prosocial <-  p_prosocial[1:100, ]
p_parent_psych <-  p_parent_psych[1:100, ]
p_exercise <-  p_exercise[1:100, ]


# Structure containing all input data
data_list <- generate_data_list(mtbi_loc = as_mtbi_loc,
                                mtbi_mechanism = as_mtbi_mechanism,
                                mtbi_mem_daze = as_mtbi_mem_daze,
                                income = d_income,
                                interview_age = d_interview_age,
                                mtbi_age = d_mtbi_age,
                                pubertal_status = d_pubertal_status,
                                race = d_race,
                                sex = d_sex,
                                wmndf = dm_wmndf,
                                headaches = mh_headaches,
                                mtbi_count = mh_mtbi_count,
                                gord_cor = rm_gord_cor,
                                gord_var = rm_gord_var,
                                subc_cor = rm_subc_cor,
                                subc_var = rm_subc_var,
                                cort_sa = sm_cort_sa,
                                cort_t = sm_cort_t,
                                subc_v = sm_subc_v,
                                loneliness = p_loneliness,
                                screen_time = p_screen_time,
                                family_function = p_family_function,
                                sports = p_sports,
                                prosocial = p_prosocial,
                                parent_psych = p_parent_psych,
                                exercise = p_exercise)



# Structure containing all outcome data
outcome_list <- generate_outcome_list(cbcl_headaches = cbcl_headaches,
                                      cbcl_nausea = cbcl_nausea,
                                      cbcl_vomiting = cbcl_vomiting,
                                      cbcl_dizzy = cbcl_dizzy,
                                      cbcl_overtired = cbcl_overtired,
                                      cbcl_sleeping_more = cbcl_sleeping_more,
                                      cbcl_sleeping_less = cbcl_sleeping_less,
                                      cbcl_depress_r = cbcl_depress_r,
                                      cbcl_anxiety_r = cbcl_anxiety_r,
                                      cbcl_attention_r = cbcl_attention_r,
                                      cbcl_aggressive_r = cbcl_aggressive_r,
                                      sds_sleep = sds_sleep)

set.seed(42)
design_matrix_base <- build_design_matrix_base_t()
design_matrix <- add_design_matrix_rows(design_matrix_base, 5)

# Assess clustering minimum p-value for an ordinal dependent variable
output_matrix <- execute_design_matrix(data_list, design_matrix, outcome_list)

design_matrix

colnames(output_matrix)

```


The output_matrix variable contains all the results from the SNF/meta-clustering procedure.

```{r eval = FALSE}
write_csv(output_matrix, here("data/abcd/results/raw/snf_mc_output_matrix.csv"))
```
