# Validation of Clustering Results

## Importing packages and establishing file paths

```{r}
library(readr)
library(abcdutils)
library(here)
library(metasnf)
library(progressr)
library(rlist)
library(ggplot2)
library(patchwork)

input_path <- path_maker(here(paste0("data/abcd/inputs")))
proc_path <- path_maker(here(paste0("data/abcd/results/processed")))
fig_path <- path_maker(here(paste0("data/abcd/results/figures")))
sub_path <- path_maker(here(paste0("data/abcd/subjects")))

mtbi_subjects <- read_csv(sub_path("2024_01_28_mtbi_subjects.csv"))
mtbi_train <- read_csv(sub_path("2024_01_31_mtbi_subjects_train.csv"))
mtbi_test <- read_csv(sub_path("2024_01_31_mtbi_subjects_test.csv"))

```

## Importing the top mTBI solution and held out subjects

```{r}

top_mc_b_solution <- read_csv(proc_path("2024_01_30_top_mc_b_solution.csv"))

data_list_m1 <- list.load(input_path("2024_01_28_data_list_m1.rds"))
data_list_m2 <- list.load(input_path("2024_01_28_data_list_m2.rds"))
data_list_m3 <- list.load(input_path("2024_01_28_data_list_m3.rds"))
data_list_m4 <- list.load(input_path("2024_01_28_data_list_m4.rds"))
data_list_m5 <- list.load(input_path("2024_01_28_data_list_m5.rds"))
oom_list_m1 <- list.load(input_path("2024_01_28_oom_list_m1.rds"))
oom_list_m2 <- list.load(input_path("2024_01_28_oom_list_m2.rds"))
oom_list_m3 <- list.load(input_path("2024_01_28_oom_list_m3.rds"))
oom_list_m4 <- list.load(input_path("2024_01_28_oom_list_m4.rds"))
oom_list_m5 <- list.load(input_path("2024_01_28_oom_list_m5.rds"))

full_data_list_m1 <- list.load(input_path("2024_01_31_full_data_list_m1.rds"))
full_data_list_m2 <- list.load(input_path("2024_01_31_full_data_list_m2.rds"))
full_data_list_m3 <- list.load(input_path("2024_01_31_full_data_list_m3.rds"))
full_data_list_m4 <- list.load(input_path("2024_01_31_full_data_list_m4.rds"))
full_data_list_m5 <- list.load(input_path("2024_01_31_full_data_list_m5.rds"))
full_oom_list_m1 <- list.load(input_path("2024_01_31_full_oom_list_m1.rds"))
full_oom_list_m2 <- list.load(input_path("2024_01_31_full_oom_list_m2.rds"))
full_oom_list_m3 <- list.load(input_path("2024_01_31_full_oom_list_m3.rds"))
full_oom_list_m4 <- list.load(input_path("2024_01_31_full_oom_list_m4.rds"))
full_oom_list_m5 <- list.load(input_path("2024_01_31_full_oom_list_m5.rds"))

```

## Label propagation

Here, I check to see if the key inferences observed in the top mTBI cluster still persist when propagated to a held out subset of patients.

```{r}
my_distance_metrics <- generate_distance_metrics_list(
    continuous_distances = list(
        "standard_norm_euclidean" = sn_euclidean_distance
    ),
    discrete_distances = list(
        "standard_norm_euclidean" = sn_euclidean_distance
    ),
    ordinal_distances = list(
        "standard_norm_euclidean" = sn_euclidean_distance
    ),
)

set.seed(42)
propagated_labels <- lp_solutions_matrix(
    top_mc_b_solution,
    full_data_list_m1,
    distance_metrics_list = my_distance_metrics
)

write_csv(propagated_labels, proc_path("top_mc_b_propagated_labels.csv", TRUE))

propagated_labels <- read_csv(
    proc_path("2024_01_31_top_mc_b_propagated_labels.csv")
)

```

## Plots of associations for label propagation solution

```{r}

test_data_list_m1 <- list.load(input_path("2024_01_31_test_data_list_m1.rds"))
test_oom_list_m1 <- list.load(input_path("2024_01_31_test_oom_list_m1.rds"))

test_results <- propagated_labels |>
    dplyr::filter(group == "test") |>
    dplyr::select(-group)
colnames(test_results) <- c("subjectkey", "cluster")

test_results

lp_plots <- characterize_solution(
    cluster_df = test_results,
    data_list = c(test_data_list_m1, test_oom_list_m1),
    plotname = "label_prop"
)

save_plot_list(lp_plots, "lp_mtbi_mc_b")

lp_data <- characterize_solution(
    cluster_df = test_results,
    data_list = c(test_data_list_m1, test_oom_list_m1),
    plotname = "label_prop",
    return_plots = FALSE
)

mock_test_solution <- tidyr::spread(
    test_results,
    key = subjectkey,
    value = cluster
)

# New Label propagated
lp_input_characterization <- extend_solutions(
    mock_test_solution,
    c(test_data_list_m1, test_oom_list_m1)
)
lp_input_characterization$"row_id" <- top_mc_b_solution$"row_id"
lp_input_pvals <- p_val_select(lp_input_characterization)
lp_input_pvals$"mc_label" <- "mTBI test"
lp_input_pvals <- lp_input_pvals |>
    dplyr::select(
        -dplyr::contains("mtbi")
    )
test_oom_list_m1 <- test_oom_list_m1 |>
    lapply(
        function(x) {
            if (x$"domain" == "B") {
                x$"domain" <- "!B"
            }
            if (x$"domain" == "S") {
                x$"domain" <- "!S"
            }
            return(x)
        }
    )

# Original mTBI
top_mc_b_solution <- read_csv(proc_path("2024_01_30_top_mc_b_solution.csv"))
top_mc_b_characterization <- extend_solutions(
    top_mc_b_solution,
    c(data_list_m1, oom_list_m1)
)
top_mc_b_characterization$"row_id" <- top_mc_b_solution$"row_id"
top_mc_b_pvals <- p_val_select(top_mc_b_characterization)
top_mc_b_pvals$"mc_label" <- "mTBI train"
top_mc_b_pvals <- top_mc_b_pvals |>
    dplyr::select(
        -dplyr::starts_with("mean"),
        -dplyr::contains("mtbi")
    )
oom_list_m1 <- oom_list_m1 |>
    lapply(
        function(x) {
            if (x$"domain" == "B") {
                x$"domain" <- "!B"
            }
            if (x$"domain" == "S") {
                x$"domain" <- "!S"
            }
            return(x)
        }
    )

# Outcome matched uninjured
top_cmu_3c_solution <- read_csv(proc_path("2024_02_01_top_cmu_3c_solution"))
data_list_cmu3 <- list.load(input_path("2024_01_29_data_list_cmu3.rds"))
oom_list_cmu3 <- list.load(input_path("2024_01_29_oom_list_cmu3.rds"))
top_cmu_3c_characterization <- extend_solutions(
    top_cmu_3c_solution,
    c(data_list_cmu3) # it already has the cbcl/sds pvalues
)
top_cmu_3c_characterization$"row_id" <- top_cmu_3c_solution$"row_id"
top_cmu_3c_pvals <- p_val_select(top_cmu_3c_characterization)
top_cmu_3c_pvals$"mc_label" <- "Demo/CBCL/SDS Matched"
top_cmu_3c_pvals <- top_cmu_3c_pvals |>
    dplyr::select(-dplyr::starts_with("mean"))
# Rename the CBCL domains to put them last
oom_list_cmu3 <- oom_list_cmu3 |>
    lapply(
        function(x) {
            if (x$"domain" == "B") {
                x$"domain" <- "!B"
            }
            if (x$"domain" == "S") {
                x$"domain" <- "!S"
            }
            return(x)
        }
    )

mtbi_contrast_associations <- manhattan_plot(
    top_mc_b_pvals,
    threshold = 0.05,
    bonferroni_line = FALSE,
    data_list = c(data_list_m1, oom_list_m1)
)
mtbi_contrast_associations

cmu_contrast_associations <- manhattan_plot(
    top_cmu_3c_pvals,
    threshold = 0.05,
    bonferroni_line = FALSE,
    data_list = c(data_list_cmu3, oom_list_cmu3)
)
cmu_contrast_associations

lp_contrast_associations <- manhattan_plot(
    lp_input_pvals,
    threshold = 0.05,
    bonferroni_line = FALSE,
    data_list = c(test_data_list_m1, test_oom_list_m1)
)
lp_contrast_associations

significance_vector <- function(p_val_df) {
    p_vals <- p_val_df |>
        dplyr::select(dplyr::ends_with("_p"))
    print(p_vals)
    sig_vec <- p_vals[1, ] > 0.05 |>
        unlist() |>
        as.vector() |>
        as.numeric()
    sig_vec <- ifelse(sig_vec, "black", "red")
    return(sig_vec)
}

mtbi_colours <- significance_vector(top_mc_b_pvals)
cmu_colours <- significance_vector(top_cmu_3c_pvals)
lp_colours <- significance_vector(lp_input_pvals)

colour_text <- function(associations, sig_vec) {
    order <- paste0(associations$"data"$"variable", "_p")
    sig_vec <- sig_vec[, order]
    associations <- associations +
        ggplot2::theme(
            axis.text.x = ggplot2::element_text(
                colour = sig_vec
            )
        )
    return(associations)
}

full_plot <-
    colour_text(cmu_contrast_associations, cmu_colours) /
    colour_text(mtbi_contrast_associations, mtbi_colours) /
    colour_text(lp_contrast_associations, lp_colours)

full_plot

ggsave(
    plot = full_plot,
    fig_path("full_contrast_associations.png", TRUE),
    height = 15
)

```
