## Siblings analysis

We choose not to eliminate siblings during the early stage of the analysis.
Within our concussion sample of size N = 437, as well as in randomly subsetted uninjured samples, the number of within group siblings that pose a threat to artificially inflating a cluster is typically no more than 2-4.
Removing siblings randomly across all observations would lead to a large loss of data.
Removing siblings on a per-group basis would disproportionately impact the uninjured group, as the mTBI group has a much lower number of siblings.

```{r}
mtbi_subs <- abcdutils::read_subjects(sub_path("2025_05_22_mtbi_subs.csv"))
unij_subs <- abcdutils::read_subjects(sub_path("2025_05_22_unij_subs.csv"))

all_subs_df <- data.frame(
    subjectkey = c(mtbi_subs, unij_subs),
    group = c(rep("mtbi", length(mtbi_subs)), rep("unij", length(unij_subs)))
) 

nrow(all_subs_df) # 9786 subjects

family_data <- read_csv(core_path("abcd-general/abcd_y_lt.csv")) |>
    filter_timepoint(t = 0) |>
    dplyr::inner_join(all_subs_df, by = c("src_subject_id" = "subjectkey"))

siblings_df <- family_data$"rel_family_id" |>
    table() |>
    data.frame() |>
    dplyr::rename("rel_family_id" = "Var1")
siblings_df$"rel_family_id" <- as.numeric(as.character(siblings_df$"rel_family_id"))

examining_sibs_df <- dplyr::full_join(family_data, siblings_df, by = "rel_family_id")

# 118/437 kids in the mTBI group have a sibling (27%)
examining_sibs_df |>
    dplyr::filter(group == "mtbi", Freq > 1)

# 2873/9339 kids in the uninjured group have a sibling (31%)
examining_sibs_df |>
    dplyr::filter(group == "unij", Freq > 1)

# Very few kids in a matched random sample of N = 437 have siblings
z <- examining_sibs_df |>
    dplyr::filter(group == "unij")
z[sample(nrow(z))[1:437], ]$"rel_family_id" |>
    unique() |>
    length()

# within concussion sample siblings: 434/437 unique family IDs (99.3%)
examining_sibs_df |>
    dplyr::filter(group == "mtbi") |>
    dplyr::select(rel_family_id) |>
    unlist() |>
    unique() |>
    length()

# within concussion sample siblings: 7944/9349 unique family IDs (85.0%)
examining_sibs_df |>
    dplyr::filter(group == "unij") |>
    dplyr::select(rel_family_id) |>
    unlist() |>
    unique() |>
    length()

# Randomly dropping leads to mTBI group of typically ~380 (dropping nearly 50+ observations)
shuffle_and_drop_siblings <- function(df) {
    df <- df[sample(nrow(df)), ] 
    #df <- arrange(df, desc(group))
    df <- df[!duplicated(df$"rel_family_id"), ]
    return(df)
}
shuffle_and_drop_siblings(family_data)$"group" |> table()
```

Getting rid of siblings randomly will lose a large amount of the concussion sample.
57/437 concussion sample children have at least one sibling, but the majority of those siblings are in the uninjured group (434/437 unique family IDs when looking exclusively in the mTBI sample).
Getting rid of siblings in a within groups fashion will change the percentage of children in the uninjured group who have a sibling and perhaps make the two groups less representative of each other.
An alternative option may be to simply drop siblings immediately prior to clustering (but after matching) to keep things simple.
