## Replication in demographic-corrected data

```{r}
library(readr)
library(abcdutils)
library(here)
library(metasnf)
library(progressr)
library(rlist)

input_path <- path_maker(here(paste0("data/abcd/inputs")))
proc_path <- path_maker(here(paste0("data/abcd/results/processed")))
fig_path <- path_maker(here(paste0("data/abcd/results/figures")))
sub_path <- path_maker(here(paste0("data/abcd/subjects")))

mtbi_subjects <- read_csv(sub_path("2024_03_12_mtbi_subjects.csv"))
uninjured_subjects <- read_csv(sub_path("2024_03_12_uninjured_subjects.csv"))
mtbi_subjects_train <- read_csv(sub_path("2024_03_12_mtbi_train_subjects.csv"))

source("abcd/functions.R")
```

```{r}
data_list_m1 <- list.load(input_path("2024_03_12_data_list_m1.rds"))
data_list_m1 <- list.load(input_path("2024_03_12_data_list_m1.rds"))
data_list_m2 <- list.load(input_path("2024_03_12_data_list_m2.rds"))
data_list_m3 <- list.load(input_path("2024_03_12_data_list_m3.rds"))
data_list_m4 <- list.load(input_path("2024_03_12_data_list_m4.rds"))
data_list_m5 <- list.load(input_path("2024_03_12_data_list_m5.rds"))
data_list_pm1 <- list.load(input_path("2024_03_12_data_list_pm1.rds"))
data_list_pm2 <- list.load(input_path("2024_03_12_data_list_pm2.rds"))
data_list_pm3 <- list.load(input_path("2024_03_12_data_list_pm3.rds"))
data_list_pm4 <- list.load(input_path("2024_03_12_data_list_pm4.rds"))
data_list_pm5 <- list.load(input_path("2024_03_12_data_list_pm5.rds"))

oom_list_m1 <- list.load(input_path("2024_03_17_oom_list_m1.rds"))
oom_list_m2 <- list.load(input_path("2024_03_17_oom_list_m2.rds"))
oom_list_m3 <- list.load(input_path("2024_03_17_oom_list_m3.rds"))
oom_list_m4 <- list.load(input_path("2024_03_17_oom_list_m4.rds"))
oom_list_m5 <- list.load(input_path("2024_03_17_oom_list_m5.rds"))
oom_list_pm1 <- list.load(input_path("2024_03_17_oom_list_pm1.rds"))
oom_list_pm2 <- list.load(input_path("2024_03_17_oom_list_pm2.rds"))
oom_list_pm3 <- list.load(input_path("2024_03_17_oom_list_pm3.rds"))
oom_list_pm4 <- list.load(input_path("2024_03_17_oom_list_pm4.rds"))
oom_list_pm5 <- list.load(input_path("2024_03_17_oom_list_pm5.rds"))
```

```{r}

demo <- c("d_age", "d_sex", "d_income", "d_race")

# demo_lists just contain the demographic variables
demo_list_m1 <- data_list_m1[summarize_dl(data_list_m1)$"name" %in% demo]
demo_list_m2 <- data_list_m2[summarize_dl(data_list_m2)$"name" %in% demo]
demo_list_m3 <- data_list_m3[summarize_dl(data_list_m3)$"name" %in% demo]
demo_list_m4 <- data_list_m4[summarize_dl(data_list_m4)$"name" %in% demo]
demo_list_m5 <- data_list_m5[summarize_dl(data_list_m5)$"name" %in% demo]
demo_list_pm1 <- data_list_pm1[summarize_dl(data_list_pm1)$"name" %in% demo]
demo_list_pm2 <- data_list_pm2[summarize_dl(data_list_pm2)$"name" %in% demo]
demo_list_pm3 <- data_list_pm3[summarize_dl(data_list_pm3)$"name" %in% demo]
demo_list_pm4 <- data_list_pm4[summarize_dl(data_list_pm4)$"name" %in% demo]
demo_list_pm5 <- data_list_pm5[summarize_dl(data_list_pm5)$"name" %in% demo]

# create copies of the data_lists
data_list_nd_m1 <- data_list_m1
data_list_nd_m2 <- data_list_m2
data_list_nd_m3 <- data_list_m3
data_list_nd_m4 <- data_list_m4
data_list_nd_m5 <- data_list_m5
data_list_nd_pm1 <- data_list_pm1
data_list_nd_pm2 <- data_list_pm2
data_list_nd_pm3 <- data_list_pm3
data_list_nd_pm4 <- data_list_pm4
data_list_nd_pm5 <- data_list_pm5
oom_list_nd_m1 <- oom_list_m1
oom_list_nd_m2 <- oom_list_m2
oom_list_nd_m3 <- oom_list_m3
oom_list_nd_m4 <- oom_list_m4
oom_list_nd_m5 <- oom_list_m5
oom_list_nd_pm1 <- oom_list_pm1
oom_list_nd_pm2 <- oom_list_pm2
oom_list_nd_pm3 <- oom_list_pm3
oom_list_nd_pm4 <- oom_list_pm4
oom_list_nd_pm5 <- oom_list_pm5

# Removing the demographic variables from the copies of the data lists
data_list_nd_m1[summarize_dl(data_list_nd_m1)$"name" %in% demo] <- NULL
data_list_nd_m2[summarize_dl(data_list_nd_m2)$"name" %in% demo] <- NULL
data_list_nd_m3[summarize_dl(data_list_nd_m3)$"name" %in% demo] <- NULL
data_list_nd_m4[summarize_dl(data_list_nd_m4)$"name" %in% demo] <- NULL
data_list_nd_m5[summarize_dl(data_list_nd_m5)$"name" %in% demo] <- NULL
data_list_nd_pm1[summarize_dl(data_list_nd_pm1)$"name" %in% demo] <- NULL
data_list_nd_pm2[summarize_dl(data_list_nd_pm2)$"name" %in% demo] <- NULL
data_list_nd_pm3[summarize_dl(data_list_nd_pm3)$"name" %in% demo] <- NULL
data_list_nd_pm4[summarize_dl(data_list_nd_pm4)$"name" %in% demo] <- NULL
data_list_nd_pm5[summarize_dl(data_list_nd_pm5)$"name" %in% demo] <- NULL

# Doing the linear regression
data_list_nd_m1 <- linear_adjust(data_list_nd_m1, demo_list_m1, sig_digs = 3)
data_list_nd_m2 <- linear_adjust(data_list_nd_m2, demo_list_m2, sig_digs = 3)
data_list_nd_m3 <- linear_adjust(data_list_nd_m3, demo_list_m3, sig_digs = 3)
data_list_nd_m4 <- linear_adjust(data_list_nd_m4, demo_list_m4, sig_digs = 3)
data_list_nd_m5 <- linear_adjust(data_list_nd_m5, demo_list_m5, sig_digs = 3)
data_list_nd_pm1 <- linear_adjust(data_list_nd_pm1, demo_list_pm1, sig_digs = 3)
data_list_nd_pm2 <- linear_adjust(data_list_nd_pm2, demo_list_pm2, sig_digs = 3)
data_list_nd_pm3 <- linear_adjust(data_list_nd_pm3, demo_list_pm3, sig_digs = 3)
data_list_nd_pm4 <- linear_adjust(data_list_nd_pm4, demo_list_pm4, sig_digs = 3)
data_list_nd_pm5 <- linear_adjust(data_list_nd_pm5, demo_list_pm5, sig_digs = 3)
oom_list_nd_m1 <- linear_adjust(oom_list_nd_m1, demo_list_m1, sig_digs = 3)
oom_list_nd_m2 <- linear_adjust(oom_list_nd_m2, demo_list_m2, sig_digs = 3)
oom_list_nd_m3 <- linear_adjust(oom_list_nd_m3, demo_list_m3, sig_digs = 3)
oom_list_nd_m4 <- linear_adjust(oom_list_nd_m4, demo_list_m4, sig_digs = 3)
oom_list_nd_m5 <- linear_adjust(oom_list_nd_m5, demo_list_m5, sig_digs = 3)
oom_list_nd_pm1 <- linear_adjust(oom_list_nd_pm1, demo_list_pm1, sig_digs = 3)
oom_list_nd_pm2 <- linear_adjust(oom_list_nd_pm2, demo_list_pm2, sig_digs = 3)
oom_list_nd_pm3 <- linear_adjust(oom_list_nd_pm3, demo_list_pm3, sig_digs = 3)
oom_list_nd_pm4 <- linear_adjust(oom_list_nd_pm4, demo_list_pm4, sig_digs = 3)
oom_list_nd_pm5 <- linear_adjust(oom_list_nd_pm5, demo_list_pm5, sig_digs = 3)

# Adding back the demographic variables post-correction
data_list_rd_m1 <- c(data_list_nd_m1, demo_list_m1)
data_list_rd_m2 <- c(data_list_nd_m2, demo_list_m2)
data_list_rd_m3 <- c(data_list_nd_m3, demo_list_m3)
data_list_rd_m4 <- c(data_list_nd_m4, demo_list_m4)
data_list_rd_m5 <- c(data_list_nd_m5, demo_list_m5)
data_list_rd_pm1 <- c(data_list_nd_pm1, demo_list_pm1)
data_list_rd_pm2 <- c(data_list_nd_pm2, demo_list_pm2)
data_list_rd_pm3 <- c(data_list_nd_pm3, demo_list_pm3)
data_list_rd_pm4 <- c(data_list_nd_pm4, demo_list_pm4)
data_list_rd_pm5 <- c(data_list_nd_pm5, demo_list_pm5)

list.save(data_list_nd_m1, input_path("data_list_nd_m1.rds", TRUE))
list.save(data_list_nd_m2, input_path("data_list_nd_m2.rds", TRUE))
list.save(data_list_nd_m3, input_path("data_list_nd_m3.rds", TRUE))
list.save(data_list_nd_m4, input_path("data_list_nd_m4.rds", TRUE))
list.save(data_list_nd_m5, input_path("data_list_nd_m5.rds", TRUE))
list.save(data_list_nd_pm1, input_path("data_list_nd_pm1.rds", TRUE))
list.save(data_list_nd_pm2, input_path("data_list_nd_pm2.rds", TRUE))
list.save(data_list_nd_pm3, input_path("data_list_nd_pm3.rds", TRUE))
list.save(data_list_nd_pm4, input_path("data_list_nd_pm4.rds", TRUE))
list.save(data_list_nd_pm5, input_path("data_list_nd_pm5.rds", TRUE))

list.save(data_list_rd_m1, input_path("data_list_rd_m1.rds", TRUE))
list.save(data_list_rd_m2, input_path("data_list_rd_m2.rds", TRUE))
list.save(data_list_rd_m3, input_path("data_list_rd_m3.rds", TRUE))
list.save(data_list_rd_m4, input_path("data_list_rd_m4.rds", TRUE))
list.save(data_list_rd_m5, input_path("data_list_rd_m5.rds", TRUE))
list.save(data_list_rd_pm1, input_path("data_list_rd_pm1.rds", TRUE))
list.save(data_list_rd_pm2, input_path("data_list_rd_pm2.rds", TRUE))
list.save(data_list_rd_pm3, input_path("data_list_rd_pm3.rds", TRUE))
list.save(data_list_rd_pm4, input_path("data_list_rd_pm4.rds", TRUE))
list.save(data_list_rd_pm5, input_path("data_list_rd_pm5.rds", TRUE))

list.save(oom_list_nd_m1, input_path("oom_list_nd_m1.rds", TRUE))
list.save(oom_list_nd_m2, input_path("oom_list_nd_m2.rds", TRUE))
list.save(oom_list_nd_m3, input_path("oom_list_nd_m3.rds", TRUE))
list.save(oom_list_nd_m4, input_path("oom_list_nd_m4.rds", TRUE))
list.save(oom_list_nd_m5, input_path("oom_list_nd_m5.rds", TRUE))
list.save(oom_list_nd_pm1, input_path("oom_list_nd_pm1.rds", TRUE))
list.save(oom_list_nd_pm2, input_path("oom_list_nd_pm2.rds", TRUE))
list.save(oom_list_nd_pm3, input_path("oom_list_nd_pm3.rds", TRUE))
list.save(oom_list_nd_pm4, input_path("oom_list_nd_pm4.rds", TRUE))
list.save(oom_list_nd_pm5, input_path("oom_list_nd_pm5.rds", TRUE))
```

```{r}
data_list_nd_m1 <- list.load(input_path("2024_03_15_data_list_nd_m1.rds"))
data_list_nd_m2 <- list.load(input_path("2024_03_15_data_list_nd_m2.rds"))
data_list_nd_m3 <- list.load(input_path("2024_03_15_data_list_nd_m3.rds"))
data_list_nd_m4 <- list.load(input_path("2024_03_15_data_list_nd_m4.rds"))
data_list_nd_m5 <- list.load(input_path("2024_03_15_data_list_nd_m5.rds"))
data_list_nd_pm1 <- list.load(input_path("2024_03_15_data_list_nd_pm1.rds"))
data_list_nd_pm2 <- list.load(input_path("2024_03_15_data_list_nd_pm2.rds"))
data_list_nd_pm3 <- list.load(input_path("2024_03_15_data_list_nd_pm3.rds"))
data_list_nd_pm4 <- list.load(input_path("2024_03_15_data_list_nd_pm4.rds"))
data_list_nd_pm5 <- list.load(input_path("2024_03_15_data_list_nd_pm5.rds"))

data_list_rd_m1 <- list.load(input_path("2024_03_15_data_list_rd_m1.rds"))
data_list_rd_m2 <- list.load(input_path("2024_03_15_data_list_rd_m2.rds"))
data_list_rd_m3 <- list.load(input_path("2024_03_15_data_list_rd_m3.rds"))
data_list_rd_m4 <- list.load(input_path("2024_03_15_data_list_rd_m4.rds"))
data_list_rd_m5 <- list.load(input_path("2024_03_15_data_list_rd_m5.rds"))
data_list_rd_pm1 <- list.load(input_path("2024_03_15_data_list_rd_pm1.rds"))
data_list_rd_pm2 <- list.load(input_path("2024_03_15_data_list_rd_pm2.rds"))
data_list_rd_pm3 <- list.load(input_path("2024_03_15_data_list_rd_pm3.rds"))
data_list_rd_pm4 <- list.load(input_path("2024_03_15_data_list_rd_pm4.rds"))
data_list_rd_pm5 <- list.load(input_path("2024_03_15_data_list_rd_pm5.rds"))

oom_list_nd_m1 <- list.load(input_path("2024_03_17_oom_list_nd_m1.rds"))
oom_list_nd_m2 <- list.load(input_path("2024_03_17_oom_list_nd_m2.rds"))
oom_list_nd_m3 <- list.load(input_path("2024_03_17_oom_list_nd_m3.rds"))
oom_list_nd_m4 <- list.load(input_path("2024_03_17_oom_list_nd_m4.rds"))
oom_list_nd_m5 <- list.load(input_path("2024_03_17_oom_list_nd_m5.rds"))
oom_list_nd_pm1 <- list.load(input_path("2024_03_17_oom_list_nd_pm1.rds"))
oom_list_nd_pm2 <- list.load(input_path("2024_03_17_oom_list_nd_pm2.rds"))
oom_list_nd_pm3 <- list.load(input_path("2024_03_17_oom_list_nd_pm3.rds"))
oom_list_nd_pm4 <- list.load(input_path("2024_03_17_oom_list_nd_pm4.rds"))
oom_list_nd_pm5 <- list.load(input_path("2024_03_17_oom_list_nd_pm5.rds"))
```

Take a look to see if we have any non-linearities

```{r}
corrected_features <- data_list_nd_m1 |>
    collapse_dl() |>
    colnames()

demo_features <- demo_list_m1 |>
    collapse_dl() |>
    colnames()

# remove subjectkey
corrected_features <- corrected_features[-1]
demo_features <- demo_features[-1]

for (i in seq_along(demo_features)) {
    plot_list <- list()
    for (j in seq_along(corrected_features)) {
        print(demo_features[i])
        print(corrected_features[j])
        plot <- dl_scatter(
            data_list_rd_m1,
            demo_features[i],
            corrected_features[j]
        )
        plot_list[[length(plot_list) + 1]] <- plot
    }
    all_plots <- wrap_plots(plot_list)
    ggsave(
        plot = all_plots,
        filename = fig_path(
            paste0("corrected_", demo_features[i], ".png"),
            TRUE
        ),
        width = 20,
        height = 15
    )
}

```

Based on the resuling plots, here are the variables that seem best adjusted relative to each demographic factor:

```{r}

age_compatible <- c(
    "mtbi_age",
    "pubertal_status",
    "headache_history",
    "brain_volume",
    "cortical_thickness",
    "cortical_sa",
    "major_wm_ndi",
    "pericortical_wm_ndi",
    "fmri_cort_cors",
    "fmri_cort_subcort_cors",
    "opp_sex_friend",
    "same_sex_close_friend",
    "opp_sex_close_friend",
    "weekend_screentime",
    "weekday_screentime",
    "school_programs",
    "non_school_programs",
    "private_instruction",
    "programs_this_year",
    "exercise_time",
    "helpful",
    "family_fight",
    "family_temper",
    "family_criticize",
    "family_hit",
    "family_yell",
    "parent_perstr",
    "parent_anxdep",
    "parent_withdrawn",
    "parent_somatic",
    "parent_thought",
    "parent_attention",
    "parent_aggressive",
    "parent_intrusive",
    "parent_depress",
    "parent_anxdisord",
    "parent_avoidant",
    "parent_antisocial",
    "parent_hyperactive"
)
income_compatible <- c(
    "mtbi_mem_daze",
    "mtbi_age",
    "pubertal_status",
    "brain_volume",
    "cortical_thickness",
    "cortical_sa",
    "major_wm_ndi",
    "pericortical_wm_ndi",
    "fmri_cort_cors",
    "fmri_cort_subcort_cors",
    "exercise_time",
    "family_yell"
)
race_compatible <- c(
    "pubertal_status",
    "brain_volume",
    "cortical_thickness",
    "cortical_sa",
    "major_wm_ndi",
    "pericortical_wm_ndi",
    "fmri_cort_cors",
    "fmri_cort_subcort_cors",
    "same_sex_friend",
    "same_sex_close_friend",
    "exercise_time"
)
sex_compatible <- c(
    "brain_volume",
    "cortical_thickness",
    "cortical_sa",
    "major_wm_ndi",
    "pericortical_wm_ndi",
    "fmri_cort_cors",
    "fmri_cort_subcort_cors",
    "same_sex_close_friend",
    "weekday_screentime",
    "non_school_programs",
    "programs_this_year",
    "exercise_time",
    "family_criticize",
    "family_outdo",
    "parent_perstr",
    "parent_somatic",
    "parent_attention",
    "parent_aggressive",
    "parent_avoidant",
    "parent_hyperactive"
)

compat_vecs <- list(
    age_compatible,
    income_compatible,
    race_compatible,
    sex_compatible
)

# Features to include for the corrected clustering
include <- Reduce(intersect, compat_vecs)

include
# brain_volume, cortical_thickness, cortical_sa, major_wm_ndi,
# pericortical_wm_ndi, fmri_cort_cors, fmri_cort_subcort_cors, exercise_time

```

```{r}
# No demographics / restricted
data_list_ndr_m1 <- dl_feature_restrict(data_list_nd_m1, include)
data_list_ndr_m2 <- dl_feature_restrict(data_list_nd_m2, include)
data_list_ndr_m3 <- dl_feature_restrict(data_list_nd_m3, include)
data_list_ndr_m4 <- dl_feature_restrict(data_list_nd_m4, include)
data_list_ndr_m5 <- dl_feature_restrict(data_list_nd_m5, include)
data_list_ndr_pm1 <- dl_feature_restrict(data_list_nd_pm1, include)
data_list_ndr_pm2 <- dl_feature_restrict(data_list_nd_pm2, include)
data_list_ndr_pm3 <- dl_feature_restrict(data_list_nd_pm3, include)
data_list_ndr_pm4 <- dl_feature_restrict(data_list_nd_pm4, include)
data_list_ndr_pm5 <- dl_feature_restrict(data_list_nd_pm5, include)

list.save(data_list_ndr_m1, input_path("data_list_ndr_m1.rds", TRUE))
list.save(data_list_ndr_m2, input_path("data_list_ndr_m2.rds", TRUE))
list.save(data_list_ndr_m3, input_path("data_list_ndr_m3.rds", TRUE))
list.save(data_list_ndr_m4, input_path("data_list_ndr_m4.rds", TRUE))
list.save(data_list_ndr_m5, input_path("data_list_ndr_m5.rds", TRUE))
list.save(data_list_ndr_pm1, input_path("data_list_ndr_pm1.rds", TRUE))
list.save(data_list_ndr_pm2, input_path("data_list_ndr_pm2.rds", TRUE))
list.save(data_list_ndr_pm3, input_path("data_list_ndr_pm3.rds", TRUE))
list.save(data_list_ndr_pm4, input_path("data_list_ndr_pm4.rds", TRUE))
list.save(data_list_ndr_pm5, input_path("data_list_ndr_pm5.rds", TRUE))

data_list_ndr_m1 <- list.load(input_path("2024_03_15_data_list_ndr_m1.rds"))
data_list_ndr_m2 <- list.load(input_path("2024_03_15_data_list_ndr_m2.rds"))
data_list_ndr_m3 <- list.load(input_path("2024_03_15_data_list_ndr_m3.rds"))
data_list_ndr_m4 <- list.load(input_path("2024_03_15_data_list_ndr_m4.rds"))
data_list_ndr_m5 <- list.load(input_path("2024_03_15_data_list_ndr_m5.rds"))
data_list_ndr_pm1 <- list.load(input_path("2024_03_15_data_list_ndr_pm1.rds"))
data_list_ndr_pm2 <- list.load(input_path("2024_03_15_data_list_ndr_pm2.rds"))
data_list_ndr_pm3 <- list.load(input_path("2024_03_15_data_list_ndr_pm3.rds"))
data_list_ndr_pm4 <- list.load(input_path("2024_03_15_data_list_ndr_pm4.rds"))
data_list_ndr_pm5 <- list.load(input_path("2024_03_15_data_list_ndr_pm5.rds"))
```

```{r}
ndr_settings_matrix <- generate_settings_matrix(
    data_list_ndr_m1,
    nrow = 200,
    seed = 42,
    distance_metrics_list = my_distance_metrics
)

write_csv(ndr_settings_matrix, proc_path("ndr_settings_matrix.csv", TRUE))

ndr_settings_matrix <- read_csv(
    proc_path("2024_03_15_ndr_settings_matrix.csv")
)
```

```{r}
# Imputation 1
start <- proc.time()
progressr::with_progress({
    solutions_matrix_ndr_m1 <- batch_snf(
        data_list = data_list_ndr_m1,
        settings_matrix = ndr_settings_matrix,
        distance_metrics_list = my_distance_metrics,
        processes = "max"
    )
})
proc.time() - start
write_csv(
    solutions_matrix_ndr_m1,
    proc_path("solutions_matrix_ndr_m1.csv", TRUE)
)
# Imputation 2
start <- proc.time()
progressr::with_progress({
    solutions_matrix_ndr_m2 <- batch_snf(
        data_list = data_list_ndr_m2,
        settings_matrix = ndr_settings_matrix,
        distance_metrics_list = my_distance_metrics,
        processes = "max"
    )
})
proc.time() - start
write_csv(
    solutions_matrix_ndr_m2,
    proc_path("solutions_matrix_ndr_m2.csv", TRUE)
)
# Imputation 3
start <- proc.time()
progressr::with_progress({
    solutions_matrix_ndr_m3 <- batch_snf(
        data_list = data_list_ndr_m3,
        settings_matrix = ndr_settings_matrix,
        distance_metrics_list = my_distance_metrics,
        processes = "max"
    )
})
proc.time() - start
write_csv(
    solutions_matrix_ndr_m3,
    proc_path("solutions_matrix_ndr_m3.csv", TRUE)
)
# Imputation 4
start <- proc.time()
progressr::with_progress({
    solutions_matrix_ndr_m4 <- batch_snf(
        data_list = data_list_ndr_m4,
        settings_matrix = ndr_settings_matrix,
        distance_metrics_list = my_distance_metrics,
        processes = "max"
    )
})
proc.time() - start
write_csv(
    solutions_matrix_ndr_m4,
    proc_path("solutions_matrix_ndr_m4.csv", TRUE)
)
# Imputation 5
start <- proc.time()
progressr::with_progress({
    solutions_matrix_ndr_m5 <- batch_snf(
        data_list = data_list_ndr_m5,
        settings_matrix = ndr_settings_matrix,
        distance_metrics_list = my_distance_metrics,
        processes = "max"
    )
})
proc.time() - start
write_csv(
    solutions_matrix_ndr_m5,
    proc_path("solutions_matrix_ndr_m5.csv", TRUE)
)
# mTBI andr uninjured pooled imputed
# Imputation 1
start <- proc.time()
progressr::with_progress({
    solutions_matrix_ndr_pm1 <- batch_snf(
        data_list = data_list_ndr_pm1,
        settings_matrix = ndr_settings_matrix,
        distance_metrics_list = my_distance_metrics,
        processes = "max"
    )
})
proc.time() - start
write_csv(
    solutions_matrix_ndr_pm1,
    proc_path("solutions_matrix_ndr_pm1.csv", TRUE)
)
# Imputation 2
start <- proc.time()
progressr::with_progress({
    solutions_matrix_ndr_pm2 <- batch_snf(
        data_list = data_list_ndr_pm2,
        settings_matrix = ndr_settings_matrix,
        distance_metrics_list = my_distance_metrics,
        processes = "max"
    )
})
proc.time() - start
write_csv(
    solutions_matrix_ndr_pm2,
    proc_path("solutions_matrix_ndr_pm2.csv", TRUE)
)
# Imputation 3
start <- proc.time()
progressr::with_progress({
    solutions_matrix_ndr_pm3 <- batch_snf(
        data_list = data_list_ndr_pm3,
        settings_matrix = ndr_settings_matrix,
        distance_metrics_list = my_distance_metrics,
        processes = "max"
    )
})
proc.time() - start
write_csv(
    solutions_matrix_ndr_pm3,
    proc_path("solutions_matrix_ndr_pm3.csv", TRUE)
)
# Imputation 4
start <- proc.time()
progressr::with_progress({
    solutions_matrix_ndr_pm4 <- batch_snf(
        data_list = data_list_ndr_pm4,
        settings_matrix = ndr_settings_matrix,
        distance_metrics_list = my_distance_metrics,
        processes = "max"
    )
})
proc.time() - start
write_csv(
    solutions_matrix_ndr_pm4,
    proc_path("solutions_matrix_ndr_pm4.csv", TRUE)
)
# Imputation 5
start <- proc.time()
progressr::with_progress({
    solutions_matrix_ndr_pm5 <- batch_snf(
        data_list = data_list_ndr_pm5,
        settings_matrix = ndr_settings_matrix,
        distance_metrics_list = my_distance_metrics,
        processes = "max"
    )
})
proc.time() - start
write_csv(
    solutions_matrix_ndr_pm5,
    proc_path("solutions_matrix_ndr_pm5.csv", TRUE)
)
```

```{r}
solutions_matrix_ndr_m1 <- read_csv(
    proc_path("2024_03_15_solutions_matrix_ndr_m1.csv")
)
solutions_matrix_ndr_m2 <- read_csv(
    proc_path("2024_03_15_solutions_matrix_ndr_m2.csv")
)
solutions_matrix_ndr_m3 <- read_csv(
    proc_path("2024_03_15_solutions_matrix_ndr_m3.csv")
)
solutions_matrix_ndr_m4 <- read_csv(
    proc_path("2024_03_15_solutions_matrix_ndr_m4.csv")
)
solutions_matrix_ndr_m5 <- read_csv(
    proc_path("2024_03_15_solutions_matrix_ndr_m5.csv")
)
solutions_matrix_ndr_pm1 <- read_csv(
    proc_path("2024_03_15_solutions_matrix_ndr_pm1.csv")
)
solutions_matrix_ndr_pm2 <- read_csv(
    proc_path("2024_03_15_solutions_matrix_ndr_pm2.csv")
)
solutions_matrix_ndr_pm3 <- read_csv(
    proc_path("2024_03_15_solutions_matrix_ndr_pm3.csv")
)
solutions_matrix_ndr_pm4 <- read_csv(
    proc_path("2024_03_15_solutions_matrix_ndr_pm4.csv")
)
solutions_matrix_ndr_pm5 <- read_csv(
    proc_path("2024_03_15_solutions_matrix_ndr_pm5.csv")
)

mtbi_ndr_sm <- do.call(
    "rbind",
    list(
        solutions_matrix_ndr_m1,
        solutions_matrix_ndr_m2,
        solutions_matrix_ndr_m3,
        solutions_matrix_ndr_m4,
        solutions_matrix_ndr_m5,
        solutions_matrix_ndr_pm1,
        solutions_matrix_ndr_pm2,
        solutions_matrix_ndr_pm3,
        solutions_matrix_ndr_pm4,
        solutions_matrix_ndr_pm5
    )
)

write_csv(data.frame(mtbi_ndr_sm), proc_path("mtbi_ndr_sm.csv", TRUE))

mtbi_ndr_ari <- calc_aris(mtbi_ndr_sm, processes = "max")
write_csv(data.frame(mtbi_ndr_ari), proc_path("mtbi_ndr_ari.csv", TRUE))

mtbi_ndr_ari_order <- ari_order(mtbi_ndr_ari)
write_csv(data.frame(mtbi_ndr_ari_order), proc_path("mtbi_ndr_ari_order.csv", TRUE))
```

```{r}
mtbi_ndr_sm <- read_csv(proc_path("2024_03_17_mtbi_ndr_sm.csv"))

mtbi_ndr_ari <- read_csv(proc_path("2024_03_15_mtbi_ndr_ari.csv")) |> as.matrix()

mtbi_ndr_ari_order <- unlist(read_csv(proc_path("2024_03_15_mtbi_ndr_ari_order.csv")))
names(mtbi_ndr_ari_order) <- NULL
```

```{r}
imputation_labels <- data.frame(
    "imputation" = c(
        rep("m1", 200),
        rep("m2", 200),
        rep("m3", 200),
        rep("m4", 200),
        rep("m5", 200),
        rep("pm1", 200),
        rep("pm2", 200),
        rep("pm3", 200),
        rep("pm4", 200),
        rep("pm5", 200)
    ),
    "pooled" = c(
        rep("yes", 1000),
        rep("no", 1000)
    )
)

# A variant with oom_list as demographic corrected
imputed_data <- list(
    "m1" = c(data_list_rd_m1, oom_list_nd_m1),
    "m2" = c(data_list_rd_m2, oom_list_nd_m2),
    "m3" = c(data_list_rd_m3, oom_list_nd_m3),
    "m4" = c(data_list_rd_m4, oom_list_nd_m4),
    "m5" = c(data_list_rd_m5, oom_list_nd_m5),
    "pm5" = c(data_list_rd_pm5, oom_list_nd_pm5),
    "pm1" = c(data_list_rd_pm1, oom_list_nd_pm1),
    "pm2" = c(data_list_rd_pm2, oom_list_nd_pm2),
    "pm3" = c(data_list_rd_pm3, oom_list_nd_pm3),
    "pm4" = c(data_list_rd_pm4, oom_list_nd_pm4),
    "pm5" = c(data_list_rd_pm5, oom_list_nd_pm5)
)

# A variant with oom_list not demographic corrected
imputed_data_old_outcomes <- list(
    "m1" = c(data_list_rd_m1, oom_list_m1),
    "m2" = c(data_list_rd_m2, oom_list_m2),
    "m3" = c(data_list_rd_m3, oom_list_m3),
    "m4" = c(data_list_rd_m4, oom_list_m4),
    "m5" = c(data_list_rd_m5, oom_list_m5),
    "pm5" = c(data_list_rd_pm5, oom_list_pm5),
    "pm1" = c(data_list_rd_pm1, oom_list_pm1),
    "pm2" = c(data_list_rd_pm2, oom_list_pm2),
    "pm3" = c(data_list_rd_pm3, oom_list_pm3),
    "pm4" = c(data_list_rd_pm4, oom_list_pm4),
    "pm5" = c(data_list_rd_pm5, oom_list_pm5)
)

mtbi_ndr_sm_l <- cbind(mtbi_ndr_sm, imputation_labels)

# Inputs and corrected outcomes
mtbi_ndr_esm <- extend_solutions_imp(
    mtbi_ndr_sm_l,
    imputed_targets = imputed_data,
    min_p = 1e-10,
    calculate_summaries = FALSE,
    processes = "max"
)
write_csv(mtbi_ndr_esm, proc_path("mtbi_ndr_esm.csv", TRUE))

# Inputs and corrected outcomes
mtbi_ndr_old_esm <- extend_solutions_imp(
    mtbi_ndr_sm_l,
    imputed_targets = imputed_data_old_outcomes,
    min_p = 1e-10,
    calculate_summaries = FALSE,
    processes = "max"
)
write_csv(mtbi_ndr_old_esm, proc_path("mtbi_ndr_old_esm.csv", TRUE))

```

```{r}
mtbi_ndr_old_esm <- read_csv(proc_path("2024_03_17_mtbi_ndr_old_esm.csv"))
mtbi_ndr_esm <- read_csv(proc_path("2024_03_17_mtbi_ndr_esm.csv"))
```

```{r}

mtbi_ndr_split_vec <- c(
    345,
    543,
    620,
    920,
    1073,
    1195,
    1265
)
mtbi_ndr_mc_heatmap <- my_similarity_matrix_heatmap(
    aris = mtbi_ndr_ari,
    aris_order = mtbi_ndr_ari_order,
    extended_solutions = mtbi_ndr_esm,
    split_vector = mtbi_ndr_split_vec
)
mtbi_ndr_mc_heatmap

mc_heatmap_save(mtbi_ndr_mc_heatmap, fig_path("mtbi_ndr_mc_heatmap.png", TRUE))

write_csv(
    data.frame(mtbi_ndr_split_vec),
    proc_path("mtbi_ndr_split_vec.csv", TRUE)
)

mtbi_ndr_split_vec <- proc_path("2024_03_17_mtbi_ndr_split_vec.csv") |>
    read_csv() |>
    unlist() |>
    as.numeric()
```

```{r}

# Function to try to lean on mTBI-including solutions when possible.
restrict_fn <- function(x, threshold = 0.1) {
    x_solo_ind <- x$"imputation" %in% c("m1", "m2", "m3", "m4", "m5")
    x_pool_ind <- x$"imputation" %in% c("pm1", "pm2", "pm3", "pm4", "pm5")
    x_solo <- x[x_solo_ind, ]
    x_pool <- x[x_pool_ind, ]
    frac_solo <- nrow(x_solo) / (nrow(x_solo) + nrow(x_pool))
    if (frac_solo < threshold) {
        return(x_pool_ind)
    } else {
        return(x_solo_ind)
    }
}

# Representative solutions
mtbi_ndr_rep <- get_rep_solutions(
    ari = mtbi_ndr_ari,
    split_vector = mtbi_ndr_split_vec,
    ari_order = mtbi_ndr_ari_order,
    solutions_matrix = mtbi_ndr_esm,
    exclude_mcs = c("D", "H"),
    restriction_function = restrict_fn
)

get_pvals(mtbi_ndr_rep)

write_csv(mtbi_ndr_rep, proc_path("mtbi_ndr_rep.csv", TRUE))

mtbi_ndr_rep <- read_csv(proc_path("2024_03_17_mtbi_ndr_rep.csv"))

all_vars <- c(data_list_rd_m1, oom_list_nd_m1) |>
    collapse_dl() |>
    colnames()
all_vars <- all_vars[-1]

included_vars <- data_list_ndr_m1 |>
    collapse_dl() |>
    colnames()
included_vars <- included_vars[-1]

var_order <- c(
    all_vars[all_vars %in% included_vars],
    all_vars[!(all_vars %in% included_vars)]
)

mtbi_ndr_manhattan <- manhattan_plot2(
    mtbi_ndr_rep,
    data_list = data_list_rd_m1,
    target_list = oom_list_nd_m1,
    variable_order = var_order,
    xints = c(8, 50, 54),
    threshold = 0.05
)
mtbi_ndr_manhattan

ggsave(
    plot = mtbi_ndr_manhattan,
    filename = fig_path("mtbi_ndr_manhattan.png", TRUE),
    width = 20,
    height = 6*3
)

plot_solutions_matrix(
    mtbi_ndr_rep,
    "mtbi_ndr",
    possible_data = imputed_data,
    individual_plots = FALSE,
    group_plots = FALSE
)

```

Not much interesting clustering in the demographic corrected data.
