## Importing packages and establishing file paths

```{r}
library(readr)
library(abcdutils)
library(here)
library(metasnf)
library(rlist)

input_path <- path_maker(here(paste0("data/abcd/inputs")))
proc_path <- path_maker(here(paste0("data/abcd/results/processed")))
fig_path <- path_maker(here(paste0("data/abcd/results/figures")))

source("abcd/functions.R")
```

```{r}
# MTBI
data_list_m1 <- list.load(input_path("2024_02_14_data_list_m1.rds"))
data_list_m2 <- list.load(input_path("2024_02_14_data_list_m2.rds"))
data_list_m3 <- list.load(input_path("2024_02_14_data_list_m3.rds"))
data_list_m4 <- list.load(input_path("2024_02_14_data_list_m4.rds"))
data_list_m5 <- list.load(input_path("2024_02_14_data_list_m5.rds"))
data_list_pm1 <- list.load(input_path("2024_02_14_data_list_pm1.rds"))
data_list_pm2 <- list.load(input_path("2024_02_14_data_list_pm2.rds"))
data_list_pm3 <- list.load(input_path("2024_02_14_data_list_pm3.rds"))
data_list_pm4 <- list.load(input_path("2024_02_14_data_list_pm4.rds"))
data_list_pm5 <- list.load(input_path("2024_02_14_data_list_pm5.rds"))
oom_list_m1 <- list.load(input_path("2024_02_14_oom_list_m1.rds"))
oom_list_m2 <- list.load(input_path("2024_02_14_oom_list_m2.rds"))
oom_list_m3 <- list.load(input_path("2024_02_14_oom_list_m3.rds"))
oom_list_m4 <- list.load(input_path("2024_02_14_oom_list_m4.rds"))
oom_list_m5 <- list.load(input_path("2024_02_14_oom_list_m5.rds"))
oom_list_pm1 <- list.load(input_path("2024_02_14_oom_list_pm1.rds"))
oom_list_pm2 <- list.load(input_path("2024_02_14_oom_list_pm2.rds"))
oom_list_pm3 <- list.load(input_path("2024_02_14_oom_list_pm3.rds"))
oom_list_pm4 <- list.load(input_path("2024_02_14_oom_list_pm4.rds"))
oom_list_pm5 <- list.load(input_path("2024_02_14_oom_list_pm5.rds"))

# MTBI-ND

data_list_rd_m1 <- list.load(input_path("2024_03_11_data_list_re_demo_m1.rds"))
data_list_rd_m2 <- list.load(input_path("2024_03_11_data_list_re_demo_m2.rds"))
data_list_rd_m3 <- list.load(input_path("2024_03_11_data_list_re_demo_m3.rds"))
data_list_rd_m4 <- list.load(input_path("2024_03_11_data_list_re_demo_m4.rds"))
data_list_rd_m5 <- list.load(input_path("2024_03_11_data_list_re_demo_m5.rds"))
data_list_rd_pm1 <- list.load(input_path("2024_03_11_data_list_re_demo_pm1.rds"))
data_list_rd_pm2 <- list.load(input_path("2024_03_11_data_list_re_demo_pm2.rds"))
data_list_rd_pm3 <- list.load(input_path("2024_03_11_data_list_re_demo_pm3.rds"))
data_list_rd_pm4 <- list.load(input_path("2024_03_11_data_list_re_demo_pm4.rds"))
data_list_rd_pm5 <- list.load(input_path("2024_03_11_data_list_re_demo_pm5.rds"))
oom_list_nd_m1 <- list.load(input_path("2024_03_11_oom_list_nd_m1.rds"))
oom_list_nd_m2 <- list.load(input_path("2024_03_11_oom_list_nd_m2.rds"))
oom_list_nd_m3 <- list.load(input_path("2024_03_11_oom_list_nd_m3.rds"))
oom_list_nd_m4 <- list.load(input_path("2024_03_11_oom_list_nd_m4.rds"))
oom_list_nd_m5 <- list.load(input_path("2024_03_11_oom_list_nd_m5.rds"))
oom_list_nd_pm1 <- list.load(input_path("2024_03_11_oom_list_nd_pm1.rds"))
oom_list_nd_pm2 <- list.load(input_path("2024_03_11_oom_list_nd_pm2.rds"))
oom_list_nd_pm3 <- list.load(input_path("2024_03_11_oom_list_nd_pm3.rds"))
oom_list_nd_pm4 <- list.load(input_path("2024_03_11_oom_list_nd_pm4.rds"))
oom_list_nd_pm5 <- list.load(input_path("2024_03_11_oom_list_nd_pm5.rds"))

# MU
data_list_mu1 <- list.load(input_path("2024_02_14_data_list_mu1.rds"))
data_list_mu2 <- list.load(input_path("2024_02_14_data_list_mu2.rds"))
data_list_mu3 <- list.load(input_path("2024_02_14_data_list_mu3.rds"))
data_list_mu4 <- list.load(input_path("2024_02_14_data_list_mu4.rds"))
data_list_mu5 <- list.load(input_path("2024_02_14_data_list_mu5.rds"))
data_list_mpu1 <- list.load(input_path("2024_02_14_data_list_mpu1.rds"))
data_list_mpu2 <- list.load(input_path("2024_02_14_data_list_mpu2.rds"))
data_list_mpu3 <- list.load(input_path("2024_02_14_data_list_mpu3.rds"))
data_list_mpu4 <- list.load(input_path("2024_02_14_data_list_mpu4.rds"))
data_list_mpu5 <- list.load(input_path("2024_02_14_data_list_mpu5.rds"))
oom_list_mu1 <- list.load(input_path("2024_02_14_oom_list_mu1.rds"))
oom_list_mu2 <- list.load(input_path("2024_02_14_oom_list_mu2.rds"))
oom_list_mu3 <- list.load(input_path("2024_02_14_oom_list_mu3.rds"))
oom_list_mu4 <- list.load(input_path("2024_02_14_oom_list_mu4.rds"))
oom_list_mu5 <- list.load(input_path("2024_02_14_oom_list_mu5.rds"))
oom_list_mpu1 <- list.load(input_path("2024_02_14_oom_list_mpu1.rds"))
oom_list_mpu2 <- list.load(input_path("2024_02_14_oom_list_mpu2.rds"))
oom_list_mpu3 <- list.load(input_path("2024_02_14_oom_list_mpu3.rds"))
oom_list_mpu4 <- list.load(input_path("2024_02_14_oom_list_mpu4.rds"))
oom_list_mpu5 <- list.load(input_path("2024_02_14_oom_list_mpu5.rds"))

# MU-ND
data_list_re_demo_mu1 <- list.load(input_path("2024_02_27_data_list_re_demo_mu1.rds"))
data_list_re_demo_mu2 <- list.load(input_path("2024_02_27_data_list_re_demo_mu2.rds"))
data_list_re_demo_mu3 <- list.load(input_path("2024_02_27_data_list_re_demo_mu3.rds"))
data_list_re_demo_mu4 <- list.load(input_path("2024_02_27_data_list_re_demo_mu4.rds"))
data_list_re_demo_mu5 <- list.load(input_path("2024_02_27_data_list_re_demo_mu5.rds"))
data_list_re_demo_mpu1 <- list.load(input_path("2024_02_27_data_list_re_demo_mpu1.rds"))
data_list_re_demo_mpu2 <- list.load(input_path("2024_02_27_data_list_re_demo_mpu2.rds"))
data_list_re_demo_mpu3 <- list.load(input_path("2024_02_27_data_list_re_demo_mpu3.rds"))
data_list_re_demo_mpu4 <- list.load(input_path("2024_02_27_data_list_re_demo_mpu4.rds"))
data_list_re_demo_mpu5 <- list.load(input_path("2024_02_27_data_list_re_demo_mpu5.rds"))
oom_list_no_demo_mu1 <- list.load(input_path("2024_02_27_oom_list_no_demo_mu1.rds"))
oom_list_no_demo_mu2 <- list.load(input_path("2024_02_27_oom_list_no_demo_mu2.rds"))
oom_list_no_demo_mu3 <- list.load(input_path("2024_02_27_oom_list_no_demo_mu3.rds"))
oom_list_no_demo_mu4 <- list.load(input_path("2024_02_27_oom_list_no_demo_mu4.rds"))
oom_list_no_demo_mu5 <- list.load(input_path("2024_02_27_oom_list_no_demo_mu5.rds"))
oom_list_no_demo_mpu1 <- list.load(input_path("2024_02_27_oom_list_no_demo_mpu1.rds"))
oom_list_no_demo_mpu2 <- list.load(input_path("2024_02_27_oom_list_no_demo_mpu2.rds"))
oom_list_no_demo_mpu3 <- list.load(input_path("2024_02_27_oom_list_no_demo_mpu3.rds"))
oom_list_no_demo_mpu4 <- list.load(input_path("2024_02_27_oom_list_no_demo_mpu4.rds"))
oom_list_no_demo_mpu5 <- list.load(input_path("2024_02_27_oom_list_no_demo_mpu5.rds"))

# CMU
data_list_cmu1 <- list.load(input_path("2024_02_14_data_list_cmu1.rds"))
data_list_cmu2 <- list.load(input_path("2024_02_14_data_list_cmu2.rds"))
data_list_cmu3 <- list.load(input_path("2024_02_14_data_list_cmu3.rds"))
data_list_cmu4 <- list.load(input_path("2024_02_14_data_list_cmu4.rds"))
data_list_cmu5 <- list.load(input_path("2024_02_14_data_list_cmu5.rds"))
data_list_cmpu1 <- list.load(input_path("2024_02_14_data_list_cmpu1.rds"))
data_list_cmpu2 <- list.load(input_path("2024_02_14_data_list_cmpu2.rds"))
data_list_cmpu3 <- list.load(input_path("2024_02_14_data_list_cmpu3.rds"))
data_list_cmpu4 <- list.load(input_path("2024_02_14_data_list_cmpu4.rds"))
data_list_cmpu5 <- list.load(input_path("2024_02_14_data_list_cmpu5.rds"))
oom_list_cmu1 <- list.load(input_path("2024_02_14_oom_list_cmu1.rds"))
oom_list_cmu2 <- list.load(input_path("2024_02_14_oom_list_cmu2.rds"))
oom_list_cmu3 <- list.load(input_path("2024_02_14_oom_list_cmu3.rds"))
oom_list_cmu4 <- list.load(input_path("2024_02_14_oom_list_cmu4.rds"))
oom_list_cmu5 <- list.load(input_path("2024_02_14_oom_list_cmu5.rds"))
oom_list_cmpu1 <- list.load(input_path("2024_02_14_oom_list_cmpu1.rds"))
oom_list_cmpu2 <- list.load(input_path("2024_02_14_oom_list_cmpu2.rds"))
oom_list_cmpu3 <- list.load(input_path("2024_02_14_oom_list_cmpu3.rds"))
oom_list_cmpu4 <- list.load(input_path("2024_02_14_oom_list_cmpu4.rds"))
oom_list_cmpu5 <- list.load(input_path("2024_02_14_oom_list_cmpu5.rds"))

# CMU-ND
data_list_re_demo_cmu1 <- list.load(input_path("2024_02_27_data_list_re_demo_cmu1.rds"))
data_list_re_demo_cmu2 <- list.load(input_path("2024_02_27_data_list_re_demo_cmu2.rds"))
data_list_re_demo_cmu3 <- list.load(input_path("2024_02_27_data_list_re_demo_cmu3.rds"))
data_list_re_demo_cmu4 <- list.load(input_path("2024_02_27_data_list_re_demo_cmu4.rds"))
data_list_re_demo_cmu5 <- list.load(input_path("2024_02_27_data_list_re_demo_cmu5.rds"))
data_list_re_demo_cmpu1 <- list.load(input_path("2024_02_27_data_list_re_demo_cmpu1.rds"))
data_list_re_demo_cmpu2 <- list.load(input_path("2024_02_27_data_list_re_demo_cmpu2.rds"))
data_list_re_demo_cmpu3 <- list.load(input_path("2024_02_27_data_list_re_demo_cmpu3.rds"))
data_list_re_demo_cmpu4 <- list.load(input_path("2024_02_27_data_list_re_demo_cmpu4.rds"))
data_list_re_demo_cmpu5 <- list.load(input_path("2024_02_27_data_list_re_demo_cmpu5.rds"))
oom_list_no_demo_cmu1 <- list.load(input_path("2024_02_27_oom_list_no_demo_cmu1.rds"))
oom_list_no_demo_cmu2 <- list.load(input_path("2024_02_27_oom_list_no_demo_cmu2.rds"))
oom_list_no_demo_cmu3 <- list.load(input_path("2024_02_27_oom_list_no_demo_cmu3.rds"))
oom_list_no_demo_cmu4 <- list.load(input_path("2024_02_27_oom_list_no_demo_cmu4.rds"))
oom_list_no_demo_cmu5 <- list.load(input_path("2024_02_27_oom_list_no_demo_cmu5.rds"))
oom_list_no_demo_cmpu1 <- list.load(input_path("2024_02_27_oom_list_no_demo_cmpu1.rds"))
oom_list_no_demo_cmpu2 <- list.load(input_path("2024_02_27_oom_list_no_demo_cmpu2.rds"))
oom_list_no_demo_cmpu3 <- list.load(input_path("2024_02_27_oom_list_no_demo_cmpu3.rds"))
oom_list_no_demo_cmpu4 <- list.load(input_path("2024_02_27_oom_list_no_demo_cmpu4.rds"))
oom_list_no_demo_cmpu5 <- list.load(input_path("2024_02_27_oom_list_no_demo_cmpu5.rds"))

# OCMU
data_list_ocmu1 <- list.load(input_path("2024_03_05_data_list_ocmu1.rds"))
data_list_ocmu2 <- list.load(input_path("2024_03_05_data_list_ocmu2.rds"))
data_list_ocmu3 <- list.load(input_path("2024_03_05_data_list_ocmu3.rds"))
data_list_ocmu4 <- list.load(input_path("2024_03_05_data_list_ocmu4.rds"))
data_list_ocmu5 <- list.load(input_path("2024_03_05_data_list_ocmu5.rds"))
data_list_ocmpu1 <- list.load(input_path("2024_03_05_data_list_ocmpu1.rds"))
data_list_ocmpu2 <- list.load(input_path("2024_03_05_data_list_ocmpu2.rds"))
data_list_ocmpu3 <- list.load(input_path("2024_03_05_data_list_ocmpu3.rds"))
data_list_ocmpu4 <- list.load(input_path("2024_03_05_data_list_ocmpu4.rds"))
data_list_ocmpu5 <- list.load(input_path("2024_03_05_data_list_ocmpu5.rds"))
oom_list_ocmu1 <- list.load(input_path("2024_03_05_oom_list_ocmu1.rds"))
oom_list_ocmu2 <- list.load(input_path("2024_03_05_oom_list_ocmu2.rds"))
oom_list_ocmu3 <- list.load(input_path("2024_03_05_oom_list_ocmu3.rds"))
oom_list_ocmu4 <- list.load(input_path("2024_03_05_oom_list_ocmu4.rds"))
oom_list_ocmu5 <- list.load(input_path("2024_03_05_oom_list_ocmu5.rds"))
oom_list_ocmpu1 <- list.load(input_path("2024_03_05_oom_list_ocmpu1.rds"))
oom_list_ocmpu2 <- list.load(input_path("2024_03_05_oom_list_ocmpu2.rds"))
oom_list_ocmpu3 <- list.load(input_path("2024_03_05_oom_list_ocmpu3.rds"))
oom_list_ocmpu4 <- list.load(input_path("2024_03_05_oom_list_ocmpu4.rds"))
oom_list_ocmpu5 <- list.load(input_path("2024_03_05_oom_list_ocmpu5.rds"))

```


```{r}
mtbi_io_esm <- read_csv(proc_path("2024_02_28_mtbi_io_esm.csv"))
mtbi_ari <- read_csv(proc_path("2024_02_15_aris_all_mtbi_imputations.csv"))
mtbi_ari_order <- read_csv(proc_path("2024_02_28_mtbi_ari_order.csv"))
mtbi_split_vec <- c(233, 350, 500, 723, 830, 1404, 1685, 1900)

mtbi_nd_io_esm <- read_csv(proc_path("2024_03_11_mtbi_nd_io_esm.csv"))
mtbi_nd_ari <- read_csv(proc_path("2024_03_11_mtbi_nd_ari.csv"))
mtbi_nd_ari_order <- read_csv(proc_path("2024_03_11_mtbi_nd_ari_order.csv"))
mtbi_nd_split_vec <- c(330, 550, 755, 995, 1175, 1320, 1430, 1650)

mu_io_esm <- read_csv(proc_path("2024_02_25_full_mu_io_extended_solutions_matrix.csv"))
mu_ari <- read_csv(proc_path("2024_02_15_aris_all_uninjured_imputations.csv"))
mu_ari_order <- read_csv(proc_path("2024_02_25_aris_all_uninjured_imputations_order.csv"))
mu_split_vec <- c(686, 1075, 1115, 1223, 1245, 1350, 1558)

mu_nd_io_esm <- read_csv(proc_path("2024_02_27_mu_nd_io_esm.csv"))
mu_nd_ari <- read_csv(proc_path("2024_02_25_aris_all_mu_imputations_no_demo.csv"))
mu_nd_ari_order <- read_csv(proc_path("2024_02_25_aris_all_mu_imputations_order_no_demo.csv"))
mu_nd_split_vec = c(329, 520, 823, 928, 1030, 1090, 1470, 1700, 1840, 1920)

cmu_io_esm <- read_csv(proc_path("2024_02_28_cmu_io_esm.csv"))
cmu_ari <- read_csv(proc_path("2024_02_15_aris_all_cmu_imputations.csv"))
cmu_ari_order <- read_csv(proc_path("2024_02_28_cmu_ari_order.csv"))
cmu_split_vec <- c(690, 1160, 1330, 1395, 1440, 1780)

cmu_3c_io_esm <- read_csv(proc_path("2024_03_10_cmu_3c_io_esm.csv"))
cmu_3c_ari <- read_csv(proc_path("2024_03_08_cmu_3c_ari.csv"))
cmu_3c_ari_order <- read_csv(proc_path("2024_03_10_cmu_3c_ari_order.csv"))
cmu_3c_split_vec <- c(95, 380, 590, 700, 850, 990, 1170, 1290, 1810, 1900)

cmu_nd_io_esm <- read_csv(proc_path("2024_02_27_cmu_nd_io_esm.csv"))
cmu_nd_ari <- read_csv(proc_path("2024_02_25_aris_all_cmu_imputations_no_demo.csv"))
cmu_nd_ari_order <- read_csv(proc_path( "2024_02_25_aris_all_cmu_imputations_order_no_demo.csv"))
cmu_nd_split_vec <- c(295, 395, 590, 705, 805, 915, 1020, 1255, 1345, 1405, 1500)

ocmu_io_esm <- read_csv(proc_path("2024_03_07_ocmu_io_esm.csv"))
ocmu_ari <- read_csv(proc_path("2024_03_06_ocmu_ari.csv"))
ocmu_ari_order <- read_csv(proc_path("2024_03_07_ocmu_ari_order.csv"))
ocmu_split_vec <- c(487, 610, 1015, 1070, 1135, 1180, 1555, 1845, 1945)

```


```{r}
# MTBI
representative_mc(
    split_vector = mtbi_split_vec,
    aris = mtbi_ari,
    ari_order = mtbi_ari_order,
    solutions_matrix = mtbi_io_esm,
    group_name = "mtbi",
    possible_data = list(
        "m1" = c(data_list_m1, oom_list_m1),
        "m2" = c(data_list_m2, oom_list_m2),
        "m3" = c(data_list_m3, oom_list_m3),
        "m4" = c(data_list_m4, oom_list_m4),
        "m5" = c(data_list_m5, oom_list_m5),
        "pm5" = c(data_list_pm5, oom_list_pm5),
        "pm1" = c(data_list_pm1, oom_list_pm1),
        "pm2" = c(data_list_pm2, oom_list_pm2),
        "pm3" = c(data_list_pm3, oom_list_pm3),
        "pm4" = c(data_list_pm4, oom_list_pm4),
        "pm5" = c(data_list_pm5, oom_list_pm5)
    )
)

# MTBI-ND
representative_mc(
    split_vector = mtbi_nd_split_vec,
    aris = mtbi_nd_ari,
    ari_order = mtbi_nd_ari_order,
    solutions_matrix = mtbi_nd_io_esm,
    group_name = "mtbi_nd",
    possible_data = list(
        "m1" = c(data_list_rd_m1, oom_list_nd_m1),
        "m2" = c(data_list_rd_m2, oom_list_nd_m2),
        "m3" = c(data_list_rd_m3, oom_list_nd_m3),
        "m4" = c(data_list_rd_m4, oom_list_nd_m4),
        "m5" = c(data_list_rd_m5, oom_list_nd_m5),
        "pm5" = c(data_list_rd_pm5, oom_list_nd_pm5),
        "pm1" = c(data_list_rd_pm1, oom_list_nd_pm1),
        "pm2" = c(data_list_rd_pm2, oom_list_nd_pm2),
        "pm3" = c(data_list_rd_pm3, oom_list_nd_pm3),
        "pm4" = c(data_list_rd_pm4, oom_list_nd_pm4),
        "pm5" = c(data_list_rd_pm5, oom_list_nd_pm5)
    ),
    individual_plots = FALSE,
    group_plots = FALSE
)

# MU
representative_mc(
    split_vector = mu_split_vec,
    aris = mu_ari,
    ari_order = mu_ari_order,
    solutions_matrix = mu_io_esm,
    group_name = "mu",
    possible_data = list(
        "u1" = c(data_list_mu1, oom_list_mu1),
        "u2" = c(data_list_mu2, oom_list_mu2),
        "u3" = c(data_list_mu3, oom_list_mu3),
        "u4" = c(data_list_mu4, oom_list_mu4),
        "u5" = c(data_list_mu5, oom_list_mu5),
        "pu5" = c(data_list_mpu5, oom_list_mpu5),
        "pu1" = c(data_list_mpu1, oom_list_mpu1),
        "pu2" = c(data_list_mpu2, oom_list_mpu2),
        "pu3" = c(data_list_mpu3, oom_list_mpu3),
        "pu4" = c(data_list_mpu4, oom_list_mpu4),
        "pu5" = c(data_list_mpu5, oom_list_mpu5)
    )
)

# MU-ND
representative_mc(
    split_vector = mu_nd_split_vec,
    aris = mu_nd_ari,
    ari_order = mu_nd_ari_order,
    solutions_matrix = mu_nd_io_esm,
    group_name = "mu_nd",
    possible_data = list(
        "u1" = c(data_list_re_demo_mu1, oom_list_no_demo_mu1),
        "u2" = c(data_list_re_demo_mu2, oom_list_no_demo_mu2),
        "u3" = c(data_list_re_demo_mu3, oom_list_no_demo_mu3),
        "u4" = c(data_list_re_demo_mu4, oom_list_no_demo_mu4),
        "u5" = c(data_list_re_demo_mu5, oom_list_no_demo_mu5),
        "pu5" = c(data_list_re_demo_mpu5, oom_list_no_demo_mpu5),
        "pu1" = c(data_list_re_demo_mpu1, oom_list_no_demo_mpu1),
        "pu2" = c(data_list_re_demo_mpu2, oom_list_no_demo_mpu2),
        "pu3" = c(data_list_re_demo_mpu3, oom_list_no_demo_mpu3),
        "pu4" = c(data_list_re_demo_mpu4, oom_list_no_demo_mpu4),
        "pu5" = c(data_list_re_demo_mpu5, oom_list_no_demo_mpu5)
    )
)

# CMU
representative_mc(
    split_vector = cmu_split_vec,
    aris = cmu_ari,
    ari_order = cmu_ari_order,
    solutions_matrix = cmu_io_esm,
    group_name = "cmu",
    possible_data = list(
        "u1" = c(data_list_cmu1, oom_list_cmu1),
        "u2" = c(data_list_cmu2, oom_list_cmu2),
        "u3" = c(data_list_cmu3, oom_list_cmu3),
        "u4" = c(data_list_cmu4, oom_list_cmu4),
        "u5" = c(data_list_cmu5, oom_list_cmu5),
        "pu5" = c(data_list_cmpu5, oom_list_cmpu5),
        "pu1" = c(data_list_cmpu1, oom_list_cmpu1),
        "pu2" = c(data_list_cmpu2, oom_list_cmpu2),
        "pu3" = c(data_list_cmpu3, oom_list_cmpu3),
        "pu4" = c(data_list_cmpu4, oom_list_cmpu4),
        "pu5" = c(data_list_cmpu5, oom_list_cmpu5)
    )
)

# CMU-3C
# The MC-A plots match the mTBI group
representative_mc(
    split_vector = cmu_3c_split_vec,
    aris = cmu_3c_ari,
    ari_order = cmu_3c_ari_order,
    solutions_matrix = cmu_3c_io_esm,
    group_name = "cmu_3c",
    possible_data = list(
        "u1" = c(data_list_cmu1, oom_list_cmu1),
        "u2" = c(data_list_cmu2, oom_list_cmu2),
        "u3" = c(data_list_cmu3, oom_list_cmu3),
        "u4" = c(data_list_cmu4, oom_list_cmu4),
        "u5" = c(data_list_cmu5, oom_list_cmu5),
        "pu5" = c(data_list_cmpu5, oom_list_cmpu5),
        "pu1" = c(data_list_cmpu1, oom_list_cmpu1),
        "pu2" = c(data_list_cmpu2, oom_list_cmpu2),
        "pu3" = c(data_list_cmpu3, oom_list_cmpu3),
        "pu4" = c(data_list_cmpu4, oom_list_cmpu4),
        "pu5" = c(data_list_cmpu5, oom_list_cmpu5)
    ),
    individual_plots = FALSE,
    group_plots = FALSE
)


# CMU-ND
representative_mc(
    split_vector = cmu_nd_split_vec,
    aris = cmu_nd_ari,
    ari_order = cmu_nd_ari_order,
    solutions_matrix = cmu_nd_io_esm,
    group_name = "cmu_nd",
    possible_data = list(
        "mu1" = c(data_list_re_demo_cmu1, oom_list_no_demo_cmu1),
        "mu2" = c(data_list_re_demo_cmu2, oom_list_no_demo_cmu2),
        "mu3" = c(data_list_re_demo_cmu3, oom_list_no_demo_cmu3),
        "mu4" = c(data_list_re_demo_cmu4, oom_list_no_demo_cmu4),
        "mu5" = c(data_list_re_demo_cmu5, oom_list_no_demo_cmu5),
        "mpu5" = c(data_list_re_demo_cmpu5, oom_list_no_demo_cmpu5),
        "mpu1" = c(data_list_re_demo_cmpu1, oom_list_no_demo_cmpu1),
        "mpu2" = c(data_list_re_demo_cmpu2, oom_list_no_demo_cmpu2),
        "mpu3" = c(data_list_re_demo_cmpu3, oom_list_no_demo_cmpu3),
        "mpu4" = c(data_list_re_demo_cmpu4, oom_list_no_demo_cmpu4),
        "mpu5" = c(data_list_re_demo_cmpu5, oom_list_no_demo_cmpu5)
    )
)

# OCMU
representative_mc(
    split_vector = ocmu_split_vec,
    aris = ocmu_ari,
    ari_order = ocmu_ari_order,
    solutions_matrix = ocmu_io_esm,
    group_name = "ocmu",
    possible_data = list(
        "u1" = c(data_list_ocmu1, oom_list_ocmu1),
        "u2" = c(data_list_ocmu2, oom_list_ocmu2),
        "u3" = c(data_list_ocmu3, oom_list_ocmu3),
        "u4" = c(data_list_ocmu4, oom_list_ocmu4),
        "u5" = c(data_list_ocmu5, oom_list_ocmu5),
        "pu5" = c(data_list_ocmpu5, oom_list_ocmpu5),
        "pu1" = c(data_list_ocmpu1, oom_list_ocmpu1),
        "pu2" = c(data_list_ocmpu2, oom_list_ocmpu2),
        "pu3" = c(data_list_ocmpu3, oom_list_ocmpu3),
        "pu4" = c(data_list_ocmpu4, oom_list_ocmpu4),
        "pu5" = c(data_list_ocmpu5, oom_list_ocmpu5)
    )
)

```

A custom search among 3 cluster solutions in the CMU group:

```{r}

cmu_3c <- cmu_io_esm |>
    dplyr::filter(nclust == 3) |>
    dplyr::select(dplyr::starts_with(c("row", "imput", "cbcl", "sds")))


means <- apply(cmu_3c[, 3:ncol(cmu_3c)], 1, FUN = mean)

top_3c <- which(means == min(means))

top_3c_cmu <- cmu_3c[top_3c, ]

top_3c_imp <- top_3c_cmu$"imputation"
top_3c_id <- top_3c_cmu$"row_id"

top_3c_cmu <- cmu_io_esm |>
    dplyr::filter(imputation == top_3c_imp, row_id == top_3c_id)

characterize_solution(
    solution = top_3c_cmu,
    data_list = c(data_list_cmu4, oom_list_cmu4),
    plotname = fig_path("cmu_top_3c", TRUE)
)

top_3c_cmu

```
