{
  "hash": "2abb8c5085285fc8084e0985fdbbdad0",
  "result": {
    "markdown": "# Identifying subjects\n\nThe TBI information of the ABCD dataset is split across a few files:\n\n* `abcd_otbi01.txt`: the raw, modified Ohio State TBI screen given at baseline\n* `abcd_tbi01.txt`: summary scores of abcd_otbi01.txt\n* `abcd_lpohstbi01.txt`: all longitudinal follow-ups of the baseline screen\n* `abcd_lsstbi01.txt`: summary scores of abcd_lpohstbi01.txt\n\nAll information required for identifying children at a chronic stage following mTBI as of baseline data collection is available in the `abcd_otbi01.txt` file.\n\n\n## Renaming the mTBI data\n\n\n\n\nThe script below was used to rename the data columns of the abcd_otbi01 file to be more interpretable.\n\n**Script location**:\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"subtyping-mtbi/abcd/rename_abcd_otbi01.Rmd\"\n```\n:::\n:::\n\n\n**Renaming abcd_otbi01 columns**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\n\n# IMPORT DATA ===============================================================\nabcd_otbi01 <- \n    read_delim(\"lab-data/abcd/4.0/trauma/abcd_otbi01.txt\")[-1, ]\n\n\n# RENAME DATA ===============================================================\nabcd_otbi01_renamed <- abcd_otbi01 |>\n    rename(\n        hosp_er_inj = tbi_1, # ever hospitalized/ER for head/neck injury?\n        hosp_er_loc = tbi_1b, # if LOC, how long?\n        hosp_er_mem_daze = tbi_1c, # were they dazed or have memory gap?\n        hosp_er_age = tbi_1d, # how old were they?\n        vehicle_inj = tbi_2, # ever injured in a vehicle accident?\n        vehicle_loc = tbi_2b, # if LOC, how long?\n        vehicle_mem_daze = tbi_2c, # were they dazed or have memory gap?\n        vehicle_age = tbi_2d, # how old were they?\n        fall_hit_inj = tbi_3, # ever injured head/neck from fall or hit?\n        fall_hit_loc = tbi_3b, # if LOC, how long?\n        fall_hit_mem_daze = tbi_3c, # were they dazed or have memory gap?\n        fall_hit_age = tbi_3d, # how old were they?\n        violent_hit_inj = tbi_4, # ever injure head/neck from violence?\n        violent_hit_loc = tbi_4b, # if LOC, how long?\n        violent_hit_mem_daze = tbi_4c, # were they dazed or have memory gap?\n        violent_hit_age = tbi_4d, # how old were they?\n        blast_inj = tbi_5, # ever injure head or neck from blast?\n        blast_loc = tbi_5b, # if LOC, how long?\n        blast_mem_daze = tbi_5c, # were they dazed or have memory gap?\n        blast_age = tbi_5d, # how old were they?\n        other_loc_inj = tbi_6o, # any other injuries with LOC?\n        other_loc_num = tbi_6p, # how many more?\n        other_loc_max_loc_mins = tbi_6q, # how long was longest LOC?\n        other_loc_num_over_30 = tbi_6r, # how many were >= 30 min?\n        other_loc_min_age = tbi_6s, # what was their youngest age?\n        multi_inj = tbi_7a, # did they have a period of multiple injuries?\n        multi_loc = tbi_7c1, # if LOC, how long?\n        multi_mem_daze = tbl_7c2, # were they dazed or have memory gap?\n        multi_effect_start_age = tbi_7e, # at what age did the effects begin?\n        multi_effect_end_age = tbi_7f, # at what age did the effects end?\n        other_multi_inj = tbi_7g, # was there another multiple injury period?\n        other_multi_effect_type = tbi_7i, # typical effect of the injury?\n        other_multi_effect_start_age = tbi_7k, # start age of those effects?\n        other_multi_effect_end_age = tbi_7l, # end age of those effects?\n        other_other_multi_inj = tbi_8g, # another period of multiple inj?\n        other_other_multi_effect_type = tbi_8i, # typical effects?\n        other_other_multi_effect_start_age = tbi_8k, # start age of effects?\n        other_other_multi_effect_end_age = tbi_8l) # end age of effects?\n\n\n# EXPORT DATA ===============================================================\nlocal_path <-\n    \"lab-data/abcd/processed/prashanth-proj/data/processed_otbi01_renamed.csv\"\n\nwrite_csv(abcd_otbi01_renamed, local_path)\n```\n:::\n\n\n\nNote that all variables with the same prefix (or number originally) are referring to the same injury or set of injuries.\n\n\n## Identifying subjects at a chronic stage post-mTBI\n\nTo identify subjects at a chronic stage post-mTBI, two intermediate pieces of information must be calculated from the original dataset:\n\n* identifying which head injuries were mTBIs\n* identifying the time since the most recent mTBI\n\nThe structure of the Ohio State TBI screen as used for ABCD data collection was not completely compatible with the most commonly used definition of mTBI @WYA25C6X#Blennow_Etal_2016:\n\nAt least one of the following:\n\n* Any period of loss of consciousness\n* Any loss of memory\n* Any alteration in mental state\n* Focal neurological deficits\n\nbut where the severity does not exceed:\n\n* LOC over 30 minutes\n* A Glasgow Coma Scale score below 13\n* Post-traumatic amnesia (PTA) greater than 24 hours\n\nA few aspects of the data collection process in the ABCD study precluded the usage of this definition:\n\n* No information was collected regarding the GCS\n* Feeling dazed and PTA were combined into a single variable, making it unclear which combination of symptoms was present\n* No information was collected regarding the duration of feeling dazed or experiencing PTA\n\nConsequently, I used the following definition to identify mTBIs:\n\nAny child who experienced at least one injury where that injury resulted in either:\n\n1. Less than 30 minutes of LOC (including 0 minutes) **AND** any duration of memory loss / feeling dazed\n2. LOC that is greater than 0 minutes but less than 30 minutes.\n\nThe fixed nature of the questionnaire also meant that some information about multiple mTBIs sustained in the same way or about a very large number of mTBIs throughout a child's life could have been lost (see the previous section on identifying children with a history of mTBI).\nFor my analyses, I assume these edge cases are not common enough to meaningfully change any obtained conclusions.\n\nThe code below generates a new file which adds the following columns to the TBI screen data:\n\n1. if a subject has experienced an mTBI prior to baseline\n2. which of the reported head injuries were mTBIs\n3. the time since a subject's most recent mTBI\n\n\n\n\nThe code below adds the following information to the otbi01 file:\n1. if a subject had > 0 mTBI (colname: mTBI)\n2. if a subject had > 0 mod/sev TBI (colname: moderate_or_severe_tbi)\n3. if each type of injury was an mTBI (colnames: x_mtbi)\n4. the time since each type of mTBI\n5. the time since the most recent mTBI\n\nThere are additional sections which involve:\n6. Visualizing the time since latest mTBI for each subject\n7. Examining the number of mTBIs sustained by each subject\n\n\n**Script location**:\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"subtyping-mtbi/abcd/detail_otbi01.Rmd\"\n```\n:::\n:::\n\n**Generate detailed form of abcd_otbi01**:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(magrittr)\n\n# IMPORT DATA ===============================================================\ninput_file <-\n    \"lab-data/abcd/processed/prashanth-proj/data/processed_otbi01_renamed.csv\"\n\notbi01 <- read_delim(input_file, guess_max = Inf)\n# guess_max = Inf required to import without parsing errors (see ?readr)\n\n\n# CONVERT TO NUMERIC ========================================================\notbi01_detailed <- otbi01 %>%\n  mutate(across(hosp_er_inj:other_other_multi_effect_end_age, as.numeric))\n```\n:::\n\n\n**1. Identify if a subject has had mTBI prior to baseline (col: mTBI)**\nIt is not possible to properly classify mTBI in the ABCD dataset\nHere, I define an mTBI as a head/neck injury which was either:\n1. LOC < 30 mins (LOC < 2) and memory loss (mem_daze == 1)\n2. LOC between 0 and 30 mins (LOC == 1)\n\nIn this section, I create an mTBI column with the values:\n\\0 - definitely had 0 mTBI\n\\1 - definitely had at LEAST one mTBI\n\\0.5 - impossible to know if patient had at least one mTBI\n\n::: {.cell}\n\n```{.r .cell-code}\n# ASSIGN MTBIS ==============================================================\notbi01_detailed %<>%\n  mutate(mtbi = case_when(\n    (hosp_er_loc < 2 & hosp_er_mem_daze == 1) | hosp_er_loc == 1 ~ 1,\n    (vehicle_loc < 2 & vehicle_mem_daze == 1) | vehicle_loc == 1 ~ 1,\n    (fall_hit_loc < 2 & fall_hit_mem_daze == 1) | fall_hit_loc == 1 ~ 1,\n    (violent_hit_loc < 2 & violent_hit_mem_daze == 1) | violent_hit_loc ==\n        1 ~ 1,\n    (blast_loc < 2 & blast_mem_daze == 1) | blast_loc == 1 ~ 1,\n    (other_loc_num - other_loc_num_over_30) > 0 ~ 1,\n    (multi_loc < 2 & multi_mem_daze == 1) | multi_loc == 1 ~ 1,\n    other_multi_inj == 1 ~ 0.5,\n    other_other_multi_inj == 1 ~ 0.5,\n    TRUE ~ 0))\n```\n:::\n\n\n**2. Identify if a subject has had a moderate or severe TBI prior to baseline**\n(col: moderate_or_severe_tbi). Based on the structure of the questionnaire,\nthis can only be done by looking at LOC (no GCS or details regarding the\nduration of post-traumatic amnesia are present).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# ASSIGN MODERATE / SEVERE TBI ==============================================\notbi01_detailed %<>%\n  mutate(moderate_or_severe_tbi = case_when(\n     (hosp_er_loc > 1 |\n      vehicle_loc > 1 |\n      fall_hit_loc > 1 |\n      violent_hit_loc > 1 |\n      blast_loc > 1 |\n      other_loc_num_over_30 > 0 |\n      multi_loc > 1) ~ 1,\n    other_multi_inj == 1 ~ 0.5,\n    other_other_multi_inj == 1 ~ 0.5,\n     TRUE ~ 0))\n```\n:::\n\n\n**3. Identify which injuries led to an mTBI (col: x_mtbi)**\n\nFirst I convert ages from approximate years to approximate months for\nsubsequent calculations.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# IDENTIFY MTBI AGE =========================================================\notbi01_detailed$blast_age <-\n    otbi01_detailed$blast_age * 12\notbi01_detailed$hosp_er_age <-\n    otbi01_detailed$hosp_er_age * 12\notbi01_detailed$vehicle_age <-\n    otbi01_detailed$vehicle_age * 12\notbi01_detailed$fall_hit_age <-\n    otbi01_detailed$fall_hit_age * 12\notbi01_detailed$violent_hit_age <-\n    otbi01_detailed$violent_hit_age * 12\notbi01_detailed$other_loc_min_age <-\n    otbi01_detailed$other_loc_min_age * 12\notbi01_detailed$multi_effect_end_age <-\n    otbi01_detailed$multi_effect_end_age * 12\n```\n:::\n\n\nI then generate columns indicating which injury types were mTBIs.\n\n\n::: {.cell}\n\n```{.r .cell-code}\notbi01_detailed %<>%\n  mutate(hosp_er_mtbi = case_when(\n    (hosp_er_loc < 2 & hosp_er_mem_daze == 1) | hosp_er_loc == 1 ~ TRUE,\n    TRUE ~ FALSE))\n\notbi01_detailed %<>%\n  mutate(vehicle_mtbi = case_when(\n    (vehicle_loc < 2 & vehicle_mem_daze == 1) | vehicle_loc == 1 ~ TRUE,\n    TRUE ~ FALSE))\n\notbi01_detailed %<>%\n  mutate(fall_hit_mtbi = case_when(\n    (fall_hit_loc < 2 & fall_hit_mem_daze == 1) | fall_hit_loc == 1 ~ TRUE,\n    TRUE ~ FALSE))\n\notbi01_detailed %<>%\n  mutate(violent_hit_mtbi = case_when(\n    (violent_hit_loc < 2 & violent_hit_mem_daze == 1) | violent_hit_loc ==\n        1 ~ TRUE,\n    TRUE ~ FALSE))\n\notbi01_detailed %<>%\n  mutate(blast_mtbi = case_when(\n    (blast_loc < 2 & blast_mem_daze == 1) | blast_loc == 1 ~ TRUE,\n    TRUE ~ FALSE))\n\notbi01_detailed %<>%\n  mutate(other_loc_mtbi = case_when(\n    (other_loc_num - other_loc_num_over_30) > 0 ~ TRUE,\n    TRUE ~ FALSE))\n\notbi01_detailed %<>%\n  mutate(multi_mtbi = case_when(\n    (multi_loc < 2 & multi_mem_daze == 1) | multi_loc == 1 ~ TRUE,\n    TRUE ~ FALSE))\n```\n:::\n\n\n**4. Identify time since each type of mTBI (col: x_mtbi_mpi)**\nThe syntax `case_when(injury_type ~ ...)` means that variables are only\ncalculated if the associated injury type actually was an mTBI.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# IDENTIFY TIME SINCE EACH MTBI =============================================\notbi01_detailed %<>%\n  mutate(hosp_er_mtbi_mpi =\n         case_when(hosp_er_mtbi ~ interview_age - hosp_er_age))\n\notbi01_detailed %<>%\n  mutate(vehicle_mtbi_mpi =\n         case_when(vehicle_mtbi ~ interview_age - vehicle_age))\n\notbi01_detailed %<>%\n  mutate(fall_hit_mtbi_mpi =\n         case_when(fall_hit_mtbi ~ interview_age - fall_hit_age))\n\notbi01_detailed %<>%\n  mutate(violent_hit_mtbi_mpi =\n         case_when(violent_hit_mtbi ~ interview_age - violent_hit_age))\n\notbi01_detailed %<>%\n  mutate(blast_mtbi_mpi =\n         case_when(blast_mtbi ~ interview_age - blast_age))\n\notbi01_detailed %<>%\n  mutate(other_loc_mtbi_mpi =\n         case_when(other_loc_mtbi ~ interview_age - other_loc_min_age))\n\notbi01_detailed %<>%\n  mutate(multi_mtbi_mpi =\n         case_when(multi_mtbi ~ interview_age - multi_effect_end_age))\n```\n:::\n\n\n**5. Time since most recent mTBI (col: latest_mtbi_mpi)**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# IDENTIFY TIME SINCE LAST MTBI =============================================\notbi01_detailed %<>%\n  mutate(latest_mtbi_mpi = pmin(hosp_er_mtbi_mpi,\n                               vehicle_mtbi_mpi,\n                               fall_hit_mtbi_mpi,\n                               violent_hit_mtbi_mpi,\n                               blast_mtbi_mpi,\n                               other_loc_mtbi_mpi,\n                               multi_mtbi_mpi, na.rm = TRUE))\n```\n:::\n\n\nExporting the completed dataset:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# EXPORT DATA ===============================================================\nexport_path <-\n    \"lab-data/abcd/processed/prashanth-proj/data/processed_otbi01_detailed.csv\"\n\nwrite_csv(otbi01_detailed, export_path)\n```\n:::\n\n\n**6. visualize time since most recent mTBI as a histogram**\n\nThe histograms below show the distribution of the time-since-last-mtbi for\neach subject that received an mTBI prior to baseline data collection.\n\nAll subjects:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# VISUALIZE DISTRIBUTION OF TIME SINCE LAST INJURY ==========================\notbi01_detailed <-read_delim(paste0(\n    \"../lab-data/abcd/processed/prashanth-proj/data/\",\n    \"processed_otbi01_detailed.csv\"),\n    guess_max = Inf)\n\nggplot(otbi01_detailed, aes(x=latest_mtbi_mpi)) +\n  geom_histogram(color=\"darkblue\", fill=\"lightblue\") +\n  ggtitle(\"Histogram of times since latest mTBI\") +\n  xlab(\"Months since most recent mTBI\") +\n  ylab(\"Count\") +\n  theme_light(base_size=20)\n```\n\n::: {.cell-output-display}\n![](subjects_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# SAVE FIGURE\nggsave(paste0(\"../lab-data/abcd/processed/prashanth-proj/\",\n              \"figures-and-tables/\",\n              \"all_mtbi_latest_mtbi_histogram.png\"),\n       height=10, width=10)\n```\n:::\n\n\nCropped to children that are in a non-chronic stage post-mTBI (note that the\nnegatives are a result of rounding used when anonymizing ages):\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# PLOT TIME SINCE LAST MTBI: NON-CHRONIC CASES\nggplot(otbi01_detailed, aes(x=latest_mtbi_mpi)) +\n  geom_histogram(color=\"darkblue\", fill=\"lightblue\") +\n  ggtitle(\"Histogram of times since latest mTBI\") +\n  xlim(-5, 5) +\n  xlab(\"Months since most recent mTBI\") +\n  ylab(\"Count\") +\n  theme_light(base_size=20)\n```\n\n::: {.cell-output-display}\n![](subjects_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# SAVE FIGURE\nggsave(paste0(\"../lab-data/abcd/processed/prashanth-proj/figures-and-tables/\",\n              \"all_mtbi_latest_mtbi_histogram_cropped_to_non_chronic.png\"),\n       height=10, width=10)\n```\n:::\n\n\nSome other summarizing:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# TIME SINCE MTBI SUMMARY VALUES ============================================\nsum(otbi01_detailed$latest_mtbi_mpi < 3, na.rm=TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 7\n```\n:::\n\n```{.r .cell-code}\n# 7 children had an mTBI within 3 months of baseline data collection\n\nchronic_subject_mtbi_mpis <- otbi01_detailed %>%\n    select(latest_mtbi_mpi) %>%\n    filter(latest_mtbi_mpi >= 3)\n\nmax(chronic_subject_mtbi_mpis)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 130\n```\n:::\n\n```{.r .cell-code}\nmin(chronic_subject_mtbi_mpis)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 4\n```\n:::\n\n```{.r .cell-code}\nsd(chronic_subject_mtbi_mpis$latest_mtbi_mpi)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 32.0575\n```\n:::\n\n```{.r .cell-code}\nmean(chronic_subject_mtbi_mpis$latest_mtbi_mpi)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 46.06934\n```\n:::\n:::\n\n\n**7. Identify number of mTBIs sustained by each subject (col: mtbi_count)**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# NUMBER OF MTBIS ===========================================================\notbi01_detailed$\n    other_loc_num[\n        is.na(otbi01_detailed$other_loc_num)] <- 0\n\notbi01_detailed$\n    other_loc_num_over_30[\n        is.na(otbi01_detailed$other_loc_num_over_30)] <- 0\n\notbi01_detailed <- otbi01_detailed |>\n    mutate(mtbi_count = (hosp_er_mtbi +\n                         vehicle_mtbi +\n                         fall_hit_mtbi +\n                         violent_hit_mtbi +\n                         blast_mtbi +\n                         (other_loc_num - other_loc_num_over_30) +\n                         multi_mtbi))\n\ntable(otbi01_detailed$mtbi_count)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n    0     1     2     3     4     5 \n11057   306   116     7     1     1 \n```\n:::\n:::\n\n\nOf the 431 subjects with a previous mTBI:\n\n* 306 of them had 1 mTBI\n* 116 of them had 2 mTBIs\n* 7 of them had 7 mTBIs\n* 1 of them had 4 mTBIs\n* 1 of them had 5 mTBIs\n\nEND OF SCRIPT\n\n\n\nA few types of injuries were handled differently from the rest in the above code:\n\n* for `other_loc`, the questionnaire asked for a total number of injuries with LOC as well as a total number of injuries with LOC above 30 minutes.\n    * If their difference was above 0, they were labeled as having had an mTBI.\n* for `other_multi` and `other_other_multi`, insufficient information was provided to determine the severity of the associated injuries.\n\nFor my analyses, I consider 3 months to be the threshold at which an mTBI patient enters a chronic stage post-injury.\nThe subject list was then defined in the following code:\n\n\n\nSTART OF SCRIPT\n\n**Script location**:\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"subtyping-mtbi/abcd/get_baseline_mtbi_subjects.Rmd\"\n```\n:::\n:::\n\n\nExport chronic-stage mTBI subject list:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\n\n# IMPORT DATA ===============================================================\nabcd_otbi01 <-read_delim(paste0(\n    \"lab-data/abcd/processed/prashanth-proj/data/\",\n    \"abcd_otbi01_detailed.csv\"),\n    guess_max = Inf)\n```\n:::\nExtract subjects at a chronic stage post-mTBI:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# SUBSET TO CHRONIC STAGE POST-MTBI =========================================\nbaseline_mtbi_subjects <- abcd_otbi01 |>\n  filter(mtbi == 1 & latest_mtbi_mpi >= 3) |>\n  select(subjectkey)\n\noutput_path <- \"lab-data/abcd/processed/prashanth-proj/data/\"\n\nwrite_csv(baseline_mtbi_subjects,\n          paste0(output_path, \"baseline_chronic_mtbi_subjects.csv\"))\n```\n:::\n\nEND OF SCRIPT\n\n\n## Some participant demographics\n\n## Handling twins\n\n## Identifying matched and non-matched control groups\n",
    "supporting": [
      "subjects_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}