# Cluster analysis

One of the most effective and commonly used approaches for identifying subtypes of items in any context is cluster analysis. In this chapter, I outline some basics of cluster analysis and how clustering has been applied to mild traumatic brain injury.

## The basics of clustering

### Distance

Identifying appropriate distance measures can be one of the most challenging parts of a cluster analysis pipeline.

Normalization prior to similarity matrix generation is only important for multidimensional input matrices. 

In the SNF analyses ahead I use the following distance measures:
* standard normalization + euclidean for multidimensional continuous matrices (like subcortical volumes of many regions)


## Commonly clustering techniques


## Clustering applied to mTBI {#sec-mtbi-subtyping-literature}



## Similarity network fusion

Similarity network fusion (SNF), developed by Wang et al. in 2014 @W9Z4CA2R#Wang_Etal_2014, is an example of such a technique which works by first constructing similarity pairwise similarity matrices of all observations for each data type and then merging those matrices into a single network in a way that captures the full spectrum of the underlying data.

Advances in technology have facilitated the collection of massive and diverse datasets.
 To harness the full potential of these datasets for pattern detection, prediction, and decision-making, techniques to effectively integrate diverse types of data are necessary.

The most basic form of data-integration is to simply normalize and concatenate all available data types prior to analysis.
This approach is known to reduce the signal-to-noise ratio of each individual data type [@W9Z4CA2R#Wang_Etal_2014], which is a serious concern in the context of biological data that is already very noisy to begin with.
The authors of SNF also note that attempting to enhance signal by only including a pre-selected subset of data measures (features) can result in biased analyses.


Analysis of each data type prior to combination can be difficult when the results of the independent analyses don't agree with each other [@W9Z4CA2R#Wang_Etal_2014]. Circumventing this issue with consensus clustering (clustering based on the agreement of multiple different clustering algorithms) can result in the loss of valuable complementary information (i.e., the information that is not shared across data types), which is somewhat antithetical to the purpose of integrating diverse data-types in the first place.


The core procedure associated with SNF analyses involves the following steps:

1.  Construct a similarity matrix for each pair of samples for each available data type
2.  Fuse the similarity matrices using an iterative, nonlinear method (SNF)

User-defined parameters of the pipeline include:

-   The data types to include

-   The similarity measure to use for each data type

-   Hyperparameters related to the fusion step (though the original SNF paper demonstrates strong robustness

The topic of feature selection (determining which variables to include) is not given much attention in the original description of the SNF pipeline. Though feature selection is known to be important in traditional cluster analysis due to the sensitivity of the algorithms to high-dimensionality,



## Spectral clustering


## Cluster analysis evaluation


### Cluster tendency

Will not examine the Hopkins statistic for cluster tendency - "The relatively high value for H in this single-cluster case is due to a comparison of the structure of this data set so uniformly distributed random numbers, Le., data intended to be completely unstructured. With unstructured data as a comparison, virtually any structure in the test data would lead to rejection of the null hypothesis whether the data are clustered or not" @CDGF5NQL#Lawson_Jurs_2002. However even such a variation of the Hopkins statistic would not be so interesting, and would likely be expected - demographic data is random noise.

Whether or not the clusters are randomly distributed. This is challenging in the context of biomedical data - we do not expect the clusters to be randomly distributed by default (the demographic composition of any given country is far from random). In the context of mTBI, there are many facets of heterogeneity that would be interesting to examine:

-   Heterogeneity of children with mTBI vs. those without

    -   **Identifying the risk-of-sustaining-mtbi groups**: of all the children without a history of mTBI at baseline, is there a difference between the clustering of those that will develop an mTBI later on in the study and those who will not?

    -   **Identifying the types of mTBI patients**: how does the heterogeneity of those who have mTBIs differ from the heterogeneity of those who don't have an mTBI? (Contrasted with the previous bullet point, this will help us learn more about the clusters that are formed BECAUSE of the mTBI and not because of being at a higher risk of mTBI)

        -   **Identifying the types of mTBI outcomes:**

            -   purely examining the clusters of patients using PPCS as the only input variable

            -   can contrast mTBI PPCS vs. non-mTBI PPCS (though in that case, it's not quite a PPCS)


```{=tex}
\begin{equation}
  f\left(k\right) = \binom{n}{k} p^k\left(1-p\right)^{n-k}
  (\#eq:binom)
\end{equation}
```

You may refer to using `\@ref(eq:binom)`, like see Equation \@ref(eq:binom).


## Subtyping mTBI {#sec-subtypingmtbi}

In this section, I outline subtypes of mTBI that have been defined in previous studies. The material in this section comes from a larger search as part of a systematic review on the topic.

### The problem



### Templates

#### Narrative template

* Participant selection:
    * Participants were
    * Excluded children
    * Included children
* Data collection: 
    * Timepoints: 
    * Variables: 
* Data pre-processing: 
* Unsupervised learning: 
* Within clusterings cluster characterization:
* Across clusterings characterization:
* Supervised learning: 

#### Rough extraction template

* Participants:
* Age on injury:
* Age on data collection:
* Time between injury and data collection:
* Concussion definition:
* Exclusion criteria: 
* Clustering method:
    * algorithm:
    * number of clusters:
* Inputs:
* Clustering 1:
    * inputs:
    * clusters:
    * outcomes:
* Primary outcome:
* Additional notes:

### Paediatric subtyping studies

The search yielded the following paediatric studies:

* Alsaheen et al., 2021@52HPU6UC##Alsalaheen_Etal_2021
* Brustman et al., 2022@ZIMIRJSM##Brustman_Etal_2022
* Kamins et al., 2021@ZH7CUDIV##Kamins_Etal_2021
* Maietta et al., 2022@P96LF8PQ##Maietta_Etal_2022
* Yeates et al., 2019@DCC2L9PL##Yeates_Etal_2019

#### Yeates et al., 2019

**Derivation and initial validation of clinical phenotypes of children presenting with concussion acutely in the Emergency Department: Latent class analysis of a multicentre, prospective cohort, observational study**


##### Narrative

* Participant selection:
    * Participants were 8-18 yo children from 5P 
    * Excluded children for variety of reasons including missing data
    * Included children for mTBI
* Data collection: 
    * Data collection on variety of tests at acute (<48 hrs), 4 weeks, 12 weeks
* Data pre-processing: Collected data split into 3 domains (pre-injury history, clinical presentation, acute parent-rated symptoms)
* Unsupervised learning: LCA conducted to identify clusters of each domain separately
* Within clusterings cluster characterization:
    * Described clusters by proportions of low/medium/high values of the input variables
    * Membership in each cluster was associated with PPCS risk at follow-up timepoints
* Across clusterings characterization:
    * Membership in the different clusters were significantly associated using Cramer's V
    * Created 'phenotypes' based on common patterns of membership across the three LCAs and examined risk of PPCS for combinations of 8-12yo/13-18yo and male/female 
        * note that a theoretical maximum of 4*4*7 (permutations of membership across the LCAs) 'phenotypes' exist in this framework
* Supervised learning: 
    * multivariate regression using age, sex, and group membership was effective at predicting PPCS

##### Rough extraction

* n: 2323 8-18 year old children from the 5P cohort
* Age on injury: 8-18 years old
* Age on data collection: 8-18 years old
* Time between injury and data collection: < 48 hours - 12 weeks
* Concussion definition: "Brain injury stemming from a direct blow to the head, face, neck, or elsewhere on the body with force transmitted to the head, and resulting in 1 or more symptoms in 1 or more of the following domains: somatic, cognitive, emotional or behavioral, or sleep"
* Exclusion criteria: 
    * Glasgow Coma Scale score < 14
    * structural abnormality on neuroimaging (if performed)
    * neurosurgical intervention
    * intubation or intensive care unit admission
    * multisystem injury requiring hospitalization
    * procedural sedation
    * severe preexisting neurological developmental delay
    * intoxication
    * absence of trauma as primary event
    * previously enrolled in the same study
    * insurmountable language barrier
    * inability to follow-up by telephone or email
* Clustering method:
    * algorithm: latent class analysis
    * number of clusters: 'multiple relevant statistics, theoretical plausibility, and interpretability of solutions with consecutively increasing number of groups'
* Inputs:
    * Acute Concussion Evaluation (ACE; completed within 48 hrs)
    * Post-Concussion Symptom Inventory (PCSI; completed within 48 hrs and followed-up at 4-weeks and 12-weeks)
    * Standardized Assessment of Concussion (SAC; completed within 48 hrs)
    * Balance Error Scoring System (BESS; completed within 48 hrs)
    * Child-Sport Concussion Assessent Tool-3rd Edition (Child-SCAT3; completed within 48 hrs)
* Clustering 1:
    * premorbid history
    * inputs:
        * previous concussion
        * prior concussion symptom duration > 1 week
        * migraine
        * learning disability
        * anxiety
        * depression
    * clusters:
        * cluster 1 (78%):
            * low probability of any pre-injury risk factor
        * cluster 2 (13%):
            * high probability of previous concussion with symptoms > 1 week
        * cluster 3 (7%):
            * high probability of pre-injury anxiety
            * modest probability of pre-injury migraine
            * modest probability of learning problems
            * modest probability of depression
        * cluster 4 (2%):
            * high probability of previous concussion with persistent symptoms
            * high probability of pre-injury anxiety
            * moderate probabilities of other pre-injury factors
    * outcomes:
        * membership significantly associated with PPCS risk at 4-weeks and 12-weeks
* Clustering 2: 
    * clinical presentation on examination
    * inputs:
        * loc
        * dazed and stunned
        * answers slowly
        * forgets recent information
        * SAC orientation score <4*
        * SAC normalized total score <0.11*
        * BESS tandem stance ## of errors >=4 or physically unable to do test
    * clusters:
        * cluster 1 (50):
            * low probability of any clinical findings on examination
        * cluster 2 (23):
            * moderate to high probability of being dazed
            * moderate to high probability of answering questions slowly
            * moderate to high probability of being forgetful
        * cluster 3 (17):
            * moderate to high probability of being dazed
            * moderate to high probability of answering questions slowly
            * moderate to high probability of being forgetful
            * elevated probabilities of deficits on objective tests of cognition and balance
            * moderate probability of LOC
        * cluster 4 (11):
            * high probability of deficits on objective tests of cognition and balance
            * low probabilities of impaired mental status
    * outcomes:
        * membership significantly associated with PPCS risk at 4-weeks
* Clustering 3: 
    * acute parent-rated symptoms
    * inputs
        * headache
        * nausea
        * balance
        * dizziness
        * clumsy
        * vision problems
        * sensitivity to light
        * sensitivity to noise
        * drowsy
        * fatigure
        * irritability
        * mental fog
        * difficulty concentrating
        * difficulty remembering
        * confused
        * answers more slowly
    * clusters:
        * cluster 1:
            * high probability of all symptoms
        * cluster 2:
            * high probability of headache
            * high probability of dizziness
            * high probability of drowsiness
            * high probability of fatigue
            * high probability of mental fogginess
            * high probability of poor concentration
            * high probability of problems remembering
            * high probability of thinking slowly
        * cluster 3:
            * high probability of headache
            * high probability of nausea
            * high probability of drowsiness
            * high probability of fatigue
            * no cognitive impairments of cluster 2
        * cluster 4:
            * high probabilities of physical and fatigue symptoms
            * low probabilities of cognitive symptoms
        * cluster 5:
            * high probability of headache
        * cluster 6:
            * high probability of headache
            * high probability of nausea
            * high probability of drowsiness
            * high probability of fatigue
            * high probability of balance problems
            * high probability of dizziness
        * cluster 7:
            * high probability of headache
            * high probability of dizziness
    * outcomes:
        * membership significantly associated with PPCS risk at 4-weeks and 12-weeks
* Primary outcome:
    * PPCS (defined as persistence over 4-weeks of at least 3 symptoms relative to baseline; evaluated at 4-weeks and 12-weeks)
* Additional notes:
    * sample collected from original 5P study
    * children needed >= 80% of all variables for inclusion
    * clustering was not used to predict specific symptoms, but rather the presence or absence of PPCS
    * sex and age were included *a priori* as additional predictors for supervised learning due to their known prognostic significance
    * **may need to request the study data to better understand the demographics of each group**


#### Maietta et al., 2022

**Cognitive profiles following sport-related concussion in high school athletes**

##### Narrative

* Participant selection:
    * Participants were 13-19 yo 1817 high-school athletes
* Data collection: 
    * Timepoints: < 30 days
    * Variables: ImPACT assessment (age, education, psychiatric history, medical history, self-reported concussive injury date, neurodevelopmental disorder history, adhd, learning disorders, battery of cognitive tests, 22-item PCSS)
* Data pre-processing: 
* Unsupervised learning: 
    * ward's method with confirmation using K-means interative partitioning cluster analysis and discriminant function analysis
* Within clusterings cluster characterization:
* Across clusterings characterization:
* Supervised learning: 


##### Rough extraction

* Participants:
* Age on injury:
* Age on data collection:
* Time between injury and data collection:
* Concussion definition:
* Exclusion criteria: 
* Clustering method:
    * algorithm:
    * number of clusters:
* Inputs:
* Clustering 1:
    * inputs:
    * clusters:
    * outcomes:
* Primary outcome:
* Additional notes:
