# Mild traumatic brain injury

This chapter is largely taken from my MSc thesis. 

## Definition and Epidemiology

Traumatic brain injuries (TBIs) refer to any injury in which an external force applied to the head results in structural injury or physiological brain disruption @WYA25C6X#Blennow_Etal_2016. These injuries are typically categorized by severity as being mild, moderate, or severe. The precise definitions for TBI and its subcategories of severity vary across sources based on the injury’s specific causes and symptoms @HUJPHQZP#NationalAcademiesOfSciences_Etal_2019.

The ambiguity of defining TBI is particularly prominent for mild traumatic brain injuries (mTBIs) @D6IUMSZT#Roozenbeek_Maas_Menon_2013. One common definition that is used to categorize a TBI as mild by sources such as the World Health Organization (WHO)’s Collaborating Centre for Neurotrauma Task Force @A5I6ILGT#Holm_Etal_2005 and the United States Department of Veterans Affairs @UDLZ7Z3L#ManagementOfConcussion/MtbiWorkingGroup_2009 is that the injury must reveal no abnormalities on traditional methods of structural brain imaging, no more than 30 minutes of lost consciousness following the impact, no more than 24 hours of altered mental state or confusion, and a score above 13 on the 15-point Glasgow Coma Scale (GCS) @WYA25C6X#Blennow_Etal_2016. The GCS is a clinical tool that examines a patient’s eye-opening, verbal, and motor responses to commands and physical stimulation to determine their precise level of consciousness along the spectrum of completely non-responsive to completely responsive @7KLH4QUR#Teasdale_Jennett_1974.

The term mTBI is also commonly used interchangeably with the term concussion [@WYA25C6X#Blennow_Etal_2016; @Y2QTXNW5#Gardner_Yaffe_2015], however, some organizations believe the term concussion should only be used to describe a specific form of (typically sports-related) mTBI, or to describe a distinct injury that shares some overlap in causes and outcomes as mTBI @5G2PR4KI#Mccrory_Etal_2013. Others also believe the ambiguity associated with the term concussion is sufficient reason to not use it at all @3YFFNGMC#Sharp_Jenkins_2015.


A recent article published in JAMA insights outlined the state of clinical post-mTBI care and management as of 2019 @Q4UGLDWH#Silverberg_Duhaime_Iaccarino_2019. Potentially as a result of the complexity of the condition, there are currently no therapeutic interventions that are known to mitigate the consequences of mTBI; the resolution of symptoms is the primary metric used to determine the pace at which an mTBI patient may resume tasks of varying cognitive and physical demand [@JJUC3QKT#Greco_Etal_2019; @Q4UGLDWH#Silverberg_Duhaime_Iaccarino_2019]. Stricter caution is used in cases where there is higher risk of sustaining a subsequent concussion or injury, such as for athletes, military personnel, and the elderly.

The high prevalence of mTBIs, their potentially serious and persistent outcomes, and their lack of effective treatments and therapies position them as a leading global health concern and an important priority for research.


## Outcomes and heterogeneity

Though mTBIs are the least harmful form of TBI, they are thought to make up between 80-90% of all TBIs @WYA25C6X#Blennow_Etal_2016 and afflict approximately 600 per 100,000 people every year @Y2QTXNW5#Gardner_Yaffe_2015. A study by Boak et al. reported that upwards of 15% of children in Ontario sustain an mTBI each year [@LUZM3UW8#Boak_Etal_2020]. While the majority of mTBIs result in transient, self-limiting symptoms which resolve within 7-10 days @5G2PR4KI#Mccrory_Etal_2013, approximately 10-20% of all mTBIs can lead to a wide range of neurological, cognitive, and behavioural symptoms including depression @HANRRY7M#Hellewell_Etal_2020, anxiety @HM64GAQX#Mcinnes_Etal_2017, headaches @NVQABINL#Dwyer_2018, dizziness @PVZTPZ25#Fife_Kalra_2015, fatigue, increased irritability @HM64GAQX#Mcinnes_Etal_2017, difficulties in concentration @EYW3TTDU#Quinn_Etal_2018, impairments in memory, abnormal sleeping patterns @47IE7B4K#Mollayeva_Mollayeva_Colantonio_2016, emotional volatility @IT86IGZ4#VanDerHorn_Etal_2016, stress intolerance @FBTHPL96#Vasterling_Jacob_Rasmusson_2018, decreased reaction times @A73WP4L8#DannaDosSantos_Etal_2018, and visual tracking ability @A73WP4L8#DannaDosSantos_Etal_2018, which may take months or years to resolve, or may never resolve at all [@WYA25C6X#Blennow_Etal_2016; @EYW3TTDU#Quinn_Etal_2018; @A73WP4L8#DannaDosSantos_Etal_2018]. Patients with mTBI have also been identified as having higher incidence rates of conditions such as dementia @Y2QTXNW5#Gardner_Yaffe_2015 and chronic traumatic encephalopathy @D3E93EJA#LuckeWold_Etal_2014. In approximately 25% of cases [@5YF45S66#Fried_Etal_2022], symptoms following mTBI persist for several months or years after the initial trauma. 

Understanding the heterogeneity of mTBI outcomes is a major challenge in the field. Our ability to predict what types of symptoms a patient will have, how long those symptoms may persist for, and what treatments will be most beneficial to them is still limited. Previous studies have made progress on this topic by identifying several biological, social, and psychological factors that explain at least some of the heterogeneity of mTBI outcome severity, duration, and type. 

Some of those previous studies attempted to further parse the heterogeneity of mTBI by using those factors to define subtypes of mTBI patients (discussed more in (@sec-subtypingmtbi).


### Sex differences

One notable component of the heterogeneity of mTBI is the differential outcomes experienced by males and females. A search of the PubMed database for review papers in the last 10 years that have examined how sex influences clinical mTBI outcomes (search: “sex” and (“mTBI” or “mild traumatic brain injury”)) identified @5G2PR4KI#Mccrory_Etal_2013 reviews which found that females generally had worse outcomes following mTBI, [@7DYTT5MG#Iverson_Etal_2017; @2TFX9MUL#Harmon_Etal_2013; @LJ8Y47QV#Cogan_Mccaughey_Scholten_2020; @47IE7B4K#Mollayeva_Mollayeva_Colantonio_2016; @4GKWK8GU#Blume_2015; @X2TZVXQE#Mccorkle_Barson_Raghupathi_2021], 1 review which found that males generally had worse outcomes @UUTLINCB#YengoKahn_Etal_2016, two reviews reporting mixed outcomes [@XZITM964#Cancelliere_Donovan_Cassidy_2016; @VI2ZX9FW#Merritt_Padgett_Jak_2019], and two reviews reporting no conclusive differences between the sexes [@HANRRY7M#Hellewell_Etal_2020; @M6CXBBDD#Noble_Hesdorffer_2013]. 

Though clinical studies tend to suggest that females experience poorer outcomes than males, a recent systematic review by Gupte et al. @N9MZJI73#Gupte_Etal_2019 examining sex differences following TBI of all severities found that in general, the opposite was true for animal studies. This review also found that the proportion of studies which reported a particular type of sex difference seemed to vary considerably with impact severity; among the 12 mTBI studies examined, 25% (n = 4) reported that females had worse outcomes and 17% (n = 2) reported that males had worse outcomes, but among the 31 moderate-severe TBI studies examined, only 10% (n = 3) reported that females had worse outcomes and 55% (n = 17) reported that males had worse outcomes. Whether this pattern was the result of chance due to the small number of mTBI studies or a reflection of a biological interaction effect of impact severity with sex remains to be determined. 

Though there are several studies which suggest that sex can influence outcomes of mTBI, it is not yet clear how or when these differences in outcomes occur. Including sex as a parameter in replicable experimental mTBI studies and examining how it interacts with other study factors will be a necessary component of future work to fully understand the pathophysiology and possible treatments of mTBI.  

Biological, psychological, and social variables have been found to associate with mTBI outcome severity, type, and duration. 


## Mechanisms of damage

Pathological sequelae of TBI are commonly split into primary and secondary damage phases @CH85VK2U#Fehily_Fitzgerald_2017. The primary damage phase refers to the immediate effects of the mechanical disruption of the brain, while the secondary damage phase encompasses longer lasting cellular and molecular mechanisms that are initiated by the consequences of the primary damage @NKTETIGJ#Walker_Tesco_2013. 


### Primary biomechanical mechanisms of damage

Though the mechanisms by which trauma to the head can result in injury to the brain are not completely known, novel advances in our understanding of the contributing biomechanical, cellular, and molecular processes are continuously being made.

Compared to TBIs of higher severities, the major effects of the primary damage phase of mTBIs are less defined by direct trauma to the brain and more defined by the straining and shearing forces generated by the rapid changes in the brain’s rotational and linear acceleration @7RULIAZQ#Cassidy_Etal_2004. These extreme changes in acceleration generate intracranial pressure gradients that permeate through the brain @WYA25C6X#Blennow_Etal_2016 and cause irreversible damage to critical brain structures @WYA25C6X#Blennow_Etal_2016.


### Secondary cellular and molecular mechanisms of damage

The initial mechanical forces of an mTBI can trigger secondary cellular and molecular processes that perpetuate brain degeneration or hinder brain recovery for years after the trauma. This secondary damage is composed of several complex mechanisms whose interactions are the subject of current investigations, and include oxidative stress @CH85VK2U#Fehily_Fitzgerald_2017, mitochondrial disruption @RJDEI9ZN#Kim_Etal_2017, inflammation @73E47CYI#Mckee_Lukens_2016, axon degeneration @ZF5C7LGJ#JohnsonVe_Etal_2018, and cellular apoptosis [@BCXQVLQW#Ng_Lee_2019; @J2CLZZVD#Tashlykov_Etal_2009].

TBIs can cause damage through the transient disruption of cell membranes, which can create imbalances in intra- and extra-cellular concentrations of ions and neurotransmitters @DA8K63LI#Prins_Etal_2013. Acutely after an injury, neuronal presynaptic terminals can aberrantly release glutamate, resulting in disrupted neuronal communication across the brain. The excessive extracellular concentrations of glutamate are exacerbated by the widespread dysfunction of glutamate transporters in the acute phase of the injury @2ZBIXSPU#Landeghem_Etal_2006. Potassium can also be released by neurons in a manner proportionate to the severity of the trauma @PPI6QJAQ#Katayama_Etal_1990, which can further exacerbate the disruptions in inter-neuronal signaling. 

TBIs can also result in abnormal buildups of intracellular calcium ions, which can in turn trigger excessive mitochondrial calcium uptake and subsequent impaired mitochondrial function @DA8K63LI#Prins_Etal_2013. 

Another consequence of TBI is the so-called ‘post-TBI energy crisis’ @TPI6RH54#Prins_Etal_2013, which describes the significant drop in brain glucose uptake following injury. The mechanisms by which glucose uptake is inhibited following TBI is not known but could be attributed to any combination of impaired glucose transporter function at the blood brain barrier, impaired levels of cerebral blood flow, and cellular impairments in metabolic processing.

Overproduction of free radicals and oxidative stress as a result of intracellular calcium accumulation @CH85VK2U#Fehily_Fitzgerald_2017 is another component by which TBIs are known to damage the brain @DA8K63LI#Prins_Etal_2013. While reactive oxygen species (ROS) are a normal product of the brain’s metabolic functions, TBI can result in ROS levels that are too high for homeostatic ROS scavenging molecules to mitigate @7PHGHQX8#OConnell_LittletonKearney_2013. The overabundance of ROS can go on to exacerbate brain damage by altering cell membrane permeability @XT5I3GSJ#Hall_Etal_1993, disrupting DNA repair @JW87P7FD#Satchell_Etal_2003, and causing mitochondrial dysfunction @SIHJNIZ6#Khatri_Etal_2018 among other harmful consequences.

The activation of glial cells is also recognized to be a major mechanism by which inflammation, degeneration, and repair are regulated following mTBI. At rest, astrocytes play important roles in establishing homeostatic conditions in the central nervous system, supporting neuronal function, and maintaining the integrity of the blood-brain barrier @LMG7842Z#Risau_Wolburg_1990. After a mild traumatic brain injury, astrocytes adjust their morphology and gene expression signature (a reaction known as astrogliosis @KM6NHV77#Sofroniew_Vinters_2010), proliferate and migrate towards damaged structures @ZR4NE5KW#Robel_Etal_2011, buffer ionic imbalances through cellular pumps and channels, and secrete both damaging and reparative cytokines and chemokines @HI6FTFSY#Karve_Taylor_Crack_2016. In more severe injury contexts, astrocytes are also capable of forming scars that protect healthy tissue from the inflammatory molecules at the sites of damaged structures @MB6CXGWP#Silver_Miller_2004.

Microglia, the resident immune cells of the central nervous system, also have a complex role in the pathophysiology of mTBI. Under homeostatic conditions, microglia constantly survey their surrounding area for signs of trauma or pathogenic invasion using highly motile processes, which, upon detection, can induce a heterogeneous set of contextually specific and morphologically, transcriptionally, and functionally activated microglial states @S6SWYJWT#Masuda_Etal_2020. Similar to astrocytes, microglia have both damaging and reparative functions when activated following mTBI. Reparative functions of microglia include phagocytosing cellular debris and producing scavenger receptors, anti-inflammatory cytokines, and growth factors, while damaging functions include producing pro-inflammatory cytokines and excessively phagocytosing tissues that are healthy or capable of being repaired [@HI6FTFSY#Karve_Taylor_Crack_2016; @9RJ86YQM#Loane_Kumar_2016; @9QX6LXNS#Donat_Etal_2017].

The complete interplay and ordering of the previously outlined mechanisms are complex and likely dependent on the specific combination of patient and injury factors. However, in addition to the primary mechanical forces described in the previous subsection, many of these secondary cellular and molecular processes play a significant role in mediating a major correlate of post-mTBI impairment: damage or disruption to the brain’s white matter. 


### White matter vulnerability to mTBI

White matter regions of the brain, which are structures composed mainly of myelinated axons that primarily function to relay information between different brain regions, are known to be highly susceptible to both primary mechanical and secondary molecular damage processes following mTBI [@KQEZAQVC#Mckee_Daneshvar_2015; @7NTF3F59#Armstrong_Etal_2016; @QA2QRD3Q#Filley_Kelly_2018].

Although all cells and structures in the brain are affected to some degree by the mechanical forces associated with mTBI, white matter structures are particularly vulnerable to primary damage due to their high composition of long neuronal axons @KQEZAQVC#Mckee_Daneshvar_2015. Rather than the overt degeneration of white matter that may be more commonly seen in severe forms of TBI, mTBI often results in axon damage and axon-myelin pathology [@7NTF3F59#Armstrong_Etal_2016]. Diffuse axonal injury (DAI), the most common form of axonal injury associated with mild injuries, is initiated by the mechanical forces of the injury and characterized by widespread patterns of damaged axons interspersed among intact ones, typically in midline white matter tracts such as the corpus callosum and internal capsules [@ZF5C7LGJ#JohnsonVe_Etal_2018; @7NTF3F59#Armstrong_Etal_2016]. In cases of mTBI, axonal damage has been observed to occur without surrounding vascular damage, suggesting that axons are substantially more susceptible to these injuries than blood vessels @7NTF3F59#Armstrong_Etal_2016.

Both the mechanical action of the impact as well as the byproducts of structures that were damaged by that action can go on to initiate secondary cellular and molecular processes of brain damage @BCXQVLQW#Ng_Lee_2019. 

Though the precise mechanisms by which secondary molecular and cellular damage and repair processes affect white matter following mTBI are not fully understood, some contributing processes have been identified. For mild brain injuries, those mechanical forces may cause axonal cytoskeleton disruption or imbalances of intra-axonal ion concentrations that primarily lead to swelling and sometimes secondary axonal disconnection. Another secondary mechanism by which white matter damage can occur is by degeneration or loss of oligodendrocyte lineage cells, which can subsequently lead to the disruption or loss of myelin @7NTF3F59#Armstrong_Etal_2016. This disruption may be initiated by a variety of mechanisms after head trauma, including glutamate excitotoxicity @KX4JXG6L#Salter_Fern_2005, oxidative stress @8TTGFM7W#Husain_Juurlink_1995, and inflammatory consequences of activated astrocytes [@HI6FTFSY#Karve_Taylor_Crack_2016; @2X7S8SSN#Johnstone_Etal_2013] and microglia [@HI6FTFSY#Karve_Taylor_Crack_2016; @PSDMBN45#Shi_Etal_2015; @GFSLRGJ7#Izzy_Etal_2019]. 

The general progression of white matter damage following mTBI is thought to typically begin with DAI from the primary impact causing unmyelinated axon fibers to degenerate and myelinated axon fibers to become damaged at the nodes of Ranvier @7NTF3F59#Armstrong_Etal_2016. Swelling and atrophy of distal axon segments following initial damage then further disrupts surrounding myelin. Secondary processes can then initiate demyelination of intact axons and additional axonal damage, again beginning from the nodes of Ranvier [@7NTF3F59#Armstrong_Etal_2016; @QA2QRD3Q#Filley_Kelly_2018]. Axons that are sufficiently damaged enough may become irreversibly disconnected. 

Myelin sheaths, the insulating layer of axons, are part of oligodendrocytes. Myelin plays a major role in axon vulnerability to damage: unmyelinated axons are especially susceptible to traumatic axonal injury. As well, the axon initial segment, an unmyelinated region of the beginning of an axon, is often the initial site of axon cleavage (axotomy) following traumatic axonal injury. Myelin debris is also enough to trigger the activation of microglia and infiltrating macrophages @ELTUYPD2#Clarner_Etal_2012, which may play a significant role in propagating secondary damage following mTBI. Myelin debris has also been shown to inhibit the differentiation of oligodendrocyte precursor cells, which is a necessary process for myelin regeneration [@LAI7X2FI#Kotter_Etal_2006; @3NXTL37E#Baer_Etal_2009]. 

Importantly, damage to white matter structures following mTBI has been strongly associated with the cognitive, neurological, and behavioural impairments that can follow the injury [@7NTF3F59#Armstrong_Etal_2016; @PSDMBN45#Shi_Etal_2015; @KM28TM9B#Hellstrøm_Etal_2017], making them an important candidate target for the development of mTBI therapies and biomarkers. 


## Neuroimaging {#sec-neuroimaging}

The subtle white matter damage that follows mTBI is most commonly detected (in both clinical and preclinical contexts) through neuroimaging and histological analysis [@7NTF3F59#Armstrong_Etal_2016]. In the context of living subjects (which is the relevant context for this project), the histological approach to detecting white matter damage is not really applicable. The usage of neuroimaging (particularly MRI) for mTBI diagonosis and prognosis is described in detail in a later chapter in this book (@sec-neuroimaging).

To better detect white matter damage in patients of mTBI, advanced MRI techniques, such as diffusion tensor imaging (DTI), are being increasingly used46. Because white matter has a more fibrous structure than gray matter, the diffusion of water within it is more directional. DTI scans measure the degree of directionality, or fractional anisotropy (FA), of water molecules over the entire brain in 3D units known as voxels. In a study that collected DTI scans of 76 adults that had received an mTBI 1 to 2 weeks prior, the reduction of FA was found to be a predictive measure of long-term outcome57. Other studies have reported both increases58 and decreases59, 60 in post-TBI FA, suggesting that even the type of structural white matter changes that follow a TBI are complex and likely depend on multiple factors. Within white matter tracts that are complex and/or long-range, the accuracy of DTI in detecting abnormalities is still limited46. 
