# Patient subtypes of mTBI

In this section, I outline subtypes of mTBI that have been defined in previous studies. The material in this section comes from a larger search as part of a systematic review on the topic.

## Templates

### Narrative template

* Participant selection:
    * Participants were
    * Excluded children
    * Included children
* Data collection: 
    * Timepoints: 
    * Variables: 
* Data pre-processing: 
* Unsupervised learning: 
* Within clusterings cluster characterization:
* Across clusterings characterization:
* Supervised learning: 

### Rough extraction template

* Participants:
* Age on injury:
* Age on data collection:
* Time between injury and data collection:
* Concussion definition:
* Exclusion criteria: 
* Clustering method:
    * algorithm:
    * number of clusters:
* Inputs:
* Clustering 1:
    * inputs:
    * clusters:
    * outcomes:
* Primary outcome:
* Additional notes:

## Paediatric subtyping studies

The search yielded the following paediatric studies:

* Alsaheen et al., 2021@52HPU6UC#Alsalaheen_Etal_2021
* Brustman et al., 2022@ZIMIRJSM#Brustman_Etal_2022
* Kamins et al., 2021@ZH7CUDIV#Kamins_Etal_2021
* Maietta et al., 2022@P96LF8PQ#Maietta_Etal_2022
* Yeates et al., 2019@DCC2L9PL#Yeates_Etal_2019

### Yeates et al., 2019

**Derivation and initial validation of clinical phenotypes of children presenting with concussion acutely in the Emergency Department: Latent class analysis of a multicentre, prospective cohort, observational study**


#### Narrative

* Participant selection:
    * Participants were 8-18 yo children from 5P 
    * Excluded children for variety of reasons including missing data
    * Included children for mTBI
* Data collection: 
    * Data collection on variety of tests at acute (<48 hrs), 4 weeks, 12 weeks
* Data pre-processing: Collected data split into 3 domains (pre-injury history, clinical presentation, acute parent-rated symptoms)
* Unsupervised learning: LCA conducted to identify clusters of each domain separately
* Within clusterings cluster characterization:
    * Described clusters by proportions of low/medium/high values of the input variables
    * Membership in each cluster was associated with PPCS risk at follow-up timepoints
* Across clusterings characterization:
    * Membership in the different clusters were significantly associated using Cramer's V
    * Created 'phenotypes' based on common patterns of membership across the three LCAs and examined risk of PPCS for combinations of 8-12yo/13-18yo and male/female 
        * note that a theoretical maximum of 4*4*7 (permutations of membership across the LCAs) 'phenotypes' exist in this framework
* Supervised learning: 
    * multivariate regression using age, sex, and group membership was effective at predicting PPCS

#### Rough extraction

* n: 2323 8-18 year old children from the 5P cohort
* Age on injury: 8-18 years old
* Age on data collection: 8-18 years old
* Time between injury and data collection: < 48 hours - 12 weeks
* Concussion definition: "Brain injury stemming from a direct blow to the head, face, neck, or elsewhere on the body with force transmitted to the head, and resulting in 1 or more symptoms in 1 or more of the following domains: somatic, cognitive, emotional or behavioral, or sleep"
* Exclusion criteria: 
    * Glasgow Coma Scale score < 14
    * structural abnormality on neuroimaging (if performed)
    * neurosurgical intervention
    * intubation or intensive care unit admission
    * multisystem injury requiring hospitalization
    * procedural sedation
    * severe preexisting neurological developmental delay
    * intoxication
    * absence of trauma as primary event
    * previously enrolled in the same study
    * insurmountable language barrier
    * inability to follow-up by telephone or email
* Clustering method:
    * algorithm: latent class analysis
    * number of clusters: 'multiple relevant statistics, theoretical plausibility, and interpretability of solutions with consecutively increasing number of groups'
* Inputs:
    * Acute Concussion Evaluation (ACE; completed within 48 hrs)
    * Post-Concussion Symptom Inventory (PCSI; completed within 48 hrs and followed-up at 4-weeks and 12-weeks)
    * Standardized Assessment of Concussion (SAC; completed within 48 hrs)
    * Balance Error Scoring System (BESS; completed within 48 hrs)
    * Child-Sport Concussion Assessent Tool-3rd Edition (Child-SCAT3; completed within 48 hrs)
* Clustering 1:
    * premorbid history
    * inputs:
        * previous concussion
        * prior concussion symptom duration > 1 week
        * migraine
        * learning disability
        * anxiety
        * depression
    * clusters:
        * cluster 1 (78%):
            * low probability of any pre-injury risk factor
        * cluster 2 (13%):
            * high probability of previous concussion with symptoms > 1 week
        * cluster 3 (7%):
            * high probability of pre-injury anxiety
            * modest probability of pre-injury migraine
            * modest probability of learning problems
            * modest probability of depression
        * cluster 4 (2%):
            * high probability of previous concussion with persistent symptoms
            * high probability of pre-injury anxiety
            * moderate probabilities of other pre-injury factors
    * outcomes:
        * membership significantly associated with PPCS risk at 4-weeks and 12-weeks
* Clustering 2: 
    * clinical presentation on examination
    * inputs:
        * loc
        * dazed and stunned
        * answers slowly
        * forgets recent information
        * SAC orientation score <4*
        * SAC normalized total score <0.11*
        * BESS tandem stance # of errors >=4 or physically unable to do test
    * clusters:
        * cluster 1 (50):
            * low probability of any clinical findings on examination
        * cluster 2 (23):
            * moderate to high probability of being dazed
            * moderate to high probability of answering questions slowly
            * moderate to high probability of being forgetful
        * cluster 3 (17):
            * moderate to high probability of being dazed
            * moderate to high probability of answering questions slowly
            * moderate to high probability of being forgetful
            * elevated probabilities of deficits on objective tests of cognition and balance
            * moderate probability of LOC
        * cluster 4 (11):
            * high probability of deficits on objective tests of cognition and balance
            * low probabilities of impaired mental status
    * outcomes:
        * membership significantly associated with PPCS risk at 4-weeks
* Clustering 3: 
    * acute parent-rated symptoms
    * inputs
        * headache
        * nausea
        * balance
        * dizziness
        * clumsy
        * vision problems
        * sensitivity to light
        * sensitivity to noise
        * drowsy
        * fatigure
        * irritability
        * mental fog
        * difficulty concentrating
        * difficulty remembering
        * confused
        * answers more slowly
    * clusters:
        * cluster 1:
            * high probability of all symptoms
        * cluster 2:
            * high probability of headache
            * high probability of dizziness
            * high probability of drowsiness
            * high probability of fatigue
            * high probability of mental fogginess
            * high probability of poor concentration
            * high probability of problems remembering
            * high probability of thinking slowly
        * cluster 3:
            * high probability of headache
            * high probability of nausea
            * high probability of drowsiness
            * high probability of fatigue
            * no cognitive impairments of cluster 2
        * cluster 4:
            * high probabilities of physical and fatigue symptoms
            * low probabilities of cognitive symptoms
        * cluster 5:
            * high probability of headache
        * cluster 6:
            * high probability of headache
            * high probability of nausea
            * high probability of drowsiness
            * high probability of fatigue
            * high probability of balance problems
            * high probability of dizziness
        * cluster 7:
            * high probability of headache
            * high probability of dizziness
    * outcomes:
        * membership significantly associated with PPCS risk at 4-weeks and 12-weeks
* Primary outcome:
    * PPCS (defined as persistence over 4-weeks of at least 3 symptoms relative to baseline; evaluated at 4-weeks and 12-weeks)
* Additional notes:
    * sample collected from original 5P study
    * children needed >= 80% of all variables for inclusion
    * clustering was not used to predict specific symptoms, but rather the presence or absence of PPCS
    * sex and age were included *a priori* as additional predictors for supervised learning due to their known prognostic significance
    * **may need to request the study data to better understand the demographics of each group**


### Maietta et al., 2022

**Cognitive profiles following sport-related concussion in high school athletes**

#### Narrative

* Participant selection:
    * Participants were 13-19 yo 1817 high-school athletes
* Data collection: 
    * Timepoints: < 30 days
    * Variables: ImPACT assessment (age, education, psychiatric history, medical history, self-reported concussive injury date, neurodevelopmental disorder history, adhd, learning disorders, battery of cognitive tests, 22-item PCSS)
* Data pre-processing: 
* Unsupervised learning: 
    * ward's method with confirmation using K-means interative partitioning cluster analysis and discriminant function analysis
* Within clusterings cluster characterization:
* Across clusterings characterization:
* Supervised learning: 


#### Rough extraction

* Participants:
* Age on injury:
* Age on data collection:
* Time between injury and data collection:
* Concussion definition:
* Exclusion criteria: 
* Clustering method:
    * algorithm:
    * number of clusters:
* Inputs:
* Clustering 1:
    * inputs:
    * clusters:
    * outcomes:
* Primary outcome:
* Additional notes:
