# Neuroimaging 

## Non-MRI approaches {#sec-neuroimaging}


## MRI approaches

To better detect white matter damage in patients of mTBI, advanced MRI techniques, such as diffusion tensor imaging (DTI), are being increasingly used46. Because white matter has a more fibrous structure than gray matter, the diffusion of water within it is more directional. DTI scans measure the degree of directionality, or fractional anisotropy (FA), of water molecules over the entire brain in 3D units known as voxels. In a study that collected DTI scans of 76 adults that had received an mTBI 1 to 2 weeks prior, the reduction of FA was found to be a predictive measure of long-term outcome57. Other studies have reported both increases58 and decreases59, 60 in post-TBI FA, suggesting that even the type of structural white matter changes that follow a TBI are complex and likely depend on multiple factors. Within white matter tracts that are complex and/or long-range, the accuracy of DTI in detecting abnormalities is still limited46. 
