{
  "hash": "d34208207cfd1c4fba115a7acb9fd8c5",
  "result": {
    "markdown": "# Identifying subjects\n\nThe TBI information of the ABCD dataset is split across a few files:\n\n* `abcd_otbi01.txt`: the raw, modified Ohio State TBI screen given at baseline\n* `abcd_tbi01.txt`: summary scores of abcd_otbi01.txt\n* `abcd_lpohstbi01.txt`: all longitudinal follow-ups of the baseline screen\n* `abcd_lsstbi01.txt`: summary scores of abcd_lpohstbi01.txt\n\nAll information required for identifying children at a chronic stage following mTBI as of baseline data collection is available in the `abcd_otbi01.txt` file.\n\n\n## Renaming the mTBI data\n\nThe provided variable names are non-descriptive.\nThe code below was used for renaming the abcd_otbi01.txt file.\n\n\n**Script location**:\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"wheeler-lab/abcd/prashanth-proj/rename-data/rename_abcd_otbi01.Rmd\"\n```\n:::\n:::\n\n**Renaming abcd_otbi01 columns**:\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nabcd_otbi01 <- read_delim(\"lab-data/abcd/4.0/trauma/abcd_otbi01.txt\")[-1, ]\n\nabcd_otbi01_renamed <- abcd_otbi01 %>%\n  rename(# ever hospitalized/ER for head/neck injury?\n         hosp_er_inj = tbi_1,\n\n         # if LOC, how long?\n         hosp_er_loc = tbi_1b,\n\n         # were they dazed or have memory gap?\n         hosp_er_mem_daze = tbi_1c,\n\n         # how old were they?\n         hosp_er_age = tbi_1d,\n\n         # ever injured in a vehicle accident?\n         vehicle_inj = tbi_2,\n\n         # if LOC, how long?\n         vehicle_loc = tbi_2b,\n\n         # were they dazed or have memory gap?\n         vehicle_mem_daze = tbi_2c,\n\n         # how old were they?\n         vehicle_age = tbi_2d,\n\n         # ever injured head/neck from fall or hit?\n         fall_hit_inj = tbi_3,\n\n         # if LOC, how long?\n         fall_hit_loc = tbi_3b,\n\n         # were they dazed or have memory gap?\n         fall_hit_mem_daze = tbi_3c,\n\n         # how old were they?\n         fall_hit_age = tbi_3d,\n\n         # ever injure head/neck from violence?\n         violent_hit_inj = tbi_4,\n\n         # if LOC, how long?\n         violent_hit_loc = tbi_4b,\n\n         # were they dazed or have memory gap?\n         violent_hit_mem_daze = tbi_4c,\n\n         # how old were they?\n         violent_hit_age = tbi_4d,\n\n         # ever injure head or neck from blast?\n         blast_inj = tbi_5,\n\n         # if LOC, how long?\n         blast_loc = tbi_5b,\n\n         # were they dazed or have memory gap?\n         blast_mem_daze = tbi_5c,\n\n         # how old were they?\n         blast_age = tbi_5d,\n\n         # any other injuries with LOC?\n         other_loc_inj = tbi_6o,\n\n         # how many more?\n         other_loc_num = tbi_6p,\n\n         # how long was longest LOC?\n         other_loc_max_loc_mins = tbi_6q,\n\n         # how many were >= 30 min?\n         other_loc_num_over_30 = tbi_6r,\n\n         # what was their youngest age?\n         other_loc_min_age = tbi_6s,\n\n         # did they experience a period of multiple head injuries?\n         multi_inj = tbi_7a,\n\n         # if LOC, how long?\n         multi_loc = tbi_7c1,\n\n         # were they dazed or have memory gap?\n         multi_mem_daze = tbl_7c2,\n\n         # at what age did the effects begin?\n         multi_effect_start_age = tbi_7e,\n\n         # at what age did the effects end?\n         multi_effect_end_age = tbi_7f,\n\n         # was there another period of multiple head injuries?\n         other_multi_inj = tbi_7g,\n\n         # what was the typical effect of the injury?\n         other_multi_effect_type = tbi_7i,\n\n         # at what age did these effects start?\n         other_multi_effect_start_age = tbi_7k,\n\n         # at what age did these effects end?\n         other_multi_effect_end_age = tbi_7l,\n\n         # was there another period of multiple head injuries?\n         other_other_multi_inj = tbi_8g,\n\n         # was there another period of multiple head injuries?\n         other_other_multi_effect_type = tbi_8i,\n\n         # at what age did these effects start?\n         other_other_multi_effect_start_age = tbi_8k,\n\n         # at what age did these effects end?\n         other_other_multi_effect_end_age = tbi_8l)\n\nwrite_csv(abcd_otbi01_renamed, \"lab-data/abcd/processed/prashanth_proj/abcd_otbi01_renamed.csv\")\n```\n:::\n\nNote that all variables with the same prefix (or number originally) are referring to the same injury or set of injuries.\n\n\n## Identifying subjects at a chronic stage post-mTBI\n\nTo identify subjects at a chronic stage post-mTBI, two intermediate pieces of information must be calculated from the original dataset:\n\n* identifying which head injuries were mTBIs\n* identifying the time since the most recent mTBI\n\nThe structure of the Ohio State TBI screen as used for ABCD data collection was not completely compatible with the most commonly used definition of mTBI @blennow_traumatic_2016:\n\nAt least one of the following:\n\n* Any period of loss of consciousness\n* Any loss of memory\n* Any alteration in mental state\n* Focal neurological deficits\n\nbut where the severity does not exceed:\n\n* LOC over 30 minutes\n* A Glasgow Coma Scale score below 13\n* Post-traumatic amnesia (PTA) greater than 24 hours\n\nA few aspects of the data collection process in the ABCD study precluded the usage of this definition:\n\n* No information was collected regarding the GCS\n* Feeling dazed and PTA were combined into a single variable, making it unclear which combination of symptoms was present\n* No information was collected regarding the duration of feeling dazed or experiencing PTA\n\nConsequently, I used the following definition to identify mTBIs:\n\nAny child who experienced at least one injury where that injury resulted in either:\n\n1. Less than 30 minutes of LOC (including 0 minutes) **AND** any duration of memory loss / feeling dazed\n2. LOC that is greater than 0 minutes but less than 30 minutes.\n\nThe fixed nature of the questionnaire also meant that some information about multiple mTBIs sustained in the same way or about a very large number of mTBIs throughout a child's life could have been lost (see the previous section on identifying children with a history of mTBI).\nFor my analyses, I assume these edge cases are not common enough to meaningfully change any obtained conclusions.\n\nThe code below generates a new file which adds the following columns to the TBI screen data:\n\n1. if a subject has experienced an mTBI prior to baseline\n2. which of the reported head injuries were mTBIs\n3. the time since a subject's most recent mTBI\n\n\n**Script location**: \n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"wheeler-lab/abcd/prashanth-proj/process-data/generate_abcd_otbi01_detailed.Rmd\"\n```\n:::\n:::\n\n**Generate detailed form of abcd_otbi01**:\n::: {.cell}\n\n```{.r .cell-code}\n# 2022-04-09 PV\n\n# Summary: export list of patients who have had at least one mTBI as of baseline\n# mTBI is defined as (LOC < 30 min & mem/dazed) or (0 min < LOC < 30 min)\n\n\n# Load data and libraries and assign working directory\nlibrary(tidyverse)\nlibrary(magrittr) \n\n# Import baseline data\nabcd_otbi01 <- read_delim(paste0(\"lab-data/abcd/processed/prashanth_proj/\",\n                                 \"abcd_otbi01_renamed.csv\"), \n                          guess_max = Inf)\n# guess_max = Inf required to import without parsing errors (see ?readr)\n\n# Assign injury column values to numeric\nabcd_otbi01_detailed <- abcd_otbi01 %>%\n  mutate(across(hosp_er_inj:other_other_multi_effect_end_age, as.numeric))\n\n\n# 1. Identify if a subject has had mTBI prior to baseline (col: mTBI)\n## It is not possible to properly classify mTBI in the ABCD dataset\n## Here, I define an mTBI as a head/neck injury which was either:\n## 1. LOC < 30 mins (LOC < 2) and memory loss (mem_daze == 1)\n## 2. LOC between 0 and 30 mins (LOC == 1)\n\n## In this section, I create an mTBI column with the values:\n## 0 - definitely had 0 mTBI\n## 1 - definitely had at LEAST one mTBI\n## 0.5 - impossible to know if patient had at least one mTBI\n\nabcd_otbi01_detailed %<>%\n  mutate(mtbi = case_when(\n    (hosp_er_loc < 2 & hosp_er_mem_daze == 1) | hosp_er_loc == 1 ~ 1,\n    (vehicle_loc < 2 & vehicle_mem_daze == 1) | vehicle_loc == 1 ~ 1,\n    (fall_hit_loc < 2 & fall_hit_mem_daze == 1) | fall_hit_loc == 1 ~ 1,\n    (violent_hit_loc < 2 & violent_hit_mem_daze == 1) | violent_hit_loc == 1 ~ 1,\n    (blast_loc < 2 & blast_mem_daze == 1) | blast_loc == 1 ~ 1,\n    (other_loc_num - other_loc_num_over_30) > 0 ~ 1,\n    (multi_loc < 2 & multi_mem_daze == 1) | multi_loc == 1 ~ 1,\n    other_multi_inj == 1 ~ 0.5,\n    other_other_multi_inj == 1 ~ 0.5,\n    TRUE ~ 0))\n\n\n# 2. Identify if a subject has had a moderate or severe TBI prior to baseline\n## (col: moderate_or_severe_tbi)\n## based on the structure of the questionnaire, this can only be done by looking at LOC\nabcd_otbi01_detailed %<>%\n  mutate(moderate_or_severe_tbi = case_when(\n     (hosp_er_loc > 1 | \n      vehicle_loc > 1 | \n      fall_hit_loc > 1 | \n      violent_hit_loc > 1 |\n      blast_loc > 1 | \n      other_loc_num_over_30 > 0 | \n      multi_loc > 1) ~ 1,\n    other_multi_inj == 1 ~ 0.5,\n    other_other_multi_inj == 1 ~ 0.5,\n     TRUE ~ 0))\n\n# 3. Identify which injuries led to an mTBI (col: *_mtbi)\n\n## 3-1) convert ages from approximate years to approximate months for \n## subsequent calculations\nabcd_otbi01_detailed$blast_age <-\n    abcd_otbi01_detailed$blast_age * 12\nabcd_otbi01_detailed$hosp_er_age <-\n    abcd_otbi01_detailed$hosp_er_age * 12\nabcd_otbi01_detailed$vehicle_age <-\n    abcd_otbi01_detailed$vehicle_age * 12\nabcd_otbi01_detailed$fall_hit_age <-\n    abcd_otbi01_detailed$fall_hit_age * 12\nabcd_otbi01_detailed$violent_hit_age <- \n    abcd_otbi01_detailed$violent_hit_age * 12\nabcd_otbi01_detailed$other_loc_min_age <- \n    abcd_otbi01_detailed$other_loc_min_age * 12\nabcd_otbi01_detailed$multi_effect_end_age <- \n    abcd_otbi01_detailed$multi_effect_end_age * 12\n\n\n## 3-2) generate columns indicating which injury types were mTBIs\nabcd_otbi01_detailed %<>%\n  mutate(hosp_er_mtbi = case_when(\n    (hosp_er_loc < 2 & hosp_er_mem_daze == 1) | hosp_er_loc == 1 ~ TRUE,\n    TRUE ~ FALSE))\n\nabcd_otbi01_detailed %<>%\n  mutate(vehicle_mtbi = case_when(\n    (vehicle_loc < 2 & vehicle_mem_daze == 1) | vehicle_loc == 1 ~ TRUE,\n    TRUE ~ FALSE))\n\nabcd_otbi01_detailed %<>%\n  mutate(fall_hit_mtbi = case_when(\n    (fall_hit_loc < 2 & fall_hit_mem_daze == 1) | fall_hit_loc == 1 ~ TRUE,\n    TRUE ~ FALSE))\n\nabcd_otbi01_detailed %<>%\n  mutate(violent_hit_mtbi = case_when(\n    (violent_hit_loc < 2 & violent_hit_mem_daze == 1) | violent_hit_loc == 1 ~ TRUE,\n    TRUE ~ FALSE))\n\nabcd_otbi01_detailed %<>%\n  mutate(blast_mtbi = case_when(\n    (blast_loc < 2 & blast_mem_daze == 1) | blast_loc == 1 ~ TRUE,\n    TRUE ~ FALSE))\n\nabcd_otbi01_detailed %<>%\n  mutate(other_loc_mtbi = case_when(\n    (other_loc_num - other_loc_num_over_30) > 0 ~ TRUE,\n    TRUE ~ FALSE))\n\nabcd_otbi01_detailed %<>%\n  mutate(multi_mtbi = case_when(\n    (multi_loc < 2 & multi_mem_daze == 1) | multi_loc == 1 ~ TRUE,\n    TRUE ~ FALSE))\n\n\n# 4. Identify time since each type of mTBI (col: *_mtbi_mpi)\n## The syntax 'case_when(injury_type ~ ...)` means that variables are only calculated\n## if the associated injury type actually was an mTBI\nabcd_otbi01_detailed %<>%\n  mutate(hosp_er_mtbi_mpi = \n         case_when(hosp_er_mtbi ~ interview_age - hosp_er_age))\n\nabcd_otbi01_detailed %<>%\n  mutate(vehicle_mtbi_mpi = \n         case_when(vehicle_mtbi ~ interview_age - vehicle_age))\n\nabcd_otbi01_detailed %<>%\n  mutate(fall_hit_mtbi_mpi = \n         case_when(fall_hit_mtbi ~ interview_age - fall_hit_age))\n\nabcd_otbi01_detailed %<>%\n  mutate(violent_hit_mtbi_mpi = \n         case_when(violent_hit_mtbi ~ interview_age - violent_hit_age))\n\nabcd_otbi01_detailed %<>%\n  mutate(blast_mtbi_mpi = \n         case_when(blast_mtbi ~ interview_age - blast_age))\n\nabcd_otbi01_detailed %<>%\n  mutate(other_loc_mtbi_mpi = \n         case_when(other_loc_mtbi ~ interview_age - other_loc_min_age))\n\nabcd_otbi01_detailed %<>%\n  mutate(multi_mtbi_mpi = \n         case_when(multi_mtbi ~ interview_age - multi_effect_end_age))\n\n\n# 5. generate column indicating time since most recent mTBI (col: latest_mtbi_mpi)\nabcd_otbi01_detailed %<>%\n  mutate(latest_mtbi_mpi = pmin(hosp_er_mtbi_mpi,\n                               vehicle_mtbi_mpi,\n                               fall_hit_mtbi_mpi,\n                               violent_hit_mtbi_mpi,\n                               blast_mtbi_mpi,\n                               other_loc_mtbi_mpi,\n                               multi_mtbi_mpi, na.rm = TRUE))\n```\n:::\n\nThe histograms below show the distribution of the time-since-last-mtbi for each subject that received an mTBI prior to baseline data collection.\n\n::: {.cell}\n\n```{.r .cell-code}\n# 6. visualize time since most recent mTBI as a histogram\n## 6-1) all subjects\nhist(abcd_otbi01_detailed$latest_mtbi_mpi,\n     breaks=30,\n     main=\"Histogram of times since latest mTBI\", \n     xlab=\"Months since most recent mTBI\")\n```\n\n::: {.cell-output-display}\n![](identifying_subjects_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n\n```{.r .cell-code}\n## 6-2) crop histogram to children that are in a non-chronic stage post-mTBI\n### note that the negatives are a result of rounding used when anonymizing ages\nhist(abcd_otbi01_detailed$latest_mtbi_mpi,\n     breaks=50,\n     xlim=c(-5,5),\n     labels=TRUE,\n     main=\"Histogram of times since latest mTBI\",\n     xlab=\"Months since most recent mTBI\")\n```\n\n::: {.cell-output-display}\n![](identifying_subjects_files/figure-html/unnamed-chunk-6-2.png){width=672}\n:::\n\n```{.r .cell-code}\n## 6-3) count the number of children in a non-chronic stage post-mTBI\nsum(abcd_otbi01_detailed$latest_mtbi_mpi < 3, na.rm=TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 7\n```\n:::\n\n```{.r .cell-code}\n# 7 children had an mTBI within 3 months of baseline data collection\n\n## 6-4) evaluate mean and SD of time since latest mTBI for children at chronic stage post-mTBI\n\nsum(abcd_otbi01_detailed$latest_mtbi_mpi >= 3, na.rm=TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 424\n```\n:::\n\n```{.r .cell-code}\nchronic_subject_mtbi_mpis <- abcd_otbi01_detailed %>%\n    select(latest_mtbi_mpi) %>%\n    filter(latest_mtbi_mpi >= 3)\n\nmax(chronic_subject_mtbi_mpis)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 130\n```\n:::\n\n```{.r .cell-code}\nmin(chronic_subject_mtbi_mpis)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 4\n```\n:::\n\n```{.r .cell-code}\nsd(chronic_subject_mtbi_mpis$latest_mtbi_mpi)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 32.0575\n```\n:::\n\n```{.r .cell-code}\nmean(chronic_subject_mtbi_mpis$latest_mtbi_mpi)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 46.06934\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# 7. Identify number of mTBIs sustained by each subject (col: mtbi_count)\n\n## 7-1) convert NAs to 0s to include in subsequent column generation\nabcd_otbi01_detailed$\n    other_loc_num[is.na(abcd_otbi01_detailed$other_loc_num)] <- 0\n\nabcd_otbi01_detailed$\n    other_loc_num_over_30[is.na(abcd_otbi01_detailed$other_loc_num_over_30)] <- 0\n\n## 7-2) generate column of mTBI counts\nabcd_otbi01_detailed %<>%\n    mutate(mtbi_count = (hosp_er_mtbi +\n                         vehicle_mtbi + \n                         fall_hit_mtbi +\n                         violent_hit_mtbi + \n                         blast_mtbi + \n                         (other_loc_num - other_loc_num_over_30) + \n                         multi_mtbi))\n\ntable(abcd_otbi01_detailed$mtbi_count)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n    0     1     2     3     4     5 \n11057   306   116     7     1     1 \n```\n:::\n:::\n\nOf the 431 subjects with a previous mTBI, \n\n* 306 of them had 1 mTBI\n* 116 of them had 2 mTBIs\n* 7 of them had 7 mTBIs \n* 1 of them had 4 mTBIs\n* 1 of them had 5 mTBIs\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_csv(abcd_otbi01_detailed,\n          \"lab-data/abcd/processed/prashanth_proj/abcd_otbi01_detailed.csv\")\n```\n:::\n\nA few types of injuries were handled differently from the rest in the above code:\n\n* for `other_loc`, the questionnaire asked for a total number of injuries with LOC as well as a total number of injuries with LOC above 30 minutes.\n    * If their difference was above 0, they were labeled as having had an mTBI.\n* for `other_multi` and `other_other_multi`, insufficient information was provided to determine the severity of the associated injuries.\n\nFor my analyses, I consider 3 months to be the threshold at which an mTBI patient enters a chronic stage post-injury.\nThe subject list was then defined in the following code:\n\n\n**Script location**:\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"wheeler-lab/abcd/prashanth-proj/get-subjects/get-baseline-mtbi-subjects.Rmd\"\n```\n:::\n:::\n\n**Export chronic-stage mTBI subject list**:\n::: {.cell}\n\n```{.r .cell-code}\n# Load libraries\nlibrary(tidyverse)\nlibrary(magrittr)\n\n\n# import data\nabcd_otbi01 <-\n    read_delim(\"lab-data/abcd/processed/prashanth_proj/abcd_otbi01_detailed.csv\",\n    guess_max = Inf)\n\n\n# extract patients at with mTBI\nbaseline_mtbi_subjects <- abcd_otbi01 %>%\n  filter(mtbi == 1 & latest_mtbi_mpi >= 3) %>%\n  select(subjectkey, src_subject_id)\n\n\nwrite_csv(baseline_mtbi_subjects,\n          \"lab-data/abcd/processed/prashanth_proj/baseline_chronic_mtbi_subjects.csv\")\n```\n:::\n\n## Some participant demographics\n\n## Handling twins\n\n## Identifying matched and non-matched control groups",
    "supporting": [
      "identifying_subjects_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": null
  }
}