# Alpha and K hyperparameter search

In this section, 'default' settings (i.e., including all variables) are used to iterate through clustering solutions from different values of alpha and K.


```{r}
# Some functions that need a home

#' Scatter plot alpha and k hyperparameter results by minimum and mean p-values
#'
#' @param ak_scan_om output matrix containing alpha, K, and min/mean p-values
#' @param a_or_k string specifying whether alpha or K should be visualized
#'
#' @export
ak_scan_plot <- function(ak_scan_om, a_or_k = "k") {
    ak_default <- ak_scan_om |>
        dplyr::filter(K == 20, alpha == 0.5)
    min_p_val <- ""
    mean_p_val <- ""
    nclust <- ""
    K <- ""
    alpha <- ""
    if (a_or_k == "alpha" || a_or_k == "a") {
        plot <- ggplot2::ggplot(ak_scan_om, mapping = ggplot2::aes(
                x = min_p_val,
                y = mean_p_val,
                color = nclust,
                size = alpha))
    } else if (a_or_k == "k" || a_or_k == "K") {
        plot <- ggplot2::ggplot(ak_scan_om, mapping = ggplot2::aes(
                x = min_p_val,
                y = mean_p_val,
                color = nclust,
                size = K))
    } else {
        print("Visualizing alpha or K not specified. Defaulting to K.")
        plot <- ggplot2::ggplot(ak_scan_om, mapping = ggplot2::aes(
                x = min_p_val,
                y = mean_p_val,
                color = nclust,
                size = K))
    }
    plot +
        ggplot2::geom_point(data = ak_default, colour = "pink", size = 6) +
        ggplot2::geom_point() +
        ggplot2::scale_x_continuous(trans = "log10") +
        ggplot2::xlab("Minimum p-value") +
        ggplot2::ylab("Mean p-value") +
        ggplot2::theme_bw() +
        ggplot2::theme(text = ggplot2::element_text(size = 20))
}

#' Heatmap alpha and k hyperparameter results by minimum and mean p-values
#'
#' @param ak_scan_om output matrix containing alpha, K, and min/mean p-values
#' @param min_or_mean string specifying whether min or mean p-value should be
#'  visualized
#' @param save optional path to save figure to
#'
#' @export
ak_heatmap <- function(ak_scan_om, min_or_mean = "min", save = NULL) {
    if (min_or_mean == "min") {
        min_or_mean <- "min_p_val"
    } else if (min_or_mean == "mean") {
        min_or_mean <- "mean_p_val"
    } else {
        print("Min or mean p-value not specified. Defaulting to min.")
        min_or_mean <- "min_p_val"
    }
    a_k_matrix <- matrix(nrow = length(unique(ak_scan_om$"K")),
                         ncol = length(unique(ak_scan_om$"alpha")))
    colnames(a_k_matrix) <- as.character(seq(0.3, 1, by = 0.1))
    rownames(a_k_matrix) <- as.character(seq(10, 100, by = 10))
    for (i in seq_len(nrow(ak_scan_om))) {
       row <- as.character(ak_scan_om[i, "K"])
       col <- as.character(ak_scan_om[i, "alpha"])
       pval <- as.numeric(ak_scan_om[i, min_or_mean])
       a_k_matrix[row, col] <- pval
    }
    if (!(is.null(grDevices::dev.list()))) {
        grDevices::dev.off()
    }
    if (!(is.null(save))) {
        pheatmap::pheatmap(
            a_k_matrix,
            cluster_rows = FALSE,
            cluster_cols = FALSE,
            filename = save)
    }
    pheatmap::pheatmap(
        a_k_matrix,
        cluster_rows = FALSE,
        cluster_cols = FALSE)
}
```

```{r}
library(dplyr)
library(abcdutils)
library(scabcd)
library(readr)
library(here)
library(ggplot2)
library(pheatmap)

proc_path <- path_maker(here(paste0("data/abcd/results/processed")))
fig_path <- path_maker(here(paste0("data/abcd/results/figures")))

# Load training data
as_mtbi_loc_train <- read_csv(proc_path("as_mtbi_loc_train.csv"))
as_mtbi_mechanism_train <- read_csv(proc_path("as_mtbi_mechanism_train.csv"))
as_mtbi_mem_daze_train <- read_csv(proc_path("as_mtbi_mem_daze_train.csv"))
d_income_train <- read_csv(proc_path("d_income_train.csv"))
d_interview_age_train <- read_csv(proc_path("d_interview_age_train.csv"))
d_mtbi_age_train <- read_csv(proc_path("d_mtbi_age_train.csv"))
d_pubertal_status_train <- read_csv(proc_path("d_pubertal_status_train.csv"))
d_race_train <- read_csv(proc_path("d_race_train.csv"))
d_sex_train <- read_csv(proc_path("d_sex_train.csv"))
mh_headaches_train <- read_csv(proc_path("mh_headaches_train.csv"))
mh_mtbi_count_train <- read_csv(proc_path("mh_mtbi_count_train.csv"))
dm_wmndf_qc_train <- read_csv(proc_path("dm_wmndf_qc_train.csv"))
rm_gord_cor_qc_train <- read_csv(proc_path("rm_gord_cor_qc_train.csv"))
rm_gord_var_qc_train <- read_csv(proc_path("rm_gord_var_qc_train.csv"))
rm_subc_cor_qc_train <- read_csv(proc_path("rm_subc_cor_qc_train.csv"))
rm_subc_var_qc_train <- read_csv(proc_path("rm_subc_var_qc_train.csv"))
sm_cort_sa_qc_train <- read_csv(proc_path("sm_cort_sa_qc_train.csv"))
sm_cort_t_qc_train <- read_csv(proc_path("sm_cort_t_qc_train.csv"))
sm_subc_v_qc_train <- read_csv(proc_path("sm_subc_v_qc_train.csv"))
p_loneliness_train <- read_csv(proc_path("p_loneliness_train.csv"))
p_screen_time_train <- read_csv(proc_path("p_screen_time_train.csv"))
p_family_function_train <- read_csv(proc_path("p_family_function_train.csv"))
p_sports_train <- read_csv(proc_path("p_sports_train.csv"))
p_prosocial_train <- read_csv(proc_path("p_prosocial_train.csv"))
p_parent_psych_train <- read_csv(proc_path("p_parent_psych_train.csv"))
p_exercise_train <- read_csv(proc_path("p_exercise_train.csv"))
cbcl_headaches_train <- read_csv(proc_path("cbcl_headaches_train.csv"))
cbcl_nausea_train <- read_csv(proc_path("cbcl_nausea_train.csv"))
cbcl_vomiting_train <- read_csv(proc_path("cbcl_vomiting_train.csv"))
cbcl_dizzy_train <- read_csv(proc_path("cbcl_dizzy_train.csv"))
cbcl_overtired_train <- read_csv(proc_path("cbcl_overtired_train.csv"))
cbcl_sleeping_more_train <- read_csv(proc_path("cbcl_sleeping_more_train.csv"))
cbcl_sleeping_less_train <- read_csv(proc_path("cbcl_sleeping_less_train.csv"))
cbcl_depress_train <- read_csv(proc_path("cbcl_depress_train.csv"))
cbcl_anxiety_train <- read_csv(proc_path("cbcl_anxiety_train.csv"))
cbcl_attention_train <- read_csv(proc_path("cbcl_attention_train.csv"))
cbcl_aggressive_train <- read_csv(proc_path("cbcl_aggressive_train.csv"))
sds_sleep_train <- read_csv(proc_path("sds_sleep_train.csv"))


# Structure containing all input data
# These data should not contain any NAs, but need not have the same subjects
data_list <- generate_data_list(
    mtbi_loc = as_mtbi_loc_train,
    mtbi_mechanism = as_mtbi_mechanism_train,
    mtbi_mem_daze = as_mtbi_mem_daze_train,
    income = d_income_train,
    interview_age = d_interview_age_train,
    mtbi_age = d_mtbi_age_train,
    pubertal_status = d_pubertal_status_train,
    race = d_race_train,
    sex = d_sex_train,
    headaches = mh_headaches_train,
    mtbi_count = mh_mtbi_count_train,
    wmndf = dm_wmndf_qc_train,
    gord_cor = rm_gord_cor_qc_train,
    gord_var = rm_gord_var_qc_train,
    subc_cor = rm_subc_cor_qc_train,
    subc_var = rm_subc_var_qc_train,
    cort_sa = sm_cort_sa_qc_train,
    cort_t = sm_cort_t_qc_train,
    subc_v = sm_subc_v_qc_train,
    loneliness = p_loneliness_train,
    screen_time = p_screen_time_train,
    family_function = p_family_function_train,
    sports = p_sports_train,
    prosocial = p_prosocial_train,
    parent_psych = p_parent_psych_train,
    exercise = p_exercise_train)

# Structure containing all outcome data
outcome_list <- generate_outcome_list(
    cbcl_nausea = cbcl_nausea_train,
    cbcl_vomiting = cbcl_vomiting_train,
    cbcl_dizzy = cbcl_dizzy_train,
    cbcl_overtired = cbcl_overtired_train,
    cbcl_sleeping_more = cbcl_sleeping_more_train,
    cbcl_sleeping_less = cbcl_sleeping_less_train,
    cbcl_depress = cbcl_depress_train,
    cbcl_anxiety = cbcl_anxiety_train,
    cbcl_attention = cbcl_attention_train,
    cbcl_aggressive = cbcl_aggressive_train)


# Builds a standard design matrix only exploring SNF hyperparameters alpha and K
design_matrix_ak <- build_design_matrix_ak()

# Assess clustering minimum p-value for an ordinal dependent variable
ak_scan_om <- execute_design_matrix_hard(data_list, design_matrix_ak, outcome_list)

# Note that the column types will be different (and more accurate) when going
#  through the read_delim function. Without doing this, you will have a lot of
#  character columns. I will fix this eventually.
write_csv(ak_scan_om, proc_path("ak_scan_om.csv", date = TRUE))

ak_scan_om <- read_delim(proc_path("ak_scan_om.csv", date = "2023_02_17"))

min(ak_scan_om$min_p_val)
min(ak_scan_om$mean_p_val)

ak_scan_om$nclust <- as.factor(ak_scan_om$nclust)

ak_scan_plot(ak_scan_om, "k")
# ggsave(fig_path("k_scan_plot.png", date = TRUE), k_scan_plot)

ak_scan_plot(ak_scan_om, "a")
# ggsave(fig_path("a_scan_plot.png", date = TRUE), a_scan_plot)

# Alternative visualizations
ak_heatmap(ak_scan_om, "min",
           save_path = fig_path("ak_min_heatmap.png", date = TRUE))

ak_heatmap(ak_scan_om, "mean",
           save_path = fig_path("ak_mean_heatmap.png", date = TRUE))
```
