---
bibliography: bareferences.bib
format:
    html:
        page-layout: full
---


# Behavioural assessments

## The CBCL questionnaire (07-02-18 Edition - 201)

Items copied from: [https://aseba.org/wp-content/uploads/2019/02/schoolagecbcl.pdf](https://aseba.org/wp-content/uploads/2019/02/schoolagecbcl.pdf)

Subscale information:

- Aggressive (Agr): @ligthartGenetic2005
- Anxious-Depressed (AnxD): @readPredicting2015
- Attention (Atn): @ferroChild2014
- Rule-break (Rule): @nobileCOMT2010
- Somatic (Smtc): @readPredicting2015
- Social (Scl): @mathyssekChildhood2012
- Thought (Tht): @ferroChild2014
- Withdrawn-Depressed (WD): @hoekstraGenetic2008

The information below is not necessarily complete or entirely consistent with 1 version of the CBCL.
Question marks indicate my own guesses for items contributing to a subscale and are not based on any particular citation.

| **CBCL item**                                                                             | **Agr** | **AnxD** | **Atn** | **Rule** | **Smtc** | **Scl** | **Tht** | **WD** |
|-------------------------------------------------------------------------------------------|:-------:|:--------:|:-------:|:--------:|:--------:|:-------:|:-------:|:------:|
| <a name="cbcl1"></a>1. Acts too young for his/her age                                     |         |          |    x    |          |          |    x    |         |        |
| <a name="cbcl2"></a>2. Drinks alcohol without parents' approval                           |         |          |         |          |          |         |         |        |
| <a name="cbcl3"></a>3. Argues a lot                                                       |    x    |          |         |          |          |         |         |        |
| <a name="cbcl4"></a>4. Fails to finish things he/she starts                               |         |          |         |          |          |         |         |        |
| <a name="cbcl5"></a>5. There is very little he/she enjoys                                 |         |          |         |          |          |         |         |        |
| <a name="cbcl6"></a>6. Bowel movements outside toilet                                     |         |          |         |          |          |         |         |        |
| <a name="cbcl7"></a>7. Bragging, boasting                                                 |    x    |          |         |          |          |         |         |        |
| <a name="cbcl8"></a>8. Can't concentrate, can't pay attention for long                    |         |          |    x    |          |          |         |         |        |
| <a name="cbcl9"></a>9. Can't get his/her mind off certain thoughts; obsessions            |         |          |         |          |          |         |    x    |        |
| <a name="cbcl10"></a>10. Can't sit still, restless, or hyperactive                        |         |          |    x    |          |          |         |         |        |
| <a name="cbcl11"></a>11. Clings to adults or too dependent                                |         |          |         |          |          |    x    |         |        |
| <a name="cbcl12"></a>12. Complains of loneliness                                          |         |          |         |          |          |         |         |        |
| <a name="cbcl13"></a>13. Confused or seems to be in a fog                                 |         |          |    x    |          |          |         |         |        |
| <a name="cbcl14"></a>14. Cries a lot                                                      |         |    x     |         |          |          |         |         |        |
| <a name="cbcl15"></a>15. Cruel to animals                                                 |         |          |         |    x     |          |         |         |        |
| <a name="cbcl16"></a>16. Cruelty, bullying, or meanness to others                         |    x    |          |         |    x     |          |         |         |        |
| <a name="cbcl17"></a>17. Daydreams or gets lost in his/her thoughts                       |         |          |    x    |          |          |         |         |        |
| <a name="cbcl18"></a>18. Deliberately harms self or attempts suicide                      |         |          |         |          |          |         |    x    |        |
| <a name="cbcl19"></a>19. Demands a lot of attention                                       |    x    |          |         |          |          |         |         |        |
| <a name="cbcl20"></a>20. Destroys his/her own things                                      |    x    |          |         |    x     |          |         |         |        |
| <a name="cbcl21"></a>21. Destroys things belonging to his/her family or others            |    x    |          |         |          |          |         |         |        |
| <a name="cbcl22"></a>22. Disobedient at home                                              |    x    |          |         |          |          |         |         |        |
| <a name="cbcl23"></a>23. Disobedient at school                                            |    x    |          |         |          |          |         |         |        |
| <a name="cbcl24"></a>24. Doesn't eat well                                                 |         |          |         |          |          |         |         |        |
| <a name="cbcl25"></a>25. Doesn't get along with other kids                                |         |          |         |          |          |    x    |         |        |
| <a name="cbcl26"></a>26. Doesn't seem to feel guilty after misbehaving                    |         |          |         |    x     |          |         |         |        |
| <a name="cbcl27"></a>27. Easily jealous                                                   |    x    |          |         |          |          |         |         |        |
| <a name="cbcl28"></a>28. Breaks rules at home, school, or elsewhere                       |         |          |         |    x     |          |         |         |        |
| <a name="cbcl29"></a>29. Fears certain animals, situations, or places, other than school  |         |    x     |         |          |          |         |         |        |
| <a name="cbcl30"></a>30. Fears going to school                                            |         |    x     |         |          |          |         |         |        |
| <a name="cbcl31"></a>31. Fears he/she might think or do something bad                     |         |    x     |         |          |          |         |         |        |
| <a name="cbcl32"></a>32. Feels he/she has to be perfect                                   |         |    x     |         |          |          |         |         |        |
| <a name="cbcl33"></a>33. Feels or complains that no one loves him/her                     |         |    x     |         |          |          |         |         |        |
| <a name="cbcl34"></a>34. Feels others are out to get him/her                              |         |          |         |          |          |         |         |        |
| <a name="cbcl35"></a>35. Feels worthless or inferior                                      |         |    x     |         |          |          |         |         |        |
| <a name="cbcl36"></a>36. Gets hurt a lot, accident-prone                                  |         |          |         |          |          |         |         |        |
| <a name="cbcl37"></a>37. Gets in many fights                                              |    x    |          |         |    x     |          |         |         |        |
| <a name="cbcl38"></a>38. Gets teased a lot                                                |         |          |         |          |          |    x    |         |        |
| <a name="cbcl39"></a>39. Hangs around with others who get in trouble                      |         |          |         |    x     |          |         |         |        |
| <a name="cbcl40"></a>40. Hears sound or voices that aren't there                          |         |          |         |          |          |         |    x    |        |
| <a name="cbcl41"></a>41. Impulsive or acts without thinking                               |         |          |    x    |          |          |         |         |        |
| <a name="cbcl42"></a>42. Would rather be alone than with others                           |         |          |         |          |          |         |         |   x    |
| <a name="cbcl43"></a>43. Lying or cheating                                                |         |          |         |    x     |          |         |         |        |
| <a name="cbcl44"></a>44. Bites fingernails                                                |         |          |         |          |          |         |         |        |
| <a name="cbcl45"></a>45. Nervous, highstrung, or tense                                    |         |    x     |         |          |          |         |         |        |
| <a name="cbcl46"></a>46. Nervous movements or twitching                                   |         |          |         |          |          |         |    x    |        |
| <a name="cbcl47"></a>47. Nightmares                                                       |         |          |         |          |    x     |         |         |        |
| <a name="cbcl48"></a>48. Not liked by other kids                                          |         |          |         |          |          |    x    |         |        |
| <a name="cbcl49"></a>49. Constipated, doesn't move bowels                                 |         |          |         |          |    x     |         |         |        |
| <a name="cbcl50"></a>50. Too fearful or anxious                                           |         |    x     |         |          |          |         |         |        |
| <a name="cbcl51"></a>51. Feels dizzy or lightheaded                                       |         |          |         |          |    x     |         |         |        |
| <a name="cbcl52"></a>52. Feels too guilty                                                 |         |    x     |         |          |          |         |         |        |
| <a name="cbcl53"></a>53. Overeating                                                       |         |          |         |          |          |         |         |        |
| <a name="cbcl54"></a>54. Overtired without good reason                                    |         |          |         |          |    x     |         |         |        |
| <a name="cbcl55"></a>55. Overweight                                                       |         |          |         |          |          |         |         |        |
| <a name="cbcl56a"></a>56a. Physical problems without known medical cause: aches or pains  |         |          |         |          |    x     |         |         |        |
| <a name="cbcl56b"></a>56b. Above for headaches                                            |         |          |         |          |    x     |         |         |        |
| <a name="cbcl56c"></a>56c. Above for nausea, feels sick                                   |         |          |         |          |    x     |         |         |        |
| <a name="cbcl56d"></a>56d. Above for problems with eyes that are not corrected by glasses |         |          |         |          |    x     |         |         |        |
| <a name="cbcl56e"></a>56e. Rashes or other skin problems                                  |         |          |         |          |    x     |         |         |        |
| <a name="cbcl56f"></a>56f. Stomachaches                                                   |         |          |         |          |    x     |         |         |        |
| <a name="cbcl56g"></a>56g. Vomiting, throwing up                                          |         |          |         |          |    x     |         |         |        |
| <a name="cbcl56h"></a>56h. Other                                                          |         |          |         |          |          |         |         |        |
| <a name="cbcl57"></a>57. Physically attacks people                                        |    x    |          |         |    x     |          |         |         |        |
| <a name="cbcl58"></a>58. Picks nose, skin, or other parts of body                         |         |          |         |          |          |         |    x    |        |
| <a name="cbcl59"></a>59. Plays with own sex parts in public                               |         |          |         |          |          |         |    x    |        |
| <a name="cbcl60"></a>60. Plays with own sex parts too much                                |         |          |         |          |          |         |    x    |        |
| <a name="cbcl61"></a>61. Poor school work                                                 |         |          |    x    |          |          |         |         |        |
| <a name="cbcl62"></a>62. Poorly coordinated or clumsy                                     |         |          |         |          |          |    x    |         |        |
| <a name="cbcl63"></a>63. Prefers being with older kids                                    |         |          |         |          |          |         |         |        |
| <a name="cbcl64"></a>64. Prefers being with younger kids                                  |         |          |         |          |          |    x    |         |        |
| <a name="cbcl65"></a>65. Refuses to talk                                                  |         |          |         |          |          |         |         |   x    |
| <a name="cbcl66"></a>66. Repeats certain acts over and over; compulsions                  |         |          |         |          |          |         |    x    |        |
| <a name="cbcl67"></a>67. Runs away from home                                              |         |          |         |    x     |          |         |         |        |
| <a name="cbcl68"></a>68. Screams a lot                                                    |    x    |          |         |          |          |         |         |        |
| <a name="cbcl69"></a>69. Secretive, keeps things to self                                  |         |          |         |          |          |         |         |   x    |
| <a name="cbcl70"></a>70. Sees things that aren't there                                    |         |          |         |          |          |         |    x    |        |
| <a name="cbcl71"></a>71. Self-conscious or easily embarrassed                             |         |    x     |         |          |          |         |         |        |
| <a name="cbcl72"></a>72. Sets fires                                                       |         |          |         |    x     |          |         |         |        |
| <a name="cbcl73"></a>73. Sexual problems                                                  |         |          |         |          |          |         |         |        |
| <a name="cbcl74"></a>74. Showing off or clowning                                          |    x    |          |         |          |          |         |         |        |
| <a name="cbcl75"></a>75. Too shy or timid                                                 |         |          |         |          |          |         |         |   x    |
| <a name="cbcl76"></a>76. Sleeps less than most kids                                       |         |          |         |          |          |         |    x    |        |
| <a name="cbcl77"></a>77. Sleeps more than most kids during day and/or night               |         |          |         |          |          |         |         |        |
| <a name="cbcl78"></a>78. Inattentive or easily distracted                                 |         |          |   x?    |          |          |         |         |        |
| <a name="cbcl79"></a>79. Speech problem                                                   |         |          |         |          |          |         |         |        |
| <a name="cbcl80"></a>80. Stares blankly                                                   |         |          |    x    |          |          |         |         |   x    |
| <a name="cbcl81"></a>81. Steals at home                                                   |         |          |         |    x     |          |         |         |        |
| <a name="cbcl82"></a>82. Steals outside the home                                          |         |          |         |    x     |          |         |         |        |
| <a name="cbcl83"></a>83. Stores up too many things he/she doesn't need                    |         |          |         |          |          |         |    x    |        |
| <a name="cbcl84"></a>84. Strange behaviour                                                |         |          |         |          |          |         |    x    |        |
| <a name="cbcl85"></a>85. Strange ideas                                                    |         |          |         |          |          |         |    x    |        |
| <a name="cbcl86"></a>86. Stubborn, sullen, or irritable                                   |    x    |          |         |          |          |         |         |        |
| <a name="cbcl87"></a>87. Sudden changes in mood or feelings                               |    x    |          |         |          |          |         |         |        |
| <a name="cbcl88"></a>88. Sulks a lot                                                      |         |          |         |          |          |         |         |   x    |
| <a name="cbcl89"></a>89. Suspicious                                                       |         |          |         |          |          |         |         |        |
| <a name="cbcl90"></a>90. Swearing or obscene language                                     |         |          |         |    x     |          |         |         |        |
| <a name="cbcl91"></a>91. Talks about killing self                                         |         |    x     |         |          |          |         |         |        |
| <a name="cbcl92"></a>92. Talks or walks in sleep                                          |         |          |         |          |          |         |    x    |        |
| <a name="cbcl93"></a>93. Talks too much                                                   |    x    |          |         |          |          |         |         |        |
| <a name="cbcl94"></a>94. Teases a lot                                                     |    x    |          |         |          |          |         |         |        |
| <a name="cbcl95"></a>95. Temper tantrums or hot temper                                    |    x    |          |         |          |          |         |         |        |
| <a name="cbcl96"></a>96. Thinks about sex too much                                        |         |          |         |          |          |         |         |        |
| <a name="cbcl97"></a>97. Threatens people                                                 |    x    |          |         |    x     |          |         |         |        |
| <a name="cbcl98"></a>98. Thumb-sucking                                                    |         |          |         |          |          |         |         |        |
| <a name="cbcl99"></a>99. Smokes, chews, or sniffs tobacco                                 |         |          |         |          |          |         |         |        |
| <a name="cbcl100"></a>100. Trouble sleeping                                               |         |          |         |          |          |         |    x    |        |
| <a name="cbcl101"></a>101. Truancy, skips school                                          |         |          |         |    x     |          |         |         |        |
| <a name="cbcl102"></a>102. Underactive, slow moving, or lacks energy                      |         |          |         |          |          |         |         |   x    |
| <a name="cbcl103"></a>103. Unhappy, sad, or depressed                                     |         |          |         |          |          |         |         |   x    |
| <a name="cbcl104"></a>104. Unusually loud                                                 |    x    |          |         |          |          |         |         |        |
| <a name="cbcl105"></a>105. Uses drugs for nonmedical purposes                             |         |          |         |          |          |         |         |        |
| <a name="cbcl106"></a>106. Vandalism                                                      |         |          |         |    x     |          |         |         |        |
| <a name="cbcl107"></a>107. Wets self during the day                                       |         |          |         |          |          |         |         |        |
| <a name="cbcl108"></a>108. Wets the bed                                                   |         |          |         |          |          |         |         |        |
| <a name="cbcl109"></a>109. Whining                                                        |         |          |         |          |          |         |         |        |
| <a name="cbcl110"></a>110. Wishes to be of opposite sex                                   |         |          |         |          |          |         |         |        |
| <a name="cbcl111"></a>111. Withdrawn, doesn't get involved with others                    |         |          |         |          |          |         |         |   x    |
| <a name="cbcl112"></a>112. Worries                                                        |         |    x     |         |          |          |         |         |        |
| <a name="cbcl113"></a>113. Other (just written descriptions)                              |         |          |         |          |          |         |         |        |

## HBI

| HBI item                                           | CBCL equivalent item                         | Associated CBCL subscales |
|----------------------------------------------------|----------------------------------------------|---------------------------|
| 1. I have trouble paying attention                 | [8](#cbcl8)                                  | Attention                 |
| 2. I get distracted easily                         | [78](#cbcl78)                                | Attention?                |
| 3. I have a hard time concentrating                | [8](#cbcl8)                                  | Attention                 |
| 4. I have problems remembering what people tell me | [13?](#cbcl13) [22](#cbcl22)? Nothing really | Attention?                |
| 5. I have problems following directions            | [22](#cbcl22)                                | Aggressive                |
| 6. I daydream too much                             | [17](#cbcl17)                                | Attention                 |
| 7. I get confused                                  | [13](#cbcl13)                                | Attention                 |
| 8. I forget things                                 | Nothing really                               |                           |
| 9. I have problems finishing things                | [61](#cbcl61)?                               | Attention?                |
| 10. I have trouble figuring things out             | [61](#cbcl61)?                               | Attention?                |
| 11. It's hard for me to learn new things           | [61](#cbcl61)?                               | Attention?                |
| 12. I have headaches                               | [56b](#cbcl56b)                              | Somatic                   |
| 13. I feel dizzy                                   | [51](#cbcl51)?                               | Somatic                   |
| 14. I feel like the room is spinning               | [51](#cbcl51)?                               | Somatic                   |
| 15. I feel like I'm going to faint                 | [51](#cbcl51)?                               | Somatic?                  |
| 16. Things are blurry when I look at them          | [56d](#cbcl56d)                              | Somatic                   |
| 17. I see double                                   | [56d](#cbcl56d)                              | Somatic                   |
| 18. I feel sick to my stomach                      | [56c](#cbcl56c)                              | Somatic                   |
| 19. I get tired a lot                              | [54](#cbcl54), [77](#cbcl77)?                | Somatic                   |
| 20. I get tired easily                             | [54](#cbcl54), [77](#cbcl77)?                | Somatic                   |


# Which behaviour measures to use?

Literature search: 'child behaviour checklist' and 'concussion'


| Study                     | Journal                     | Legitness out of 5   | CBCL use                                                                                                                                   |
|---------------------------|-----------------------------|----------------------|--------------------------------------------------------------------------------------------------------------------------------------------|
| Liu et al., 2013          | Brain Inj (IF 2.167)        | 2                    | Internalizing (T), externalizing (T), total (T), emotionally reactive, anxious/depressed, somatic, withdrawn, sleep, attention, aggressive |
| Huynh et al., 2023        | Child Neuropsych (IF 2.597) | 5 (Beauchamp)        | Internalizing and externalizing problems subscale                                                                                          |
| Gornall et al., 2020      | J Neurotrauma (IF 4.2)      | 5                    | Total (T), internalizing (T) and externalizing (T) problems subscale                                                                       |
| Brooks et al., 2018       | J Neurotrauma (IF 4.2)      | 5 (perc team)        | Withdrawn-depressed and anxious-depressed                                                                                                  |
| Gagner et al., 2019       | J Ped Psych (IF 3.624)      | 5 (Beachamp)         | Internalizing and externalizing                                                                                                            |
| Roghair et al., 2022      | Orthop J Sports Med (3.4)   | 3                    | All as T-scores, the internalizing, externalizing, total, anx-dep, with-dep, somatc, social, thought, attn, rule-breaking, aggressive      |
| Gagner et al., 2018       | Psychol Med                 | 5 (Beauchamp)        | NA (can't access article)                                                                                                                  |
| Madaan et al., 2021       | J Child Neurol (2.4)        | 2                    | Attention, aggressiveness, rule-break, withdrawn, somatic, anxiety, depression, thought problems, social problems                          |
| Veliz and Berryhill, 2023 | J Head Trauma Rehabil (3.4) | 3                    | NA (can't access article)                                                                                                                  |
| Hunt et al., 2020         | Brain Inj                   | 5 (Reed and Scratch) | All as T scores, anx-dep, somatic, with-dep, rule-break, aggressive, social, thought, attn, internal, external, total                      |
| Gagner et al., 2021       | J Neurotrauma               | 5 (Beauchamp)        | Internalizing and externalizing problems                                                                                                   |


Recommendation: Collect information on total, internalizing, externalizing subscales as well as all the subscales they are composed of.

# References
