---
format:
  html:
    embed-resources: true
    toc: true
---

# rs-fMRI: cortical ROI to cortical ROI average correlations

43. default network vs. default network [1](https://pubmed.ncbi.nlm.nih.gov/36182818/), [2](https://pubmed.ncbi.nlm.nih.gov/36594665/), [3](https://pubmed.ncbi.nlm.nih.gov/36999674/), [4](https://pubmed.ncbi.nlm.nih.gov/36841854/)
45. default network vs. fronto-parietal network [1](https://pubmed.ncbi.nlm.nih.gov/36182818/), 
57. dorsal attention network vs. dorsal attention network [3](https://pubmed.ncbi.nlm.nih.gov/36999674/)
71. fronto-parietal network vs. fronto-parietal network [1](https://pubmed.ncbi.nlm.nih.gov/36182818/), [2](https://pubmed.ncbi.nlm.nih.gov/36594665/)
113. salience network vs. salience network [1](https://pubmed.ncbi.nlm.nih.gov/36182818/), [4](https://pubmed.ncbi.nlm.nih.gov/36841854/)

::: {.callout-note appearance="simple" collapse=true}

## Features that were not selected

1. auditory network vs. auditory network
2. auditory network vs. cingulo-opercular network
3. auditory network vs. cingulo-parietal network
4. auditory network vs. default network
5. auditory network vs. dorsal attention network
6. auditory network vs. fronto-parietal network
7. auditory network vs. none network
8. auditory network vs. retrosplenial temporal network
9. auditory network vs. salience network
10. auditory network vs. sensorimotor hand network
11. auditory network vs. sensorimotor mouth network
12. auditory network vs. ventral attention network
13. auditory network vs. visual network
14. cingulo-opercular network vs. auditory network
15. cingulo-opercular network vs. cingulo-opercular network
16. cingulo-opercular network vs. cingulo-parietal network
17. cingulo-opercular network vs. default network
18. cingulo-opercular network vs. dorsal attention network
19. cingulo-opercular network vs. fronto-parietal network
20. cingulo-opercular network vs. none network
21. cingulo-opercular network vs. retrosplenial temporal network
22. cingulo-opercular network vs. salience network
23. cingulo-opercular network vs. sensorimotor hand network
24. cingulo-opercular network vs. sensorimotor mouth network
25. cingulo-opercular network vs. ventral attention network
26. cingulo-opercular network vs. visual network
27. cingulo-parietal network vs. auditory network
28. cingulo-parietal network vs. cingulo-opercular network
29. cingulo-parietal network vs. cingulo-parietal network
30. cingulo-parietal network vs. default network
31. cingulo-parietal network vs. dorsal attention network
32. cingulo-parietal network vs. fronto-parietal network
33. cingulo-parietal network vs. none network
34. cingulo-parietal network vs. retrosplenial temporal network
35. cingulo-parietal network vs. salience network
36. cingulo-parietal network vs. sensorimotor hand network
37. cingulo-parietal network vs. sensorimotor mouth network
38. cingulo-parietal network vs. ventral attention network
39. cingulo-parietal network vs. visual network
40. default network vs. auditory network
41. default network vs. cingulo-opercular network
42. default network vs. cingulo-parietal network
44. default network vs. dorsal attention network
46. default network vs. none network
47. default network vs. retrosplenial temporal network
48. default network vs. salience network
49. default network vs. sensorimotor hand network
50. default network vs. sensorimotor mouth network
51. default network vs. ventral attention network
52. default network vs. visual network
53. dorsal attention network vs. auditory network
54. dorsal attention network vs. cingulo-opercular network
55. dorsal attention network vs. cingulo-parietal network
56. dorsal attention network vs. default network
58. dorsal attention network vs. fronto-parietal network
59. dorsal attention network vs. none network
60. dorsal attention network vs. retrosplenial temporal network
61. dorsal attention network vs. salience network
62. dorsal attention network vs. sensorimotor hand network
63. dorsal attention network vs. sensorimotor mouth network
64. dorsal attention network vs. ventral attention network
65. dorsal attention network vs. visual network
66. fronto-parietal network vs. auditory network
67. fronto-parietal network vs. cingulo-opercular network
68. fronto-parietal network vs. cingulo-parietal network
69. fronto-parietal network vs. default network
70. fronto-parietal network vs. dorsal attention network
72. fronto-parietal network vs. none network
73. fronto-parietal network vs. retrosplenial temporal network
74. fronto-parietal network vs. salience network
75. fronto-parietal network vs. sensorimotor hand network
76. fronto-parietal network vs. sensorimotor mouth network
77. fronto-parietal network vs. ventral attention network
78. fronto-parietal network vs. visual network
79. none network vs. auditory network
80. none network vs. cingulo-opercular network
81. none network vs. cingulo-parietal network
82. none network vs. default network
83. none network vs. dorsal attention network
84. none network vs. fronto-parietal network
85. none network vs. none network
86. none network vs. retrosplenial temporal network
87. none network vs. salience network
88. none network vs. sensorimotor hand network
89. none network vs. sensorimotor mouth network
90. none network vs. ventral attention network
91. none network vs. visual network
92. retrosplenial temporal network vs. auditory network
93. retrosplenial temporal network vs. cingulo-opercular network
94. retrosplenial temporal network vs. cingulo-parietal network
95. retrosplenial temporal network vs. default network
96. retrosplenial temporal network vs. dorsal attention network
97. retrosplenial temporal network vs. fronto-parietal network
98. retrosplenial temporal network vs. none network
99. retrosplenial temporal network vs. retrosplenial temporal network
100. retrosplenial temporal network vs. salience network
101. retrosplenial temporal network vs. sensorimotor hand network
102. retrosplenial temporal network vs. sensorimotor mouth network
103. retrosplenial temporal network vs. ventral attention network
104. retrosplenial temporal network vs. visual network
105. salience network vs. auditory network
106. salience network vs. cingulo-opercular network
107. salience network vs. cingulo-parietal network
108. salience network vs. default network
109. salience network vs. dorsal attention network
110. salience network vs. fronto-parietal network
111. salience network vs. none network
112. salience network vs. retrosplenial temporal network
114. salience network vs. sensorimotor hand network
115. salience network vs. sensorimotor mouth network
116. salience network vs. ventral attention network
117. salience network vs. visual network
118. sensorimotor hvs. network and auditory network
119. sensorimotor hvs. network and cingulo-opercular network
120. sensorimotor hvs. network and cingulo-parietal network
121. sensorimotor hvs. network and default network
122. sensorimotor hvs. network and dorsal attention network
123. sensorimotor hvs. network and fronto-parietal network
124. sensorimotor hvs. network and none network
125. sensorimotor hvs. network and retrosplenial temporal network
126. sensorimotor hvs. network and salience network
127. sensorimotor hvs. network and sensorimotor hand network
128. sensorimotor hvs. network and sensorimotor mouth network
129. sensorimotor hvs. network and ventral attention network
130. sensorimotor hvs. network and visual network
131. sensorimotor mouth network vs. auditory network
132. sensorimotor mouth network vs. cingulo-opercular network
133. sensorimotor mouth network vs. cingulo-parietal network
134. sensorimotor mouth network vs. default network
135. sensorimotor mouth network vs. dorsal attention network
136. sensorimotor mouth network vs. fronto-parietal network
137. sensorimotor mouth network vs. none network
138. sensorimotor mouth network vs. retrosplenial temporal network
139. sensorimotor mouth network vs. salience network
140. sensorimotor mouth network vs. sensorimotor hand network
141. sensorimotor mouth network vs. sensorimotor mouth network
142. sensorimotor mouth network vs. ventral attention network
143. sensorimotor mouth network vs. visual network
144. ventral attention network vs. auditory network
145. ventral attention network vs. cingulo-opercular network
146. ventral attention network vs. cingulo-parietal network
147. ventral attention network vs. default network
148. ventral attention network vs. dorsal attention network
149. ventral attention network vs. fronto-parietal network
150. ventral attention network vs. none network
151. ventral attention network vs. retrosplenial temporal network
152. ventral attention network vs. salience network
153. ventral attention network vs. sensorimotor hand network
154. ventral attention network vs. sensorimotor mouth network
155. ventral attention network vs. ventral attention network
156. ventral attention network vs. visual network
157. visual network vs. auditory network
158. visual network vs. cingulo-opercular network
159. visual network vs. cingulo-parietal network
160. visual network vs. default network
161. visual network vs. dorsal attention network
162. visual network vs. fronto-parietal network
163. visual network vs. none network
164. visual network vs. retrosplenial temporal network
165. visual network vs. salience network
166. visual network vs. sensorimotor hand network
167. visual network vs. sensorimotor mouth network
168. visual network vs. ventral attention network
169. visual network vs. visual network

:::

# rs-fMRI: cortical ROI to subcortical ROI average correlations

160. salience network and ASEG ROI left-cerebellum-cortex [4](https://pubmed.ncbi.nlm.nih.gov/36841854/) ?
161. salience network and ASEG ROI right-cerebellum-cortex  [4](https://pubmed.ncbi.nlm.nih.gov/36841854/) ?

::: {.callout-note appearance="simple" collapse=true}

## Features that were not selected

1. auditory network and ASEG ROI left-accumbens-area
2. auditory network and ASEG ROI right-accumbens-area
3. auditory network and ASEG ROI left-amygdala
4. auditory network and ASEG ROI right-amygdala
5. auditory network and ASEG ROI brain-stem
6. auditory network and ASEG ROI left-caudate
7. auditory network and ASEG ROI right-caudate
8. auditory network and ASEG ROI left-cerebellum-cortex
9. auditory network and ASEG ROI right-cerebellum-cortex
10. auditory network and ASEG ROI left-hippocampus
11. auditory network and ASEG ROI right-hippocampus
12. auditory network and ASEG ROI left-pallidum
13. auditory network and ASEG ROI right-pallidum
14. auditory network and ASEG ROI left-putamen
15. auditory network and ASEG ROI right-putamen
16. auditory network and ASEG ROI left-thalamus-proper
17. auditory network and ASEG ROI right-thalamus-proper
18. auditory network and ASEG ROI left-ventraldc
19. auditory network and ASEG ROI right-ventraldc
20. cingulo-opercular network and ASEG ROI left-accumbens-area
21. cingulo-opercular network and ASEG ROI right-accumbens-area
22. cingulo-opercular network and ASEG ROI left-amygdala
23. cingulo-opercular network and ASEG ROI right-amygdala
24. cingulo-opercular network and ASEG ROI brain-stem
25. cingulo-opercular network and ASEG ROI left-caudate
26. cingulo-opercular network and ASEG ROI right-caudate
27. cingulo-opercular network and ASEG ROI left-cerebellum-cortex
28. cingulo-opercular network and ASEG ROI right-cerebellum-cortex
29. cingulo-opercular network and ASEG ROI left-hippocampus
30. cingulo-opercular network and ASEG ROI right-hippocampus
31. cingulo-opercular network and ASEG ROI left-pallidum
32. cingulo-opercular network and ASEG ROI right-pallidum
33. cingulo-opercular network and ASEG ROI left-putamen
34. cingulo-opercular network and ASEG ROI right-putamen
35. cingulo-opercular network and ASEG ROI left-thalamus-proper
36. cingulo-opercular network and ASEG ROI right-thalamus-proper
37. cingulo-opercular network and ASEG ROI left-ventraldc
38. cingulo-opercular network and ASEG ROI right-ventraldc
39. cingulo-parietal network and ASEG ROI left-accumbens-area
40. cingulo-parietal network and ASEG ROI right-accumbens-area
41. cingulo-parietal network and ASEG ROI left-amygdala
42. cingulo-parietal network and ASEG ROI right-amygdala
43. cingulo-parietal network and ASEG ROI brain-stem
44. cingulo-parietal network and ASEG ROI left-caudate
45. cingulo-parietal network and ASEG ROI right-caudate
46. cingulo-parietal network and ASEG ROI left-cerebellum-cortex
47. cingulo-parietal network and ASEG ROI right-cerebellum-cortex
48. cingulo-parietal network and ASEG ROI left-hippocampus
49. cingulo-parietal network and ASEG ROI right-hippocampus
50. cingulo-parietal network and ASEG ROI left-pallidum
51. cingulo-parietal network and ASEG ROI right-pallidum
52. cingulo-parietal network and ASEG ROI left-putamen
53. cingulo-parietal network and ASEG ROI right-putamen
54. cingulo-parietal network and ASEG ROI left-thalamus-proper
55. cingulo-parietal network and ASEG ROI right-thalamus-proper
56. cingulo-parietal network and ASEG ROI left-ventraldc
57. cingulo-parietal network and ASEG ROI right-ventraldc
58. default network and ASEG ROI left-accumbens-area
59. default network and ASEG ROI right-accumbens-area
60. default network and ASEG ROI left-amygdala
61. default network and ASEG ROI right-amygdala
62. default network and ASEG ROI brain-stem
63. default network and ASEG ROI left-caudate
64. default network and ASEG ROI right-caudate
65. default network and ASEG ROI left-cerebellum-cortex
66. default network and ASEG ROI right-cerebellum-cortex
67. default network and ASEG ROI left-hippocampus
68. default network and ASEG ROI right-hippocampus
69. default network and ASEG ROI left-pallidum
70. default network and ASEG ROI right-pallidum
71. default network and ASEG ROI left-putamen
72. default network and ASEG ROI right-putamen
73. default network and ASEG ROI left-thalamus-proper
74. default network and ASEG ROI right-thalamus-proper
75. default network and ASEG ROI left-ventraldc
76. default network and ASEG ROI right-ventraldc
77. dorsal attention network and ASEG ROI left-accumbens-area
78. dorsal attention network and ASEG ROI right-accumbens-area
79. dorsal attention network and ASEG ROI left-amygdala
80. dorsal attention network and ASEG ROI right-amygdala
81. dorsal attention network and ASEG ROI brain-stem
82. dorsal attention network and ASEG ROI left-caudate
83. dorsal attention network and ASEG ROI right-caudate
84. dorsal attention network and ASEG ROI left-cerebellum-cortex
85. dorsal attention network and ASEG ROI right-cerebellum-cortex
86. dorsal attention network and ASEG ROI left-hippocampus
87. dorsal attention network and ASEG ROI right-hippocampus
88. dorsal attention network and ASEG ROI left-pallidum
89. dorsal attention network and ASEG ROI right-pallidum
90. dorsal attention network and ASEG ROI left-putamen
91. dorsal attention network and ASEG ROI right-putamen
92. dorsal attention network and ASEG ROI left-thalamus-proper
93. dorsal attention network and ASEG ROI right-thalamus-proper
94. dorsal attention network and ASEG ROI left-ventraldc
95. dorsal attention network and ASEG ROI right-ventraldc
96. fronto-parietal network and ASEG ROI left-accumbens-area
97. fronto-parietal network and ASEG ROI right-accumbens-area
98. fronto-parietal network and ASEG ROI left-amygdala
99. fronto-parietal network and ASEG ROI right-amygdala
100. fronto-parietal network and ASEG ROI brain-stem
101. fronto-parietal network and ASEG ROI left-caudate
102. fronto-parietal network and ASEG ROI right-caudate
103. fronto-parietal network and ASEG ROI left-cerebellum-cortex
104. fronto-parietal network and ASEG ROI right-cerebellum-cortex
105. fronto-parietal network and ASEG ROI left-hippocampus
106. fronto-parietal network and ASEG ROI right-hippocampus
107. fronto-parietal network and ASEG ROI left-pallidum
108. fronto-parietal network and ASEG ROI right-pallidum
109. fronto-parietal network and ASEG ROI left-putamen
110. fronto-parietal network and ASEG ROI right-putamen
111. fronto-parietal network and ASEG ROI left-thalamus-proper
112. fronto-parietal network and ASEG ROI right-thalamus-proper
113. fronto-parietal network and ASEG ROI left-ventraldc
114. fronto-parietal network and ASEG ROI right-ventraldc
115. none network and ASEG ROI left-accumbens-area
116. none network and ASEG ROI right-accumbens-area
117. none network and ASEG ROI left-amygdala
118. none network and ASEG ROI right-amygdala
119. none network and ASEG ROI brain-stem
120. none network and ASEG ROI left-caudate
121. none network and ASEG ROI right-caudate
122. none network and ASEG ROI left-cerebellum-cortex
123. none network and ASEG ROI right-cerebellum-cortex
124. none network and ASEG ROI left-hippocampus
125. none network and ASEG ROI right-hippocampus
126. none network and ASEG ROI left-pallidum
127. none network and ASEG ROI right-pallidum
128. none network and ASEG ROI left-putamen
129. none network and ASEG ROI right-putamen
130. none network and ASEG ROI left-thalamus-proper
131. none network and ASEG ROI right-thalamus-proper
132. none network and ASEG ROI left-ventraldc
133. none network and ASEG ROI right-ventraldc
134. retrosplenial temporal network and ASEG ROI left-accumbens-area
135. retrosplenial temporal network and ASEG ROI right-accumbens-area
136. retrosplenial temporal network and ASEG ROI left-amygdala
137. retrosplenial temporal network and ASEG ROI right-amygdala
138. retrosplenial temporal network and ASEG ROI brain-stem
139. retrosplenial temporal network and ASEG ROI left-caudate
140. retrosplenial temporal network and ASEG ROI right-caudate
141. retrosplenial temporal network and ASEG ROI left-cerebellum-cortex
142. retrosplenial temporal network and ASEG ROI right-cerebellum-cortex
143. retrosplenial temporal network and ASEG ROI left-hippocampus
144. retrosplenial temporal network and ASEG ROI right-hippocampus
145. retrosplenial temporal network and ASEG ROI left-pallidum
146. retrosplenial temporal network and ASEG ROI right-pallidum
147. retrosplenial temporal network and ASEG ROI left-putamen
148. retrosplenial temporal network and ASEG ROI right-putamen
149. retrosplenial temporal network and ASEG ROI left-thalamus-proper
150. retrosplenial temporal network and ASEG ROI right-thalamus-proper
151. retrosplenial temporal network and ASEG ROI left-ventraldc
152. retrosplenial temporal network and ASEG ROI right-ventraldc
153. salience network and ASEG ROI left-accumbens-area
154. salience network and ASEG ROI right-accumbens-area
155. salience network and ASEG ROI left-amygdala
156. salience network and ASEG ROI right-amygdala
157. salience network and ASEG ROI brain-stem
158. salience network and ASEG ROI left-caudate
159. salience network and ASEG ROI right-caudate
162. salience network and ASEG ROI left-hippocampus
163. salience network and ASEG ROI right-hippocampus
164. salience network and ASEG ROI left-pallidum
165. salience network and ASEG ROI right-pallidum
166. salience network and ASEG ROI left-putamen
167. salience network and ASEG ROI right-putamen
168. salience network and ASEG ROI left-thalamus-proper
169. salience network and ASEG ROI right-thalamus-proper
170. salience network and ASEG ROI left-ventraldc
171. salience network and ASEG ROI right-ventraldc
172. sensorimotor hand network and ASEG ROI left-accumbens-area
173. sensorimotor hand network and ASEG ROI right-accumbens-area
174. sensorimotor hand network and ASEG ROI left-amygdala
175. sensorimotor hand network and ASEG ROI right-amygdala
176. sensorimotor hand network and ASEG ROI brain-stem
177. sensorimotor hand network and ASEG ROI left-caudate
178. sensorimotor hand network and ASEG ROI right-caudate
179. sensorimotor hand network and ASEG ROI left-cerebellum-cortex
180. sensorimotor hand network and ASEG ROI right-cerebellum-cortex
181. sensorimotor hand network and ASEG ROI left-hippocampus
182. sensorimotor hand network and ASEG ROI right-hippocampus
183. sensorimotor hand network and ASEG ROI left-pallidum
184. sensorimotor hand network and ASEG ROI right-pallidum
185. sensorimotor hand network and ASEG ROI left-putamen
186. sensorimotor hand network and ASEG ROI right-putamen
187. sensorimotor hand network and ASEG ROI left-thalamus-proper
188. sensorimotor hand network and ASEG ROI right-thalamus-proper
189. sensorimotor hand network and ASEG ROI left-ventraldc
190. sensorimotor hand network and ASEG ROI right-ventraldc
191. sensorimotor mouth network and ASEG ROI left-accumbens-area
192. sensorimotor mouth network and ASEG ROI right-accumbens-area
193. sensorimotor mouth network and ASEG ROI left-amygdala
194. sensorimotor mouth network and ASEG ROI right-amygdala
195. sensorimotor mouth network and ASEG ROI brain-stem
196. sensorimotor mouth network and ASEG ROI left-caudate
197. sensorimotor mouth network and ASEG ROI right-caudate
198. sensorimotor mouth network and ASEG ROI left-cerebellum-cortex
199. sensorimotor mouth network and ASEG ROI right-cerebellum-cortex
200. sensorimotor mouth network and ASEG ROI left-hippocampus
201. sensorimotor mouth network and ASEG ROI right-hippocampus
202. sensorimotor mouth network and ASEG ROI left-pallidum
203. sensorimotor mouth network and ASEG ROI right-pallidum
204. sensorimotor mouth network and ASEG ROI left-putamen
205. sensorimotor mouth network and ASEG ROI right-putamen
206. sensorimotor mouth network and ASEG ROI left-thalamus-proper
207. sensorimotor mouth network and ASEG ROI right-thalamus-proper
208. sensorimotor mouth network and ASEG ROI left-ventraldc
209. sensorimotor mouth network and ASEG ROI right-ventraldc
210. ventral attention network and ASEG ROI left-accumbens-area
211. ventral attention network and ASEG ROI right-accumbens-area
212. ventral attention network and ASEG ROI left-amygdala
213. ventral attention network and ASEG ROI right-amygdala
214. ventral attention network and ASEG ROI brain-stem
215. ventral attention network and ASEG ROI left-caudate
216. ventral attention network and ASEG ROI right-caudate
217. ventral attention network and ASEG ROI left-cerebellum-cortex
218. ventral attention network and ASEG ROI right-cerebellum-cortex
219. ventral attention network and ASEG ROI left-hippocampus
220. ventral attention network and ASEG ROI right-hippocampus
221. ventral attention network and ASEG ROI left-pallidum
222. ventral attention network and ASEG ROI right-pallidum
223. ventral attention network and ASEG ROI left-putamen
224. ventral attention network and ASEG ROI right-putamen
225. ventral attention network and ASEG ROI left-thalamus-proper
226. ventral attention network and ASEG ROI right-thalamus-proper
227. ventral attention network and ASEG ROI left-ventraldc
228. ventral attention network and ASEG ROI right-ventraldc
229. visual network and ASEG ROI left-accumbens-area
230. visual network and ASEG ROI right-accumbens-area
231. visual network and ASEG ROI left-amygdala
232. visual network and ASEG ROI right-amygdala
233. visual network and ASEG ROI brain-stem
234. visual network and ASEG ROI left-caudate
235. visual network and ASEG ROI right-caudate
236. visual network and ASEG ROI left-cerebellum-cortex
237. visual network and ASEG ROI right-cerebellum-cortex
238. visual network and ASEG ROI left-hippocampus
239. visual network and ASEG ROI right-hippocampus
240. visual network and ASEG ROI left-pallidum
241. visual network and ASEG ROI right-pallidum
242. visual network and ASEG ROI left-putamen
243. visual network and ASEG ROI right-putamen
244. visual network and ASEG ROI left-thalamus-proper
245. visual network and ASEG ROI right-thalamus-proper
246. visual network and ASEG ROI left-ventraldc
247. visual network and ASEG ROI right-ventraldc

:::

# diffusion MRI - RND, major cortical white matter

38. all fibers

::: {.callout-note appearance="simple" collapse=true}

## Features that were not selected

1. right fornix
2. left fornix
3. right cingulate cingulum
4. left cingulate cingulum
5. right parahpcm cingulum
6. left parahpcm cingulum
7. right corticospinal/pyramidal
8. left corticospinal/pyramidal
9. right anterior thalamic radiations
10. left right anterior thalamic radiations
11. right uncinate fasciculus
12. left uncinate
13. right inferior longitudinal fasciculus
14. left inferior longitudinal fasciculus
15. right inferior fronto-occipital fasciculus
16. left inferior fronto-occipital fasciculus
17. forceps major
18. forceps minor
19. corpus callosum
20. right superior longitudinal fasciculus
21. left superior longitudinal fasciculus
22. right temporal superior longitudinal fasiculus
23. left temporal superior longitudinal fasiculus
24. right parietal superior longitudinal fasiculus
25. left parietal superior longitudinal fasiculus
26. right superior corticostriate
27. left superior corticostriate
28. right superior corticostriate-frontal cortex only
29. left superior corticostriate-frontal cortex only
30. right superior corticostriate-parietal cortex only
31. left superior corticostriate-parietal cortex only
32. right striatal inferior frontal cortex
33. left striatal inferior frontal cortex
34. right inferior frontal superior frontal cortex
35. left inferior frontal superior frontal cortex
36. right fornix, excluding fimbria
37. left fornix, excluding fimbria
39. right hemisphere fibers without corpus callosum
40. left hemisphere fibers without corpus callosum
41. right hemisphere fibers
42. left hemisphere fibers

:::

# diffusion MRI - RND, peri-cortical white matter

69. mean

::: {.callout-note appearance="simple" collapse=true}

## Features that were not selected

1. left hemisphere bankssts
2. left hemisphere caudalanteriorcingulate
3. left hemisphere caudalmiddlefrontal
4. left hemisphere cuneus
5. left hemisphere entorhinal
6. left hemisphere fusiform
7. left hemisphere inferiorparietal
8. left hemisphere inferiortemporal
9. left hemisphere isthmuscingulate
10. left hemisphere lateraloccipital
11. left hemisphere lateralorbitofrontal
12. left hemisphere lingual
13. left hemisphere medialorbitofrontal
14. left hemisphere middletemporal
15. left hemisphere parahippocampal
16. left hemisphere paracentral
17. left hemisphere parsopercularis
18. left hemisphere parsorbitalis
19. left hemisphere parstriangularis
20. left hemisphere pericalcarine
21. left hemisphere postcentral
22. left hemisphere posteriorcingulate
23. left hemisphere precentral
24. left hemisphere precuneus
25. left hemisphere rostralanteriorcingulate
26. left hemisphere rostralmiddlefrontal
27. left hemisphere superiorfrontal
28. left hemisphere superiorparietal
29. left hemisphere superiortemporal
30. left hemisphere supramarginal
31. left hemisphere frontalpole
32. left hemisphere temporalpole
33. left hemisphere transversetemporal
34. left hemisphere insula
35. right hemisphere bankssts
36. right hemisphere caudalanteriorcingulate
37. right hemisphere caudalmiddlefrontal
38. right hemisphere cuneus
39. right hemisphere entorhinal
40. right hemisphere fusiform
41. right hemisphere inferiorparietal
42. right hemisphere inferiortemporal
43. right hemisphere isthmuscingulate
44. right hemisphere lateraloccipital
45. right hemisphere lateralorbitofrontal
46. right hemisphere lingual
47. right hemisphere medialorbitofrontal
48. right hemisphere middletemporal
49. right hemisphere parahippocampal
50. right hemisphere paracentral
51. right hemisphere parsopercularis
52. right hemisphere parsorbitalis
53. right hemisphere parstriangularis
54. right hemisphere pericalcarine
55. right hemisphere postcentral
56. right hemisphere posteriorcingulate
57. right hemisphere precentral
58. right hemisphere precuneus
59. right hemisphere rostralanteriorcingulate
60. right hemisphere rostralmiddlefrontal
61. right hemisphere superiorfrontal
62. right hemisphere superiorparietal
63. right hemisphere superiortemporal
64. right hemisphere supramarginal
65. right hemisphere frontalpole
66. right hemisphere temporalpole
67. right hemisphere transversetemporal
68. right hemisphere insula
70. left hemisphere mean
71. right hemisphere mean

:::

# Cortical surface area

71. Total whole brain

::: {.callout-note appearance="simple" collapse=true}

## Features that were not selected

1. lh-Banks of Superior Temporal Sulcus
2. lh-caudalanteriorcingulate
3. lh-caudalmiddlefrontal
4. lh-cuneus
5. lh-entorhinal
6. lh-fusiform
7. lh-inferiorparietal
8. lh-inferiortemporal
9. lh-isthmuscingulate
10. lh-lateraloccipital
11. lh-lateralorbitofrontal
12. lh-lingual
13. lh-medialorbitofrontal
14. lh-middletemporal
15. lh-parahippocampal
16. lh-paracentral
17. lh-parsopercularis
18. lh-parsorbitalis
19. lh-parstriangularis
20. lh-pericalcarine
21. lh-postcentral
22. lh-posteriorcingulate
23. lh-precentral
24. lh-precuneus
25. lh-rostralanteriorcingulate
26. lh-rostralmiddlefrontal
27. lh-superiorfrontal
28. lh-superiorparietal
29. lh-superiortemporal
30. lh-supramarginal
31. lh-frontalpole
32. lh-temporalpole
33. lh-transversetemporal
34. lh-insula
35. rh-Banks of Superior Temporal Sulcus
36. rh-caudalanteriorcingulate
37. rh-caudalmiddlefrontal
38. rh-cuneus
39. rh-entorhinal
40. rh-fusiform
41. rh-inferiorparietal
42. rh-inferiortemporal
43. rh-isthmuscingulate
44. rh-lateraloccipital
45. rh-lateralorbitofrontal
46. rh-lingual
47. rh-medialorbitofrontal
48. rh-middletemporal
49. rh-parahippocampal
50. rh-paracentral
51. rh-parsopercularis
52. rh-parsorbitalis
53. rh-parstriangularis
54. rh-pericalcarine
55. rh-postcentral
56. rh-posteriorcingulate
57. rh-precentral
58. rh-precuneus
59. rh-rostralanteriorcingulate
60. rh-rostralmiddlefrontal
61. rh-superiorfrontal
62. rh-superiorparietal
63. rh-superiortemporal
64. rh-supramarginal
65. rh-frontalpole
66. rh-temporalpole
67. rh-transversetemporal
68. rh-insula
69. Total left hemisphere
70. Total right hemisphere

:::

# Cortical thickness

7. lh-inferiorparietal [5](https://www.sciencedirect.com/science/article/pii/S0022347614009615), [6](https://pmc.ncbi.nlm.nih.gov/articles/PMC7462020/)
28. lh-superiorparietal [5](https://www.sciencedirect.com/science/article/pii/S0022347614009615), [6](https://pmc.ncbi.nlm.nih.gov/articles/PMC7462020/)
41. rh-inferiorparietal [5](https://www.sciencedirect.com/science/article/pii/S0022347614009615), [6](https://pmc.ncbi.nlm.nih.gov/articles/PMC7462020/)
62. rh-superiorparietal [5](https://www.sciencedirect.com/science/article/pii/S0022347614009615), [6](https://pmc.ncbi.nlm.nih.gov/articles/PMC7462020/)
71. Mean for whole brain [5](https://www.sciencedirect.com/science/article/pii/S0022347614009615), [6](https://pmc.ncbi.nlm.nih.gov/articles/PMC7462020/)

::: {.callout-note appearance="simple" collapse=true}

## Features that were not selected

1. lh-Banks of Superior Temporal Sulcus
2. lh-caudalanteriorcingulate
3. lh-caudalmiddlefrontal
4. lh-cuneus
5. lh-entorhinal
6. lh-fusiform
8. lh-inferiortemporal
9. lh-isthmuscingulate
10. lh-lateraloccipital
11. lh-lateralorbitofrontal
12. lh-lingual
13. lh-medialorbitofrontal
14. lh-middletemporal
15. lh-parahippocampal
16. lh-paracentral
17. lh-parsopercularis
18. lh-parsorbitalis
19. lh-parstriangularis
20. lh-pericalcarine
21. lh-postcentral
22. lh-posteriorcingulate
23. lh-precentral
24. lh-precuneus
25. lh-rostralanteriorcingulate
26. lh-rostralmiddlefrontal
27. lh-superiorfrontal
29. lh-superiortemporal
30. lh-supramarginal
31. lh-frontalpole
32. lh-temporalpole
33. lh-transversetemporal
34. lh-insula
35. rh-Banks of Superior Temporal Sulcus
36. rh-caudalanteriorcingulate
37. rh-caudalmiddlefrontal
38. rh-cuneus
39. rh-entorhinal
40. rh-fusiform
42. rh-inferiortemporal
43. rh-isthmuscingulate
44. rh-lateraloccipital
45. rh-lateralorbitofrontal
46. rh-lingual
47. rh-medialorbitofrontal
48. rh-middletemporal
49. rh-parahippocampal
50. rh-paracentral
51. rh-parsopercularis
52. rh-parsorbitalis
53. rh-parstriangularis
54. rh-pericalcarine
55. rh-postcentral
56. rh-posteriorcingulate
57. rh-precentral
58. rh-precuneus
59. rh-rostralanteriorcingulate
60. rh-rostralmiddlefrontal
61. rh-superiorfrontal
63. rh-superiortemporal
64. rh-supramarginal
65. rh-frontalpole
66. rh-temporalpole
67. rh-transversetemporal
68. rh-insula
69. Mean for left hemisphere
70. Mean for right hemisphere

:::

# Subcortical volumes

13. left-hippocampus [7](https://www.neurology.org/doi/abs/10.1212/WNL.0000000000201470), [10](https://pmc.ncbi.nlm.nih.gov/articles/PMC8082726/), [11](https://www.sciencedirect.com/science/article/pii/S2213158218301608)
28. right-hippocampus [7](https://www.neurology.org/doi/abs/10.1212/WNL.0000000000201470), [10](https://pmc.ncbi.nlm.nih.gov/articles/PMC8082726/), [11](https://www.sciencedirect.com/science/article/pii/S2213158218301608)
12. brain-stem [9](https://pmc.ncbi.nlm.nih.gov/articles/PMC8032213/)
41. wholebrain [8](https://journals.lww.com/headtraumarehab/abstract/2018/11000/quantitative_volumetric_imaging_and_clinical.9.aspx), [9](https://www.liebertpub.com/doi/abs/10.1089/neu.2016.4531)
29. right-amygdala, [11](https://www.sciencedirect.com/science/article/pii/S2213158218301608)
14. left-amygdala, [11](https://www.sciencedirect.com/science/article/pii/S2213158218301608)

::: {.callout-note appearance="simple" collapse=true}

## Features that were not selected

1. left-cerebral-white-matter
2. left-lateral-ventricle
3. left-inf-lat-vent
4. left-cerebellum-white-matter
5. left-cerebellum-cortex
6. left-thalamus-proper
7. left-caudate
8. left-putamen
9. left-pallidum
10. 3rd-ventricle
11. 4th-ventricle
15. csf
16. lesion
17. left-accumbens-area
18. left-ventraldc
19. right-cerebral-white-matter
20. right-lateral-ventricle
21. right-inf-lat-vent
22. right-cerebellum-white-matter
23. right-cerebellum-cortex
24. right-thalamus-proper
25. right-caudate
26. right-putamen
27. right-pallidum
30. right-lesion
31. right-accumbens area
32. right-ventraldc
33. wm-hypointensities
34. left-wm-hypointensities
35. right-wm-hypointensities
36. CC-Posterior
37. CC-Mid_Posterior
38. CC-Central
39. CC-Mid_Anterior
40. CC-Anterior
42. latventricles
43. allventricles
44. intracranialvolume
45. supratentorialvolume
46. subcorticalgrayvolume

:::
