# Loading in data

```{r}
library(abcdutils)
library(here)
library(readr)
library(metasnf)
library(mice)
library(ComplexHeatmap)
library(naniar)
library(dplyr)

input_path <- path_maker(here(paste0("data/abcd/inputs")))
raw_path <- path_maker(here(paste0("data/abcd/raw")))
core_path <- path_maker(here(paste0("data/abcd/core")))
misc_path <- path_maker(here(paste0("data/abcd/misc")))
sub_path <- path_maker(here(paste0("data/abcd/subjects")))
fig_path <- path_maker(here(paste0("data/abcd/results/figures")))
proc_path <- path_maker(here(paste0("data/abcd/results/processed")))

mtbi_subjects <- read_csv(sub_path("2024_03_12_mtbi_subjects.csv"))
mtbi_subjects <- mtbi_subjects$subjectkey

uninjured_subjects <- read_csv(sub_path("2024_03_12_uninjured_subjects.csv"))
uninjured_subjects <- uninjured_subjects$subjectkey

import <- function(path) {
    return(abcd_load(core_path(path)))
}
```

```{r}
source("abcd/functions.R")
```

```{r}
#rm_gord_cor_qc_mtbi <- read_csv(input_path("2024_03_12_rm_gord_cor_qc_mtbi.csv"))
#rm_subc_cor_qc_mtbi <- read_csv(input_path("2024_03_12_rm_subc_cor_qc_mtbi.csv"))
#dm_all_wmnd_qc_mtbi <- read_csv(input_path("2024_03_12_dm_all_wmnd_qc_mtbi.csv"))
#sm_cort_sa_qc_mtbi <- read_csv(input_path("2024_03_12_sm_cort_sa_qc_mtbi.csv"))
sm_cort_t_qc_mtbi <- read_csv(input_path("2024_03_12_sm_cort_t_qc_mtbi.csv"))
#sm_subc_v_qc_mtbi <- read_csv(input_path("2024_03_12_sm_subc_v_qc_mtbi.csv"))

#rm_gord_cor_mtbi <- read_csv(input_path("2024_03_12_rm_gord_cor_mtbi.csv"))
#rm_subc_cor_mtbi <- read_csv(input_path("2024_03_12_rm_subc_cor_mtbi.csv"))
#dm_all_wmnd_mtbi <- read_csv(input_path("2024_03_12_dm_all_wmnd_mtbi.csv"))
#sm_subc_v_mtbi <- read_csv(input_path("2024_03_12_sm_subc_v_mtbi.csv"))
sm_cort_t_mtbi <- read_csv(input_path("2024_03_12_sm_cort_t_mtbi.csv"))
#sm_cort_sa_mtbi <- read_csv(input_path("2024_03_12_sm_cort_sa_mtbi.csv"))
```

## Neuroimaging QC

```{r}
#mri_y_smr_vol_aseg <- import("imaging/mri_y_smr_vol_aseg.csv")
#mri_y_smr_thk_dsk <- import("imaging/mri_y_smr_thk_dsk.csv")
#mri_y_smr_area_dsk <- import("imaging/mri_y_smr_area_dsk.csv")
#mri_y_rsi_rnd_at <- import("imaging/mri_y_rsi_rnd_at.csv")
#mri_y_rsi_rnd_wm_dsk <- import("imaging/mri_y_rsi_rnd_wm_dsk.csv")
#mri_y_rsi_rnd_wm_dst <- import("imaging/mri_y_rsi_rnd_wm_dst.csv")
#mri_y_rsfmr_cor_gp_gp <- import("imaging/mri_y_rsfmr_cor_gp_gp.csv")
#mri_y_rsfmr_cor_gp_aseg <- import("imaging/mri_y_rsfmr_cor_gp_aseg.csv")

mri_y_qc_raw_smr_t1 <- abcd_load(core_path("imaging/mri_y_qc_raw_smr_t1.csv"))
mri_y_qc_raw_smr_t2 <- abcd_load(core_path("imaging/mri_y_qc_raw_smr_t2.csv"))
mri_y_qc_raw_rsfmr <- abcd_load(core_path("imaging/mri_y_qc_raw_rsfmr.csv"))
mri_y_qc_raw_dmr <- abcd_load(core_path("imaging/mri_y_qc_raw_dmr.csv"))

qc_smri(
    mri_y_qc_raw_smr_t1,
    t = 0,
    subjects = mtbi_subjects,
    metric = "qc"
)

qc_smri(
    mri_y_qc_raw_smr_t1,
    t = 0,
    subjects = mtbi_subjects,
    metric = "pc"
)

qc_smri(
    mri_y_qc_raw_smr_t2,
    t = 0,
    subjects = mtbi_subjects,
    metric = "qc"
)

qc_smri(
    mri_y_qc_raw_smr_t2,
    t = 0,
    subjects = mtbi_subjects,
    metric = "pc"
)

qc_dmri(
    mri_y_qc_raw_dmr,
    t = 0,
    subjects = mtbi_subjects,
    metric = "qc"
)

qc_dmri(
    mri_y_qc_raw_dmr,
    t = 0,
    subjects = mtbi_subjects,
    metric = "pc"
)

qc_rsfmri(
    mri_y_qc_raw_rsfmr,
    t = 0,
    subjects = mtbi_subjects,
    metric = "qc"
)

qc_rsfmri(
    mri_y_qc_raw_rsfmr,
    t = 0,
    subjects = mtbi_subjects,
    metric = "pc"
)
```


```{r}
mtbi_df <- list(
    "as_mtbi_mem_daze_mtbi" = as_mem_daze_mtbi,
    "as_mtbi_mechanism_mtbi" = as_mechanism_mtbi,
    "as_mtbi_loc_mtbi" = as_loc_mtbi,
    "d_pubertal_status_mtbi" = d_pubertal_status_mtbi,
    "d_interview_age_mtbi" = d_interview_age_mtbi,
    "d_mtbi_age_mtbi" = d_mtbi_age_mtbi,
    "d_sex_mtbi" = d_sex_mtbi,
    "d_income_mtbi" = d_income_mtbi,
    "d_race_mtbi" = d_race_mtbi,
    "mh_headaches_mtbi" = mh_headaches_mtbi,
    "mh_mtbi_count_mtbi" = mh_mtbi_count_mtbi,
    "sm_subc_v_qc_mtbi" = sm_subc_v_qc_mtbi,
    "sm_cort_t_qc_mtbi" = sm_cort_t_qc_mtbi,
    "sm_cort_sa_qc_mtbi" = sm_cort_sa_qc_mtbi,
    "dm_all_wmnd_qc_mtbi" = dm_all_wmnd_qc_mtbi,
    "rm_gord_cor_qc_mtbi" = rm_gord_cor_qc_mtbi,
    "rm_subc_cor_qc_mtbi" = rm_subc_cor_qc_mtbi,
    "p_loneliness_mtbi" = p_loneliness_mtbi,
    "p_screen_time_mtbi" = p_screen_time_mtbi,
    "p_sports_mtbi" = p_sports_mtbi,
    "p_exercise_mtbi" = p_exercise_mtbi,
    "p_prosocial_mtbi" = p_prosocial_mtbi,
    "p_family_function_mtbi" = p_fam_fn_mtbi,
    "p_parent_psych_mtbi" = p_parent_psych_mtbi,
    "cbcl_anxdep_mtbi" = cbcl_anxdep_mtbi,
    "cbcl_withdep_mtbi" = cbcl_withdep_mtbi,
    "cbcl_somatic_mtbi" = cbcl_somatic_mtbi,
    "cbcl_social_mtbi" = cbcl_social_mtbi,
    "cbcl_thought_mtbi" = cbcl_thought_mtbi,
    "cbcl_attention_mtbi" = cbcl_attention_mtbi,
    "cbcl_rulebreak_mtbi" = cbcl_rulebreak_mtbi,
    "cbcl_aggressive_mtbi" = cbcl_aggressive_mtbi,
    "sds_total_probs_mtbi" = sds_total_probs_mtbi
) |> merge_df_list(join = "full")

mtbi_df_no_qc <- list(
    "as_mtbi_mem_daze_mtbi" = as_mem_daze_mtbi,
    "as_mtbi_mechanism_mtbi" = as_mechanism_mtbi,
    "as_mtbi_loc_mtbi" = as_loc_mtbi,
    "d_pubertal_status_mtbi" = d_pubertal_status_mtbi,
    "d_interview_age_mtbi" = d_interview_age_mtbi,
    "d_mtbi_age_mtbi" = d_mtbi_age_mtbi,
    "d_sex_mtbi" = d_sex_mtbi,
    "d_income_mtbi" = d_income_mtbi,
    "d_race_mtbi" = d_race_mtbi,
    "mh_headaches_mtbi" = mh_headaches_mtbi,
    "mh_mtbi_count_mtbi" = mh_mtbi_count_mtbi,
    "sm_subc_v_mtbi" = sm_subc_v_mtbi,
    "sm_cort_t_mtbi" = sm_cort_t_mtbi,
    "sm_cort_sa_mtbi" = sm_cort_sa_mtbi,
    "dm_all_wmnd_mtbi" = dm_all_wmnd_mtbi,
    "rm_gord_cor_mtbi" = rm_gord_cor_mtbi,
    "rm_subc_cor_mtbi" = rm_subc_cor_mtbi,
    "p_loneliness_mtbi" = p_loneliness_mtbi,
    "p_screen_time_mtbi" = p_screen_time_mtbi,
    "p_sports_mtbi" = p_sports_mtbi,
    "p_exercise_mtbi" = p_exercise_mtbi,
    "p_prosocial_mtbi" = p_prosocial_mtbi,
    "p_family_function_mtbi" = p_fam_fn_mtbi,
    "p_parent_psych_mtbi" = p_parent_psych_mtbi,
    "cbcl_anxdep_mtbi" = cbcl_anxdep_mtbi,
    "cbcl_withdep_mtbi" = cbcl_withdep_mtbi,
    "cbcl_somatic_mtbi" = cbcl_somatic_mtbi,
    "cbcl_social_mtbi" = cbcl_social_mtbi,
    "cbcl_thought_mtbi" = cbcl_thought_mtbi,
    "cbcl_attention_mtbi" = cbcl_attention_mtbi,
    "cbcl_rulebreak_mtbi" = cbcl_rulebreak_mtbi,
    "cbcl_aggressive_mtbi" = cbcl_aggressive_mtbi,
    "sds_total_probs_mtbi" = sds_total_probs_mtbi
) |> merge_df_list(join = "full")

vis_miss(mtbi_df)

colnames(mtbi_df)

# Summarizing
mtbi_df_race5 <- mtbi_df
#mtbi_df_race5 <- mtbi_df_no_qc
mtbi_df_race5$"race" <- NULL
mtbi_df_race5 <- dplyr::full_join(
    mtbi_df_race5,
    d_race_5,
    by = "subjectkey"
)
#any_na_mtbi <- mtbi_df_race5[, colSums(is.na(mtbi_df_race5)) > 0]
any_na_mtbi <- mtbi_df_race5
any_na_mtbi$"race" <- mtbi_df_race5$"race"
mtbi_summary <- any_na_mtbi |>
    group_by(race) |>
    summarize(N = n())
mtbi_summary
missingness_by_race_plot <- any_na_mtbi |>
    gg_miss_var(
        facet = race,
        show_pct = TRUE
    ) +
    geom_text(
        data = mtbi_summary,
        x = ncol(any_na_mtbi) / 2,
        y = 13,
        aes(label = paste0("n = ", N)),
        hjust = 1,
        size = 5
    ) +
    theme(
      text = element_text(size = 10)
    )
missingness_by_race_plot

get_race

import <- function(path) {
    return(abcd_load(core_path(path)))
}
abcd_p_demo <- import("abcd-general/abcd_p_demo.csv")

d_race_5 <- get_race(
    abcd_p_demo,
    mtbi_subjects,
    asian_as_other = FALSE,
    t = 0
)


missingness_by_race_plot <- any_na_mtbi |>
    gg_miss_var(
        facet = race,
        show_pct = TRUE
    ) +
    geom_text(
        data = mtbi_summary,
        x = ncol(mtbi_df) / 2,
        y = 13,
        aes(label = paste0("n = ", N)),
        hjust = 1,
        size = 5
    ) +
    theme(
      text = element_text(size = 10)
    )
missingness_by_race_plot


?gg_miss_var

mtbi_df |>
    ggplot(
        aes(x = race, y = household_income)
    ) +
    geom_miss_point(
        size = 4,
        alpha = 0.5,
        position = "jitter",
        jitter = 0,
        width = 1
    ) +
    theme_bw()


to_missingness <- function(df) {
    df_char <- as.data.frame(apply(df, 2, as.character))
    df_char <- apply(
        df_char,
        2,
        function(x) {
            x[!is.na(x)] <- "1"
            x[is.na(x)] <- "0"
            return(x)
        }
    ) |> as.data.frame()
    df_num <- as.data.frame(apply(df_char, 2, as.numeric))
    return(df_num)
}

mtbi_missing <- to_missingness(mtbi_df)


mtbi_missing |> Heatmap()

cor(mtbi_missing)


complete_mtbi <- na.omit(mtbi_df_list)
```
