# Raw summaries {#sec-rawsummaries}

(Move to appendix) Some visualizations of the extracted data:

```{r}
library(abcdutils)
library(scabcd)
library(readr)
library(here)
library(dplyr)

input_path <- "data/abcd/inputs/pre-imputation/"
misc_path <- "data/abcd/misc/"


# Breakdown of how many kids had each number of mTBIs
mh_mtbi_count <- read_csv(here(paste0(input_path, "mh_mtbi_count.csv")))
table(mh_mtbi_count$mtbi_count)

# Plot of the times since each child had their latest mTBI
mtbi_detailed <- read_csv(here(paste0(misc_path, "mtbi_detailed.csv")))

# plotting function
scabcd_hist <- function(df, xval, xlabel = "", title = "", size = 20) {
    ggplot2::ggplot(df, ggplot2::aes_string(x = xval)) +
        ggplot2::geom_histogram(color = "darkblue", fill = "lightblue") +
        ggplot2::ggtitle(title) +
        ggplot2::xlab(xlabel) +
        ggplot2::ylab("Count") +
        ggplot2::theme_light(base_size = size)
}

scabcd_hist(mtbi_detailed,
            title = "Histogram of times since latest mTBI",
            xval = "latest_mtbi_mpi",
            xlabel = "Time since last mTBI")
```

```{r echo = FALSE}
# Export the figure

scabcd_ggsave <- function(path, plotname) {
    carbon_path <- paste0(path, plotname)
    repo_path <- paste0("figures/abcd/", plotname)
    print("Warning: This will overwrite files located at:")
    print(paste0("[1]: ", here::here(carbon_path)))
    print(paste0("[2]: ", here::here(repo_path)))
    proceed <- readline(prompt = "Proceed? [N/y]: ")
    if (proceed == "y") {
        ## For carbon
        ggplot2::ggsave(here::here(carbon_path),
            width = 10,
            height = 10)
        # For this repo
        ggplot2::ggsave(here::here(repo_path),
            width = 10,
            height = 10)
    }
}

scabcd_ggsave(path = "data/abcd/processed/prashanth/figures-and-tables/",
              plotname = "time_since_latest_mtbi_full.png")
```

```{r}
d_pubertal_status <- read_csv(here(paste0(input_path, "d_pubertal_status.csv")))
scabcd_hist(df = d_pubertal_status,
            xval = "pubertal_status",
            xlabel = "Pubertal status",
            title = "Distribution of pubertal status reports")
```

```{r echo = FALSE}
# Export the figure
scabcd_ggsave(path = "data/abcd/processed/prashanth/figures-and-tables/",
              plotname = "puberty_distributions.png")
```

```{r}
d_income <- read_csv(here(paste0(input_path, "d_income.csv")))
scabcd_hist(d_income,
            xval = "household_income",
            title = "Household incomes of mTBI subjects",
            xlabel = "Income tier (1 = 0-50k, 2 = 50-100k, 3 = 100k+)")
```

```{r echo = FALSE}
# Export the figure
scabcd_ggsave(path = "data/abcd/processed/prashanth/figures-and-tables/",
              plotname = "income_distributions.png")
```

```{r}
# Distribution of subjects by race
d_race_condensed <- read_csv(here(paste0(input_path, "d_race_cd.csv")))
d_race_expanded <- read_csv(here(paste0(input_path, "d_race_ed.csv")))
format_race(d_race_condensed, "dummied")
format_race(d_race_expanded, "dummied")
```
