# Functions in the scabcd package

## Generic utility functions

```{r, code = readLines("/home/prashanth/documents/scabcd/R/utils.R"), eval = FALSE}
```

## Plotting

```{r, code = readLines("/home/prashanth/documents/scabcd/R/plotting.R"), eval = FALSE}
```


## Traumatic brain injury

```{r, code = readLines("/home/prashanth/documents/scabcd/R/tbi.R"), eval = FALSE}
```


## Subject list generation

```{r, code = readLines("/home/prashanth/documents/scabcd/R/get_subjects.R"), eval = FALSE}
```


## Acute symptoms

```{r, code = readLines("/home/prashanth/documents/scabcd/R/acute_symptoms.R"), eval = FALSE}
```


## Medical history

```{r, code = readLines("/home/prashanth/documents/scabcd/R/med_history.R"), eval = FALSE}
```


## Demographics

```{r, code = readLines("/home/prashanth/documents/scabcd/R/demographics.R"), eval = FALSE}
```


## Neuroimaging

```{r, code = readLines("/home/prashanth/documents/scabcd/R/neuroimaging.R"), eval = FALSE}
```


## Psychosocial resilience

```{r, code = readLines("/home/prashanth/documents/scabcd/R/psych_resilience.R"), eval = FALSE}
```
